### ISSUE TITLE
PDF generation

### ISSUE THREAD

**Issue by victorklos** [pdoc3/pdoc#1]
### Expected Behavior

A generated pdf document after `pdoc3 --pdf time`.

### Actual Behavior

```
usage: pdoc3 [-h] [--version] [--filter STRING] [--html] [--html-dir DIR]
             [--html-no-source] [--overwrite] [--external-links]
             [--template-dir DIR] [--link-prefix STRING] [--http HOST:PORT]
             MODULE [MODULE ...]
pdoc3: error: unrecognized arguments: --pdf
```

### Steps to Reproduce

1. Read homepage <https://pdoc3.github.io/pdoc/>
2. Execute command above

### Additional info

- pdoc version: 0.5.1

**Comment by victorklos** [comment]
BTW I have some experience with `pandoc` so if you need help please let me know...

**Comment by kernc** [comment]
Thanks. How would you implement PDF generation using pandoc?

**Comment by victorklos** [comment]
First step would be to generate a single page output (even HTML would be interesting in itself, e.g. if you want to email the documentation). Pandoc needs an input and a template. The input could be said HTML document, or markdown or what it is you currently generate. The template is in LaTeX. Pandoc would than be required on the path.

Creating PDF files through LaTeX is a bit of a pain through, as it depends on texlive which is over 2GB when installed fully. Maybe offer the option to compile through docker? Most developers have that installed nowadays I guess...

Some alternatives are possible:
- focus on a single-page HTML output and convert it through a browser or local PDF printer
- write your own PDF output generator, e.g. based on reportlab or pdfkit (not recommended)

**Comment by kernc** [comment]
I tried pandoc to convert [pdoc documentation index.html](https://pdoc3.github.io/pdoc/doc/pdoc/) as well as some other HTML. It didn't work. The latex converters seem picky about everything, including non-ASCII characters and referenced SVG images. There are some indications (https://github.com/jgm/pandoc/issues/1793#issuecomment-286668030) that alternative engines should be preferred for better results. Engine `html5`, though, requires [wkhtmltopdf](https://wkhtmltopdf.org/downloads.html), which itself is a largish binary the user would require and can then as well be used standalone.

Pdoc indeed already contains some provisions for printing:

https://github.com/pdoc3/pdoc/blob/e7868e286c260650daeee478a8b2f1e9ed4c8767/pdoc/templates/html.mako#L353

https://github.com/pdoc3/pdoc/blob/e7868e286c260650daeee478a8b2f1e9ed4c8767/pdoc/templates/css.mako#L302-L381

If we could somehow leverage the common web browsers, some instance of which exists in almost all environments, that'd be great! I was looking into Selenium / WebDriver API and whether it supports printing to file, but it appears this is not the (common) case.

I found [this Reddit thread](https://www.reddit.com/r/linux/comments/7wcd0g/generating_files_for_printing/), comparing several possible approaches, and of the listed I feel like preferring [running Chrome](https://developers.google.com/web/updates/2017/04/headless-chrome#create_a_pdf_dom) the most.

```bash
chromium --headless --disable-gpu --print-to-pdf=output.pdf input.html
```
Second to that maybe [WeasyPrint](https://weasyprint.org/), but that has a [list of dependencies](https://github.com/Kozea/WeasyPrint/blob/afc773a440e21be3ca3b24b1f2c12342b54229cf/setup.cfg#L38-L45) that may not be so easy to support in all environments (e.g. Windos without a C/C++ compiler).

**Comment by victorklos** [comment]
I like the chromium route best. How much work would it be to generate a single HTML file? The current index file can become the TOC, the rest chapters, all links internal.

**Comment by kernc** [comment]
Currently, every module is rendered and written out separately:

https://github.com/pdoc3/pdoc/blob/e7868e286c260650daeee478a8b2f1e9ed4c8767/pdoc/cli.py#L253-L275

So not too much, but it would certainly bear generating a new mako template that handles a list of modules and in which all `pdoc.Doc.url()` calls are trimmed to [URL fragments](https://en.wikipedia.org/wiki/Fragment_identifier). Then, I guess, a new command line switch can be added.

Is ths something you would care to work on?

**Comment by kernc** [comment]
Or, probably better yet, _adapting [existing HTML template](https://github.com/pdoc3/pdoc/blob/master/pdoc/templates/html.mako)_. It already handles a list of modules in a way when pdoc is run as a development web server:
https://github.com/pdoc3/pdoc/blob/e7868e286c260650daeee478a8b2f1e9ed4c8767/pdoc/templates/html.mako#L66-L81

**Comment by kernc** [comment]
@victorklos I made some progress https://github.com/pdoc3/pdoc/pull/20 using markdown and pandoc. If you're still interested, please have a look.

**Comment by victorklos** [comment]
Great! I will, but earliest this weekend...

**Comment by victorklos** [comment]
The generated PDF already looks great though! Maybe add some `pdoc3` styling later on.

**Comment by kernc** [comment]
It now prints straight to markdown, so any styling would need to be overridden on pandoc/LaTeX level, or a new set of CSS written and included as raw HTML for conversion through intermediate HTML.
