### ISSUE TITLE
Bug: It seems the `Returns` section does not support multiple lines for single object

### ISSUE THREAD

**Issue by wq2012** [pdoc3/pdoc#10]
### Expected Behavior

Like `Args`, I expect `Returns` and `Raises` to support multiple lines to describe a single object.

### Actual Behavior

The second line is treated as a new paragraph.

This is my code:
```
  Returns:
    sampled_index_sequences: (a list of numpy arrays) - a list of subsampled
      block-preserving permuted sequences. For example,
      ```
      sampled_index_sequences =
      [[10,11,12,1,2,6],
       [6,1,2,10,11,12],
       [1,2,10,11,12,6],
       [6,1,2,10,11,12],
       [1,2,6,10,11,12]]
      ```
      The length of "sampled_index_sequences" is "number_samples".
```

This is what I got:
![screenshot from 2019-01-24 11-33-04](https://user-images.githubusercontent.com/3002724/51692893-dc847080-1fcb-11e9-8e6e-dee6858362d9.png)

The should not be a new paragraph between "sampled" and "block-preserving".

### Steps to Reproduce

N/A

### Additional info

- pdoc version:
0.5.1

**Comment by kernc** [comment]
Thanks! This had worked in 0.5.1 (you are using master), see [pdoc.test.example_pkg.google() Raises AttributeError](https://pdoc3.github.io/pdoc/doc/pdoc/test/example_pkg/index.html#pdoc.test.example_pkg.google).
https://github.com/pdoc3/pdoc/blob/e2739ced41b66450138c5372378ded8543b9c309/pdoc/test/example_pkg/__init__.py#L161-L165

**Comment by kernc** [comment]
It _didn't_ work in 0.5.1. Now hopefully is fixed.

**Comment by wq2012** [comment]
Works now. That's great. Thanks!
