### ISSUE TITLE
Link documentation to source code at its online repository like GitHub

### ISSUE THREAD

**Issue by dhimmel** [pdoc3/pdoc#100]
@zietzm and I recently started [using pdoc3 for a project](https://hetio.github.io/xswap/) and love its simplicity and power.

Is there any way to have the documentation for a function link to its source code on an online repository (like GitHub or GitLab)?

For example, see [these docs](https://hetio.github.io/xswap/preprocessing.html#xswap.preprocessing.load_processed_edges) which look like:

> ![image](https://user-images.githubusercontent.com/1117703/63730998-be217480-c83b-11e9-920f-0357c945dc04.png)

In addition to the "source code" snippet, would it be possible to link to the [corresponding source code on GitHub](https://github.com/hetio/xswap/blob/d26165f91cfff0b73e9c2a6183726ca19fd1ba5e/xswap/preprocessing.py#L15-L24) which looks like:

> ![image](https://user-images.githubusercontent.com/1117703/63731138-47d14200-c83c-11e9-847d-9d0d0714c51d.png)

Linking to the source code at the hosting repository would be helpful for:

1. browsing the relevant source code outside of the specific function.
2. copying and pasting the URL with lines selected into issues.
3. making it easier for users to make small pull requests right from their browser
4. getting versioned source code links that can be persistently linked to

I am guessing that currently pdoc3 is unaware of the online repository where the code is hosted, so I'm guessing this would take some extra configuration to make possible?

**Comment by kernc** [comment]
Of the top of my head, sans any testing, you could achieve something like this for functions and types by adapting your template and call a function like the following for each of those objects:
```py
import inspect
import subprocess

last_commit = subprocess.run(['git', 'rev-list', '--max-count=1', 'HEAD'],
                             stdout=subprocess.PIPE, text=True).stdout

def gh_url(dobj: pdoc.Doc):
    try:
        lines, start_line = inspect.getsourcelines(dobj.obj)
        end_line = start_line + len(lines)
        abs_path = inspect.getmodule(dobj.obj).__file__
        file_path = os.path.relpath(abs_path, os.getcwd())  # Project-relative path
        return f'<a href="https://github.com/hetio/xswap/blob/{last_commit}/{file_path}#L{start_line}-L{end_line}">Source on GitHub</a>'
    except Exception:
        return ''
```
It is based on the following additional assumptions: 
* your cwd is a git repository,
* your cwd is the project root directory, 
* the current branch is the canonical reference branch synced to GitHub remote.

Feel free to make it work (:sweat_smile:) and let me know how it turns out for you.

**Comment by kernc** [comment]
Indeed, you might even override just _html.mako_, adding the function into a code block at the top and adapt the `show_source(d)` section as needed, then run with `--template-dir`.

**Comment by kernc** [comment]
> Do you think pdoc3 would have any interest in supporting this feature via a `show_source_link` configuration option that could be enabled?

Looks very good, absolutely!

How about more simply configurable
```py
online_source_link = 'https://github.com/ORG/PROJECT/blob/{commit}/{file_path}#L{start_line}-L{end_line}'
```
commented-out by default, documented with what values get interpolated?

**Comment by dhimmel** [comment]
> How about more simply configurable

So the idea here is that `online_source_link` is a string that can include supported templating variables? Where would users set this variable (sorry very inexperienced with pdoc3 configuration)?

Not having to figure out which hosting service was being used (i.e. GitHub, GitLab, BitBucket, or something self-hosted) would make the implementation much simpler. I agree let's just leave that to the user.

I'm happy to take a stab at the implementation, especially if you let me know which source files to edit.

**Comment by kernc** [comment]
> Where would users set this variable?

[config.mako](https://github.com/pdoc3/pdoc/blob/master/pdoc/templates/config.mako) with `--template-dir`, or `--config`.

I think the rest could go under `pdoc.html_helpers`.
