### ISSUE TITLE
pdoc3 and mkdocs

### ISSUE THREAD

**Issue by PanRe** [pdoc3/pdoc#105]
Hello,

I am new to Python and currently i am looking for good tools for documentation. Since Sphinx is an overkill, i would like to use mkdocs for prosa documentation. Unfortunately, mkdocs has no support for API documentation. Pdoc, however, is very nice for this job.

My question would be, is there any way to combine mkdocs and pdoc? Is there a pdoc plugin for mkdocs available?

Thanks a lot in advance!

**Comment by kernc** [comment]
Take a look at [Portray](https://github.com/timothycrosley/portray).

**Comment by coderatul** [comment]
> Hello,
> 
> I am new to Python and currently i am looking for good tools for documentation. Since Sphinx is an overkill, i would like to use mkdocs for prosa documentation. Unfortunately, mkdocs has no support for API documentation. Pdoc, however, is very nice for this job.
> 
> My question would be, is there any way to combine mkdocs and pdoc? Is there a pdoc plugin for mkdocs available?
> 
> Thanks a lot in advance!

hey @PanRe 

you can output docs as markdown using `-o DIR =` flag then add those files in mkdocs

**Comment by spirali** [comment]
Hi, 
I have the same problem and I have written a simple plugin to mkdocs for linking pdoc:

https://github.com/spirali/mkdocs-pdoc-plugin/
