### ISSUE TITLE
Error in generated documentation

### ISSUE THREAD

**Issue by frosenek** [pdoc3/pdoc#108]
pdoc3 builds flawed documentation for the peewee project (https://github.com/coleifer/peewee).

### Expected Behavior

pdoc3 builds documentation

### Actual Behavior

![image](https://user-images.githubusercontent.com/7946595/65076333-10683800-d999-11e9-85d1-757cb0f2235f.png)

![image](https://user-images.githubusercontent.com/7946595/65076388-2f66ca00-d999-11e9-9cb0-9b73f7d57ada.png)

### Steps to Reproduce

1. pdoc3 --http : peewee

### Additional info

- pdoc version: 0.6.3

**Comment by kernc** [comment]
A simple workaround is to apply [Mako's `h` filter](https://docs.makotemplates.org/en/latest/filtering.html) to `params` and `returns` strings here:
https://github.com/pdoc3/pdoc/blob/44c9606d441cbf60630fc1402f868f1fbb51bd1e/pdoc/templates/html.mako#L97

This won't name the default value `SENTINEL` though. :thinking:

**Comment by kernc** [comment]
> This won't name the default value `SENTINEL` though. :thinking:

Some options are:
* AST parsing, extracting the default value as specified in source by ast node's `lineno` 
 and `col_offset` (mucky and error-prone). <details>
    ```py
    def _arg_defaults(self):
        tree = _ast_parse(self)
        if tree is None:
            return {}
        args = tree.body[0].args
        source = inspect.getsource(self.obj).splitlines()

        defaults_offsets = {}
        breakpoints = sorted((i.lineno, i.col_offset)
                             for i in (args.args + [args.vararg] + 
                                       args.kwonlyargs + [args.kwarg] + 
                                       tree.body[0].body))
        for arg, default_value in (list(zip(args.args[::-1], args.defaults[::-1]))[::-1] +
                                   list(zip(args.kwonlyargs, args.kw_defaults))):
            line0, col0 = default_value.lineno, default_value.col_offset
            line1, col1 = next(brk for brk in breakpoints if brk > (line0, col0))
            if line0 == line1:
                text = source[line0 - 1][col0:col1 - 1]
            else:
                assert line1 > line0
                text = (source[line0 - 1][col0:] + 
                        '\n'.join(source[line0:line1 - 1]) + 
                        source[line1 - 1][:col1 - 1])
            defaults_offsets[arg.arg] = text.rstrip(',* \n\r\t')
        return defaults_offsets
    ```
    </details>
* `gc.get_referrers()`, but this results in scope-local identifiers, e.g.
  ```py
  def foo(a=some.package.SomeClass.class_variable)  # results in just 'class_variable'
  ```
* additional complex overrides in `safe_default_value()`
  https://github.com/pdoc3/pdoc/blob/148237b14625edcd5456c9abd45e3ec89de7f157/pdoc/__init__.py#L1102-L1119
* ...?
