### ISSUE TITLE
Markdown lists in the docstring seems to be ignored.

### ISSUE THREAD

**Issue by USSX-Hares** [pdoc3/pdoc#109]
Markdown lists in the docstring seems to be ignored.

### Example:
```python
def dump_config(conf: ConfigTree, format: str = 'json', prefix: str = "Config dump:") -> str:
    """
    Dumps the specified `pyhocon.ConfigTree` in specified format.
    For the *pyhocon* release 0.4.0, the following formats are allowed:
     - json (default)
     - properties
     - hocon
     - yaml
     """
     
     pass
```

### Expected:
Dumps the specified `pyhocon.ConfigTree` in specified format.
For the *pyhocon* release 0.4.0, the following formats are allowed:
 - json (default)
 - properties
 - hocon
 - yaml

![image](https://user-images.githubusercontent.com/29100587/65380871-98c64000-dced-11e9-9341-a89d579b266b.png)

### Actual:
Dumps the specified `pyhocon.ConfigTree` in specified format.
For the *pyhocon* release 0.4.0, the following formats are allowed: - json (default) - properties - hocon - yaml

![image](https://user-images.githubusercontent.com/29100587/65380859-5e5ca300-dced-11e9-96af-7f32aeb29bf9.png)

### Additional info

- pdoc version: 0.6.3

**Comment by kernc** [comment]
[Lists do work](https://pdoc3.github.io/pdoc/doc/pdoc/#supported-rest-directives).

You seem to be missing **a blank line** between the introductory paragraph and the list. Github-Flavored Markdown maybe supports the conversion without it, but python markdown, apparently, does not:
```bash
$ echo -e 'Foo:\n- list item' | markdown_py
<p>Foo:
- list item</p>

$ echo -e 'Foo:\n\n- list item' | markdown_py
<p>Foo:</p>
<ul>
<li>list item</li>
</ul>
```
