### ISSUE TITLE
Partial functions/methods are ignored

### ISSUE THREAD

**Issue by USSX-Hares** [pdoc3/pdoc#111]
Partial dispatch is ignored, even if included in module exports (`__all__`)

### Example:
```python
from functools import wraps, partial

def my_func(a: str, b: str = 'test', *, z: str):
    """
    Some documentation here
    """
    
    pass
my_func_simple = wraps(my_func)(partial(my_func, z='foo'))

@wraps(my_func_simple)
def my_func_not_simple(*args, **kwargs):
    return my_func_simple(*args, **kwargs)

__all__ = \
[
    'my_func',
    'my_func_simple',
    'my_func_not_simple',
]
```

### Expected:
All 3 functions are documented

### Actual:
Only `my_func` and `my_func_not_simple` are documented.
`my_func_simple` is missing.
![image](https://user-images.githubusercontent.com/29100587/65380948-150d5300-dcef-11e9-9256-969ecf5e7eb6.png)

### Additional info

- pdoc version: 0.6.3

**Comment by kernc** [comment]
The problem stems from the fact that `inspect.isroutine()` returns False for `functools.partial` objects ...
https://github.com/pdoc3/pdoc/blob/44c9606d441cbf60630fc1402f868f1fbb51bd1e/pdoc/__init__.py#L564-L566

**Comment by kernc** [comment]
But `functools.partial` object, while callable, is not really a function. Extracting the signature and other particulars (from `.func` attribute) is too implementation-specific and wouldn't necessarily work for other similar wrappers.

In light of few strong arguments pro and an elegant workaround available (cf. `my_func_not_simple`), I humbly vote to close.
