### ISSUE TITLE
Construct docstring Args sections from signatures

### ISSUE THREAD

**Issue by USSX-Hares** [pdoc3/pdoc#112]
It would be nice to automatically generate function/method argument types from its signature
(i.e., by calling `inspect.signature`) if the docstring provides no such information.

It would be helpful in linking the difficult types.
However, it can go wrong with the TypeVar's.

```python
def my_func(a: str, b: str = 'test', *, z: str) -> str:
    """
    Some documentation here
    """
    
    pass
```
### Expected Behavior

Something like that
![image](https://user-images.githubusercontent.com/29100587/65380988-125f2d80-dcf0-11e9-8e57-8fd347804c49.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/29100587/65380973-cca26500-dcef-11e9-94d0-deb931ad61be.png)

### Additional info

- pdoc version: 0.6.3.

**Comment by kernc** [comment]
Have a look at `show_type_annotations` config tunable.
https://github.com/pdoc3/pdoc/blob/44c9606d441cbf60630fc1402f868f1fbb51bd1e/pdoc/templates/config.mako#L9
You can set it by running pdoc as
```bash
pdoc --config show_type_annotations=True ...
```
It's not _exactly_ what you ask here (won't create or modify prose text sections), but it should make the declared types visible in the signature.

**Comment by kernc** [comment]
It so stands that Python projects should foremost be documented via code and then via docstrings. Automatic code generation (i.e. inserting missing docstrings) is out of scope for pdoc, but should instead be handled at an IDE / project build level. As an IDE, PyCharm offers to [auto-generate docstrings](https://www.jetbrains.com/help/pycharm/creating-documentation-comments.html#) similar to above, with several styles to choose from (Numpydoc, Google, reST, ...).
