### ISSUE TITLE
PEP-484 type hints don't work with complex nested/stored types

### ISSUE THREAD

**Issue by gdude2002** [pdoc3/pdoc#114]
In testing with pdoc, I've noticed some problems when trying to represent particularly complex type hints.

Let's say we have the following stored in, for example, a `types.py`.

```py
FilterType = Union[Filter, Callable[[str, Path], bool]]
ParserType = Tuple[Union[Parser, Callable[[str, Path], Optional[object]]]]
ProcessorType = Union[Processor, Callable[[str, object, Path], Optional[object]]]

Pipeline = Tuple[
    FilterType, ParserType, ProcessorType
]
```

This is a pretty common way to represent complex type hints. Following that, let's run pdoc: `pdoc --html --force -c show_type_annotations=True comect.sidecar`

### Expected Behavior

Here's one possible output, created using "inspect element" in the browser.

![image](https://user-images.githubusercontent.com/204153/66034239-c89cf100-e500-11e9-8207-656dd54c1993.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/204153/66034060-693ee100-e500-11e9-9f57-e63d671d0215.png)

### Additional info

- pdoc3 version: 0.7.0
- python version: 3.7.4

**Comment by kernc** [comment]
Regression, introduced in https://github.com/pdoc3/pdoc/commit/148237b14625edcd5456c9abd45e3ec89de7f157. :grimacing: Thanks.
