### ISSUE TITLE
"documentation.md" not included in documentation

### ISSUE THREAD

**Issue by git-n-pissed** [pdoc3/pdoc#118]
### Expected Behavior
"documentation.md" should be included in my docs like it is in the pdoc example

### Actual Behavior
"documentation.md" is not included in my docs like it is in the pdoc example

### Steps to Reproduce

1. Create a file named "documentation.md" at the root of your module which contains some additional info about your module.
2. Run `pdoc`.  The exact command I'm using is `pdoc --force --html --output-dir documentation .`
3. Note that "documentation.md" is not included in your documentation like it is in the pdoc documentation.

### Additional info

- pdoc version: 0.7.1

When you browse to https://pdoc3.github.io/pdoc/doc/pdoc/ you are greeted with a bunch of helpful info under "Index" in the left navigation column.  The only place this info exists in the pdoc repo is in the file "documentation.md".  The only place "documentation.md" is referenced is in \_\_init\_\_.py.  How is the info from "documentation.md" getting into the final documentation build by pdoc?

**Comment by git-n-pissed** [comment]
Nevermind.  I figured it out.  Seems obvious now.  The file "documentation.md" was being included _because_ of the comment in \_\_init\_\_.py:

```
"""
Python package `pdoc` provides types, functions, and a command-line
interface for accessing public documentation of Python modules, and
for presenting it in a user-friendly, industry-standard open format.
It is best suited for small- to medium-sized projects with tidy,
hierarchical APIs.

.. include:: ./documentation.md
"""
```

Feel free to close this issue.

**Comment by kernc** [comment]
See [docs](https://pdoc3.github.io/pdoc/doc/pdoc/#supported-rest-directives) for additional supported reStructuredText directives.
