### ISSUE TITLE
Feature request: Add means to exclude items (modules, functions, etc.) from being included in the docs besides using the _ prefix

### ISSUE THREAD

**Issue by b52** [pdoc3/pdoc#12]
The title basically says it all.

**Comment by kernc** [comment]
Have you tried [`__pdoc__` dict](https://pdoc3.github.io/pdoc/doc/pdoc/#overriding-docstrings-with-__pdoc__)? I guess that could go with slightly more emphasis.

**Comment by kernc** [comment]
Clearer rewording welcome!

**Comment by b52** [comment]
You are right, it is indeed possible with `__pdoc__[MY_SYMBOL] = False`. I just somewhat skipped this part in the README it seems.

**Comment by Basem-Gaber** [comment]
Where exactly should the __pdoc__ dict be placed?
I can't tell from the documentation.

Do I place it in the python file that has the functions that I need to exclude? 
Is it just another line of code? Or is it a part of the docstring?

If you can share a sample that would be much appreciated.

I tried placing it as part of the code but got the following error : `__pdoc__ is not defined `
I tried placing it as part of the docstring but it had no effect at all.

**Comment by shner-elmo** [comment]
Does `__pdoc__[key] = False` still work? I cant get it working
