### ISSUE TITLE
Type annotations for variables/properties

### ISSUE THREAD

**Issue by whitelynx** [pdoc3/pdoc#121]
Example code:
```py
class Porkline:
    """A porkline. A porkline corresponds to one example class."""

    type: str = None
    """The porkline type"""

    def __init__(self, name: str) -> None:
        self.name: str = name
        """The porkline name"""

    def compare(self, name: str) -> bool:
        """Check if the porkline's name matches the given name."""
        return name == self.name
```

### Expected Behavior

In the given example, the types of `Porkline.type` and `self.name` should be shown in the documentation.

### Actual Behavior

The annotated types are missing from the documentation.

![2019-11-05-141226_803x628_scrot](https://user-images.githubusercontent.com/285264/68238056-60956b00-ffd6-11e9-8ed7-aacdb0d6c7cd.png)

### Additional info

- pdoc version: 0.7.1

**Comment by kernc** [comment]
This is the relevant place if you care to tweak it:
https://github.com/pdoc3/pdoc/blob/1b644f6e86a5da4922679a8db540b83f8362ef08/pdoc/__init__.py#L252-L254
