### ISSUE TITLE
support unusual constructors by using inspect.signature() on class directly

### ISSUE THREAD

**Issue by programmerjake** [pdoc3/pdoc#124]
I'm currently writing a Python extension in Rust using [PyO3](https://pyo3.rs/). PyO3 uses `__new__` instead of `__init__` due to peculiarities needed by Rust's memory safety model.

It would be nice to support documenting the constructor signature by using `inspect.signature()` on the class directly rather than on the `__init__` or `__new__` method, since that also picks up `cls.__text_signature__` derived from the class's documentation.

**Comment by kernc** [comment]
This is the class signature entry point:
https://github.com/pdoc3/pdoc/blob/3a5e1d1241562691cb64584add3c8ed647ea2505/pdoc/__init__.py#L888-L903
If the line is changed to:
```py
params = Function._params(self.obj, ...)
```
and the redundant line after is removed, it all still seems to work and looks cleaner.

Can you propose a simple test case?

**Comment by programmerjake** [comment]
Here's a relatively simple test case:
https://github.com/programmerjake/rust-python-test/tree/doc-test

Build instructions (tested on Ubuntu 18.04 x86_64, in CPython 3.6 venv):
Install Rust toolchain:
```sh
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```
Restart terminal window to put Rust in `$PATH` (added to `.bashrc`).

Install build tool:
```sh
pip install maturin
```
Checkout code:
```sh
git clone -b doc-test https://github.com/programmerjake/rust-python-test.git
cd rust-python-test
```
Switch Rust to use known-working nightly version in `rust-python-test` directory:
```sh
rustup override set nightly-2019-07-19
```
Build and install (like setup.py develop):
```sh
maturin develop
```
Generate docs using pdoc3
```sh
pdoc rust_python_test
```

**Comment by programmerjake** [comment]
If you're not ok with using Rust, I can try to write a C version, but it may take some time as I'm not familiar with writing CPython extensions in C.

**Comment by programmerjake** [comment]
I'm not aware of a way to create the correct classes using pure Python.

**Comment by programmerjake** [comment]
Built wheels and source for convenience: [rust_python_test_wheels.zip](https://github.com/pdoc3/pdoc/files/3863215/rust_python_test_wheels.zip)

**Comment by kernc** [comment]
> I'm not aware of a way to create the correct classes using pure Python.

I'm so sorry for the effort you needlessly put into it above. Pure Python test case is indeed the only one I'd consider.

I'll think of something.

**Comment by kernc** [comment]
I think this issue is somewhat related to this TODO marker:
https://github.com/pdoc3/pdoc/blob/3a5e1d1241562691cb64584add3c8ed647ea2505/pdoc/__init__.py#L1084-L1087
https://github.com/pdoc3/pdoc/blob/3a5e1d1241562691cb64584add3c8ed647ea2505/pdoc/__init__.py#L1095-L1101
Unfortunately, `__text_signature__` (or whatever) doesn't seem to work for either `itertools.count` nor `numpy.array`. :confused:

**Comment by programmerjake** [comment]
`__text_signature__` is only used by `inspect.signature` when it's on a C (or other non-Python) function.

> I'm not aware of a way to create the correct classes using pure Python.

I am a relative beginner at Python, so there may be a way that I'm not aware of, but, from reading `inspect.signature`'s source, it appears as though it completely bypasses that code-path for pure-Python functions.

We may be able to create a pure-Python test by doing something like (not tested):
```python
class MyClass:
    def __new__(cls, value):
        """ docs for new """
        raise NotImplementedError()
```

**Comment by kernc** [comment]
> by doing something like (not tested)

In order to follow the correct execution path, both `getattr(cls, '__new__')` and `getattr(cls, '__init__')` would need to fail, which is not assured by raising — the attributes (methods) still exist.

After some mistrials of my own, I guess I'm happy to refrain from pursuing further occult edge cases and just apply the fix as is. :sweat_smile:

**Comment by programmerjake** [comment]
should I make a pull request?

**Comment by kernc** [comment]
That's always the preferred approach to have things fixed promptly and satisfactorily. :sweat_smile: If you have something ready, welcome. Otherwise I'll push something by the weekend. :+1:

**Comment by kernc** [comment]
Pushed it. It's a single line change and should be found working in the next release shortly. For the life of me, I could not come up with a working unit test. If you can think of something, PR welcome!

**Comment by programmerjake** [comment]
Figured out a test case:
```python3
class A:
    def f(a, b, c=None, *, d=1, e):
        pass
    __signature__ = inspect.signature(f)
    del f
```

I'm not sure where the test case should go so I didn't make a PR.

**Comment by kernc** [comment]
I think `pdoc.test.ApiTest.test_Class_params()` (maybe with a comment, issue link) should be wonderful!
