### ISSUE TITLE
Calling pdoc3 inside path containing spaces fails within virtual environment

### ISSUE THREAD

**Issue by smonsays** [pdoc3/pdoc#127]
When I try to call `pdoc3` from within a path that contains spaces, bash complains with `bad interpreter: No such file or directory` showing the cut-off path up until the first space.

### Steps to Reproduce

1. Create directory containing at least one space
2. Evoke pdoc from inside that directory

### Additional info

- pdoc version: 0.7.2

**Comment by kernc** [comment]
The following workflow works for me:
```bash
$ mkdir /tmp/foo\ dir
$ cd /tmp/foo\ dir
$ touch xx.py
$ pdoc3 xx.py
```
What am I missing?

What OS, version?

**Comment by smonsays** [comment]
Oh interesting. I think the difference might be that I am calling pdoc3 from inside a virtual environment. For me the following fails:
```
$ mkdir /tmp/foo\ dir
$ cd /tmp/foo\ dir
$ touch xx.py
$ python -m venv .myenv
$ source .myenv/bin/activate
$ pip install pdoc3
$ pdoc3 xx.py
bash: /tmp/foo dir/.myenv/bin/pdoc3: "/tmp/foo: bad interpreter: No such file or directory
```
If I am using a global pip installation of pdoc3, it does indeed work.

**Comment by kernc** [comment]
I don't think this is a pdoc issue.

https://stackoverflow.com/questions/15472430/using-virtualenv-with-spaces-in-a-path
https://stackoverflow.com/questions/10873440/trouble-with-pip-and-virtualenv/10873611#10873611

Maybe try to upgrade packages pip and virtualenv to most recent versions?

**Comment by smonsays** [comment]
`pip3` is working fine for me from inside the virtual environment with spaces. In contrast to `pdoc3`, it starts the .myenv/bin/pip3 with:
```
#!/bin/sh
'''exec' "/path/to the/env/.myenv/bin/python" "$0" "$@"
' '''
```
If I replace the first line in .myenv/bin/pdoc3 with this one, I can use pdoc3 from within the virtual environment even though the path contains spaces. Are there any downsides to this? Otherwise this might be an easy change in the repo.

**Comment by kernc** [comment]
What's the line in .myenv/bin/pdoc3? The thing is, the line is not created by pdoc, but by pip/setuptools (and friends) from this:
https://github.com/pdoc3/pdoc/blob/0b1561b47de4c91193fe10bda0ecb6f0f9e60e01/setup.py#L38-L43

If there is something we should do on this end, I certainly don't know about it.

**Comment by kernc** [comment]
> I think the difference might be that I am calling pdoc3 from inside a virtual environment. For me the following fails:

Your spaced path example works over here. Shebang lines are the same as in your example. :confused:

**Comment by smonsays** [comment]
> What's the line in _.myenv/bin/pdoc3_?

It was simply `#!//tmp/foo dir/.myenv/bin/python`

> Do other, installed executables work?

Quite a few python packages have been updated recently (due to the release of python 3.8 on Arch Linux) and now pdoc3 has the correct header by default too. So this issue resolved itself for me now. Thank you for your patience!
