### ISSUE TITLE
params and return are not separated from docstring

### ISSUE THREAD

**Issue by cristianmtr** [pdoc3/pdoc#129]
### Expected Behavior

`param` and `return` entries in docstring should be separated from the main description of a function, perhaps on in a list, like so:

- param1
- param2
- returns

### Actual Behavior

They are in-line with the rest of the docstring: 
![param](https://user-images.githubusercontent.com/8330330/69332011-1824b100-0c56-11ea-81ab-55c34a172064.png)

### Steps to Reproduce

1. Have docstring with params and return
2. Build markdown with `pdoc --pdf --template-dir=docs/templates -c show_inherited_members=False`

See templates below:

[templates.zip](https://github.com/pdoc3/pdoc/files/3874302/templates.zip)

### Additional info

- pdoc version: pdoc3 0.7.2

**Comment by kernc** [comment]
You are using RestructuredText docstring notation (`:param df: the dataframe`) which pdoc doesn't support. If you instead use Numpydoc or Google-style docstrings, the params should render better as well as be more user-friendly to read in plain text.
See https://pdoc3.github.io/pdoc/doc/pdoc/#supported-docstring-formats.
