### ISSUE TITLE
str Annotations rendered with trailing single quote

### ISSUE THREAD

**Issue by Sieboldianus** [pdoc3/pdoc#130]
I just discovered that I can enable showing type annotations in my docs with `--config show_type_annotations=True` flag. This is awesome!
However, for some reason `str` type hints show a trailing single quote `'`:

### Expected Behavior

Example Code:
```python
@TMDec.prepare_clustering_check
def get_selection_map(self, cls_type: str, item):
    """Return plt.figure for item selection."""
    fig = self.clusterer[cls_type].get_sel_preview(item)
    return fig
```

Should render as:
```output
def get_selection_map(self, cls_type: str, item)
```

### Actual Behavior

It is rendered as:
```output
def get_selection_map(self, cls_type: str', item)
```
Picture:
![pdoc_str](https://user-images.githubusercontent.com/13646666/69625000-fe181380-1045-11ea-8115-bd8ecdde408d.png)

All type hints for type `str` show the same behaviour. There're other instances where this happens, but I couldn't find a pattern:

e.g. example for Iterable, Custom type, and Optional:
```
def check_fileheader
(fieldnames: Iterable[str]', source_map: ConfigMap', filename: Optional[str]')
```

### Steps to Reproduce

This is the full command I am using:
```bash
pdoc --config show_type_annotations=True --template-dir docs/apidoc/ --html --output-dir docs/api/ mypackage
```

### Additional info

- pdoc version: 0.72

**Comment by kernc** [comment]
I can't immediately reproduce it on pdoc docs:
```bash
pdoc --html -c show_type_annotations=True pdoc
```
and neither in tests:
```py
def bug130(cls_type: str):
    pass

params = pdoc.Function('bug130', mod, bug130).params(annotate=True)
```
Help in debugging this would be appreciated.

**Comment by Sieboldianus** [comment]
Ok, started debugging this, here's some base info to start locating the issue:

The issue appears in all of these 3 setups:

Setup 1:
- Gitlab CI (Miniconda Docker) and newest package dependencies

Setup 2:
- Windows Subsystem for Linux (Ubuntu 18.04) with Miniconda environment isolated
- Python 3.8

Setup 3:
- Windows 10 Miniconda, separate environment (Python 3.8)

What I discovered is that the single quote is only renedered in the browser, I can't find it in the static html:

```html
    @TMDec.init_data_check
    def add_record(self, record: PostStructure):
        &#34;&#34;&#34;Adds record to input data

        Args:
            record (PostStructure):
            A record with latitude/ longitude
            coordinates and tags/ terms attached.
            This structure provides a wide array of
            input attributes that will be filtered/
            reduced to CleanedPost structure for
            TagMaps clustering
        &#34;&#34;&#34;
        self.lbsn_data.add_record(record)

Do you have any suggestion where to look for the issue?
```

**Comment by Qu4tro** [comment]
I can't reproduce this either on `pdoc3-0.7.2 - Python 3.8`

**Comment by Sieboldianus** [comment]
Thanks for testing! It could likely be an issue of pdoc3 installed with pip using conda. I will test if it works with plain pip for me and report back.

**Comment by Sieboldianus** [comment]
Ok, I tested and it is not an issue with conda. Here's my setup in ubuntu 18.04 (Windows 10 Subsystem for Linux):

* `git clone https://github.com/Sieboldianus/TagMaps.git`
* `cd tagmaps`
* `sudo apt-get install python3-venv`  
* `python3 -m venv tagmaps`  
* `source ./tagmaps/bin/activate`
* `sudo apt-get install libgdal-dev`
* `export CPLUS_INCLUDE_PATH=/usr/include/gdal`
* `export C_INCLUDE_PATH=/usr/include/gdal`
* `gdal-config --version` Output: 2.2.3
* `pip install GDAL==2.2.3`
* Install tagmaps in venv: `pip install .`
* `pip install pdoc3`
* run pdoc: `pdoc --config show_type_annotations=True --template-dir docs/apidoc/ --http : tagmaps`

Same issue:
* Open [http://localhost:8080/tagmaps/tagmaps_.html#tagmaps.tagmaps_.TagMaps.cluster_tags](http://localhost:8080/tagmaps/tagmaps_.html#tagmaps.tagmaps_.TagMaps.cluster_tags)

![tm](https://user-images.githubusercontent.com/13646666/71882674-3591d980-3135-11ea-9c1a-bc6026b6c954.png)

**Comment by Qu4tro** [comment]
Just to let you know, that I managed to reproduce the issue. Will try to add in more information about this, later today.

**Comment by Qu4tro** [comment]
Ok, so the issue lies here:
https://github.com/pdoc3/pdoc/blob/master/pdoc/__init__.py#L1165

It goes a bit like this:
```
>>> re.sub(r'(?<=: )[\'"]|[\'"](?= = )', '', "cls_type: 'str'", 2)
"cls_type: str'"
```

The underlying issue is that the second single quote does not match and therefore is not replaced by `''`.
A bit tired so for now I'll just leave this here, if anyone wants to give a shot at correcting the expression:
https://regex101.com/r/XmPH1z/1

**Comment by kernc** [comment]
Thank you both!

**Comment by Qu4tro** [comment]
Amazing :raised_hands:

**Comment by Sieboldianus** [comment]
Thanks so much to you both! I would have had a hard time finding this..
