### ISSUE TITLE
C extension is not documented as submodule

### ISSUE THREAD

**Issue by szsdk** [pdoc3/pdoc#132]
I used pdoc to document a python libray with some c extension. The structure looks like this.
- pylib
  - `__init__.py`
  - testing
    - `__init__.py`
    - `cpplib.so`

### Expected Behavior
After running `pdoc --html pylib`, I expected `cpplib`'s document would be shown in the submodule section of testing.

### Actual Behavior
It seems that `pdoc` tried to parse the `cpplib.so` file because I got a warning says
```
UserWarning: Couldn't get/parse source of
```
But finally in generated html files, there is nothing about `cpplib`.
However, if I use
```
pdoc --html pylib.testing.cpplib
```
Document page can be generated as expected.

### Additional info

- pdoc version: 0.7.1

**Comment by kernc** [comment]
I'm really sorry for the late reply, but could you maybe provide a minimal example (i.e. code and compile instructions for cpplib.so) which I can use to reproduce the issue?

On a quick glance, is it possible that this bit is hit?
https://github.com/pdoc3/pdoc/blob/b2878214f272d3cd541ca436ae587ba8b98624cd/pdoc/__init__.py#L596-L599

When you say:

> However, if I use `pdoc --html pylib.testing.cpplib`, document page can be generated as expected.

Do you mean that the document page also contains documented module members (such that would violate aforementioned `Couldn't get/parse source` warning)?

**Comment by szsdk** [comment]
> I'm really sorry for the late reply, but could you maybe provide a minimal example (i.e. code and compile instructions for cpplib.so) which I can use to reproduce the issue?

Sure. You could run the `runme.sh` in [pdoc_pylib.zip](https://github.com/pdoc3/pdoc/files/4048840/pdoc_pylib.zip) to produce what I am talking about. [Pybind11](https://pybind11.readthedocs.io/en/stable/) is used. So you may need to install it first by pip.

>   Do you mean that the document page also contains documented module members (such that would violate aforementioned `Couldn't get/parse source` warning)?

Yes. I saw the warning and the generated html file.

**Comment by kernc** [comment]
Thanks, this was really helpful! The issue was that we only ever considered iterating over files with `importlib.machinery.SOURCE_SUFFIXES`, which compiled/bytecode modules obviously didn't match. :sweat_smile:
