### ISSUE TITLE
pdoc executes documented modules

### ISSUE THREAD

**Issue by RicardoALFCG** [pdoc3/pdoc#138]
Hello,

I have a simple Flask module(server.py) which I want to create html docs for it.

### Expected Behavior
When executing `pdoc3 --html server.py` i am only expecting the creation of a folder with the html documentation.

### Actual Behavior
When executing `pdoc3 --html server.py` I am creating a folder with the html docs, but pdoc3 somehow also runs the script. In this way, I am forced to quit the script manually. However, the docs are created with no problems. 

### Steps to Reproduce
1. Create some python script with some prints (For example: example.py).
2. Run `pydoc3 --html example.py`
3. Observe the documentation being created and also the prints of the example.py script printed. Which means the script is being executed.

### Additional info
This issue is not problematic if my module only prints stuff. But since I am creating docs for a flask app, when I run the flask module, I am only able to quit the module manually or by accessing a specific API route.

- pdoc3 version: 0.7.2 ( I have installed it via `pip install pdoc3`)
- Python version: 3.7.4

Thank you for the future support and congratulation for the light and efficient tool you have created.

Regards, 
Ricardo

**Comment by kernc** [comment]
[pdoc executes documented modules](https://pdoc3.github.io/pdoc/doc/pdoc/#fn:execution) and there's no simple way around it.

Curious, is your server execution logic safely nested behind a `if __name__ == '__main__'` guard?

**Comment by inktrap** [comment]
As a consequence of this you can't keep your argument setup in a separate file/module. You would have to import it and that would either execute the code and your script would need the arguments (which is what you want, the if part of the ifmain-guard), or it wouldn't (else part of the ifmain-guard). However if it is executed on import that is true for pdoc's imports as well, which doesn't work with pdoc's arguments. Sigh.

**Comment by kernc** [comment]
> you can't keep your argument setup in a separate file/module

Can you show a brief example on what you mean by argument setup? The `argparse` argument parser only considers arguments [upon executing `parser.parse_args()`](https://docs.python.org/3/library/argparse.html#example) ... :thinking:

**Comment by inktrap** [comment]
Let's have this project:
```
main.py
lib/cli.py
```

This is the ``main.py`` file:

```
#!/usr/bin/env python3.9
'''
 .. py:module:: main
'''

import sys
import os
from lib import cli


def some_helper(help_text: str):
    """
    Print help: a rendundant helper function

    :param help_text: The help text to print
    :return: None
    """
    print(help_text)
    return None


def main(args=None):
    print("hello, world")
    print(args)


if __name__ == "__main__":
    args = cli.args
    main()
else:
    main()
```


This is ``lib/cli.py``:

```
#!/usr/bin/env python3.9
import argparse

if __name__ == "__main__":
    pass
else:
    parser = argparse.ArgumentParser()
    parser.add_argument("--foo", help="foo help")
    args = parser.parse_args()
```

Now if I call pdoc it overwrites the options and I can pass it ``--foo``.

Thats why I wrote that the argument parsing has to happen in ``./main.py``.

pdoc executing modules is not surprising, sphinx with its autoapi-extension (https://autoapi.readthedocs.io/) does the same …

**Comment by inktrap** [comment]
Well … it is not surprising that the code above doesn't work … I want to create the arguments when the file is imported in order to separate that from main.py. However if the arguments are built when the file is imported, then this happens too when it is imported by pdoc or autoapi … and you can't pass parameters to imports.

**Comment by kernc** [comment]
Why not:
```py
# lib/cli.py:
import argparse

parser = argparse.ArgumentParser()
parser.add_argument(...)
```

```py
# main.py:
from lib.cli import parser

def main():
    args = parser.parse_args()
    ...

if __name__ == '__main__':
    main()
```

Where else do you need `args` other than in your `main()`?

**Comment by inktrap** [comment]
On larger applications I prefer to write an args module that has different submodules, e.g. for a web application, the cli application aso. and then i have to use values from these argumens in other modules (e.g. -t N --threads N where N is the number of threads that I want my threadpool to have). Anyways, I guess I am trying sphinx with autodoc.

**Comment by prabu28** [comment]
@inktrap are u able to fix the above explained issue or you moved away from pdoc ?

**Comment by inktrap** [comment]
I moved away from it … I would use swagger through fastapi or starlight/starlette now.
