### ISSUE TITLE
BUG: `Args` section issue when variable name is single upper case character

### ISSUE THREAD

**Issue by wq2012** [pdoc3/pdoc#14]
### Expected Behavior

I have this docstring:
```python
def compute_intersection_length(A, B):
    """Compute the intersection length of two tuples.
    Args:
        A: a (speaker, start, end) tuple of type (string, float, float)
        B: a (speaker, start, end) tuple of type (string, float, float)
    Returns:
        a float number of the intersection between `A` and `B`
    """
```

I expect the generated docs separate A and B in different paragraphs.

### Actual Behavior

This is what has been generated:
![screenshot from 2019-01-28 11-00-05](https://user-images.githubusercontent.com/3002724/51848611-e66be380-22eb-11e9-8863-9b8fc94390db.png)

Not sure if this is a bug or intentional...

### Steps to Reproduce

N/A

### Additional info

- pdoc version:
master of this repo

**Comment by kernc** [comment]
Certainly wasn't intentional. The regex was made to recognize beginnings of sections by a preceding empty line. I guess that limitation was superfluous. Hope this doesn't creep in too many false positives ...

**Comment by kernc** [comment]
Thanks!
