### ISSUE TITLE
Add Flag to Document Non-private Imported Members

### ISSUE THREAD

**Issue by ahangsleben** [pdoc3/pdoc#142]
### Expected Behavior
Document locally imported private members if they are imported in a non-private form. This would allow vanity imports from `_file.py`s to be documented. 

### Actual Behavior
Private imported members are not documented

### Steps to Reproduce
Structure:
```
mypackage/
|- __init__.py
|- _myclass.py
```

Code:
`mypackage/__init__.py`:
```python
from ._myclass import MyClass
```
`mypackage/_myclass.py`:
```python
class MyClass():
    """Here is some documentation!"""
```

Expected documentation output:
```
Module mypackage

Classes
class MyClass ()
    Here is some documentation!
```

### Additional info

- pdoc version: 0.7.2

**Comment by kernc** [comment]
I don't like too many feature flags. I think this is best resolved by way of [whitelisting with `__pdoc__` dict](https://github.com/pdoc3/pdoc/issues/90). Unless disagreed, continue in https://github.com/pdoc3/pdoc/issues/90.
