### ISSUE TITLE
Links to references in type strings don't work for complex types.

### ISSUE THREAD

**Issue by knarfS** [pdoc3/pdoc#145]
### Expected Behavior

Pdoc3 should add links to known references (here `MyClass`) for complex types like `Set[MyClass]` or `Dict[int, MyClass]`

### Actual Behavior

Pdoc3 only adds reference in complex types when there are additional white spaces. `Set[ MyClass ]` or `Dict[ int, MyClass ]`is working.

### Additional info

In `html_helpers.py` function `to_markdown()` links between square brackets are excluded (is there a reason for this?):
```python
# Matches markdown code spans not +directly+ within links.
# E.g. `code` and [foo is `bar`]() but not [`code`](...)
# Also skips \-escaped grave quotes.
_code_refs=re.compile(r'(?<![\[\\`])`(?!])(?:[^`]|(?<=\\)`)+`').sub
```
This regular expression is working for me, but it is probably not valid for other cases:
```python
r'(?<![\\`])`(?!])(?:[^`]|(?<=\\)`)+`'
```

- pdoc version: git commit 196c93b

**Comment by kernc** [comment]
References between square brackets are excluded as mentioned in the comment, because they would override what are already markdown hyperlinks:
```markdown
[`ref`](url)   # We don't want ref to overrule url
```

I think the regex might be missing an additional lookahead check for the opening URL-containing parenthesis ... :thinking:

Do the tests by chance pass with your modification?
```bash
python -m pdoc.test.__init__
```

**Comment by knarfS** [comment]
Yes, the modified regular expression passes the unit tests.

**Comment by kernc** [comment]
Sorry, can you give an example docstring? Even with your regex fix, I can't get
```md
`Dict[int, pdoc.Doc]`
```
to link. :flushed:

**Comment by knarfS** [comment]
I've added a PR that may fix this problem.
The new regexpr should be reviewed ;)

**Comment by kernc** [comment]
> This regular expression is working for me, but it is probably not valid for other cases:

Can we first have a docstring example on which your modified expression works and the original doesn't? So that the issue can be easily reproduced.

**Comment by knarfS** [comment]
Test Docstrings:
```
`test`
`test` test `test`
Dict[`test`, `test`]
Tuple[`test`, `test`, `test`]
Tuple[`test`, Dict[`test`, `test`], `test`]
[`test`](URL)
[`test`]: (URL)
```

Everything between back ticks should match, except the last two (markdown links).

**Comment by knarfS** [comment]
Old RegExpr: https://regex101.com/r/TWjTTy/1
New Regexpr: https://regex101.com/r/TWjTTy/2

**Comment by knarfS** [comment]
Slightly modified expression with more test strings. Also one of the markdown link examples had the wrong syntax: https://regex101.com/r/zIfB3k/4

Notes:
1. Not all of them are parsed correctly (Multiple back tick in bracket for markdown link syntax). Maybe a modified reg expr can do the job?
1. I have no idea about the reference-style link definitions.
1. One of the test string can't be distinguished from a markdown link or not (``... [`link text` `itself`] ...``). For this one, a regular expression can't do the job....

Any suggestions to improve the regular expression further? Where to cut corners (e.g. 2. and 3.)?
