### ISSUE TITLE
Return type is displayed as name for google style comments

### ISSUE THREAD

**Issue by knarfS** [pdoc3/pdoc#146]
### Expected Behavior
The `Returns:` section (also `Raises:` and `Yields:`) when using the google syntax has normally no (parameter) name, but only a type (but could also have a name).
The name is displayed in bold and the type is displayed normal.

### Actual Behavior
- When only a type is used, it is interpreted as the name and displayed in bold.
- When a complex type is used (e.g. `Dict[int, MyClass]`) everything is interpreted as the description.

### Steps to Reproduce

This will display the type (`MyClass`) as the name:
```
Returns:
    MyClass: This is a description.
```

This will display everything as the parameter description:
```
Returns:
    Dict[int, MyClass]: This is another description.
```

### Additional info

I couldn't come up with a regular expression to cover all cases, because when you only have the type (common in the `Returns:` section) or only have a name (common in the `Args:` section), you can't tell them apart. The parsing of the google syntax (`google()` in `html_helpers.py`) should probably be more like the parsing of the numpy syntax (`_numpy_sections()` in `html_helpers.py`).

For now I'm using the numpy syntax, which is working as expected ;)

If you want, I can probably come up with something for the unit tests.

- pdoc version: git commit 196c93b

**Comment by kernc** [comment]
> only a type (but could also have a name).

Source? Does Sphinx ([sphinxcontrib-napoleon](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html)) support that?

Probably welcome a PR fix for complex types (`Dict[int, MyClass]`). Although Google pystyle does strongly [encourage type annotated code](http://google.github.io/styleguide/pyguide.html#221-type-annotated-code), which I think makes sense particularly for complex types. Prose documentation does have a tendency to go out of date ...

**Comment by knarfS** [comment]
> > only a type (but could also have a name).
> 
> Source? Does Sphinx ([sphinxcontrib-napoleon](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html)) support that?

Yes, that syntax is all over in the examples you linked. (e.g. function `module_level_function()` in the `Returns:` section and `Raises:` section).
I've added a test to my branch issue_146: https://github.com/knarfS/pdoc/tree/issue_146

> Although Google pystyle does strongly [encourage type annotated code](http://google.github.io/styleguide/pyguide.html#221-type-annotated-code), which I think makes sense particularly for complex types.

I'm using pybind11 and an embedded module, so no source code for pdoc to parse and no type annotations.
But I'm working on a PR to fix that, by extracting the signature from the first line of the docstring.

**Comment by kernc** [comment]
> Yes, that syntax is all over in the examples you linked. (e.g. function module_level_function() in the Returns: section and Raises: section).

I can't see any Returns/Raises/Yields examples containing _names_ of returned values? Types only. :thinking:

> I've added a test to my branch issue_146: https://github.com/knarfS/pdoc/tree/issue_146

So IIUC, the issue is the types are rendered in bold instead of code, correct? :sweat_smile: Fix welcome.

**Comment by knarfS** [comment]
> I can't see any Returns/Raises/Yields examples containing _names_ of returned values? Types only. thinking

Sorry, that was a misunderstanding, was talking about types. There was an example with named return types, but I couldn't find it anymore, so forget about that.

> So IIUC, the issue is the types are rendered in bold instead of code, correct? sweat_smile Fix welcome.

Yes, the rendering is wrong and different for both provided examples.

**Comment by knarfS** [comment]
Found it, but it was in the documentation for the NumPy style (See https://numpydoc.readthedocs.io/en/latest/format.html#sections, 5. and 6.).
Sorry ;)

**Comment by kernc** [comment]
Thanks. So a solution would be to make `google()` more like `_numpy_sections()` and handle sections Returns/Raises/Yields/(...?) differently. PR welcome. :+1: 
https://github.com/pdoc3/pdoc/blob/72bd9821e6a8180230f220a453dd4c0d53832063/pdoc/html_helpers.py#L204-L205
https://github.com/pdoc3/pdoc/blob/72bd9821e6a8180230f220a453dd4c0d53832063/pdoc/html_helpers.py#L152-L175
