### ISSUE TITLE
Cannot pip install pdoc3

### ISSUE THREAD

**Issue by 1081** [pdoc3/pdoc#147]
### Actual Behavior
I get this error message in windows 10 during pip install:

```
File "c:\XXX\venv\lib\site-packages\setuptools\command\easy_install.py", line 673, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools_scm')
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

### Steps to Reproduce

1. cmd: pip install pdoc3
2. --> Error message

### Additional info
- windows 10
- python 3.8.1 and 3.74
- pdoc version: 0.7.2

**Comment by kernc** [comment]
Pdoc3 installation requires [setuptools-scm](https://pypi.org/project/setuptools-scm/) package:
```bash
pip install setuptools_scm
```
Please install this first; or what does it error with?

**Comment by 1081** [comment]
Thank you! I had to install setuptools-scm and setuptools-git first. Are these packages not included in the requirements?

**Comment by kernc** [comment]
Sure they are.
https://github.com/pdoc3/pdoc/blob/72bd9821e6a8180230f220a453dd4c0d53832063/setup.py#L52-L55
For some reason your environment (outdated setuptools or pip?) didn't obtain/pick them up properly. Do explain if you figure it out!

**Comment by kernc** [comment]
Maybe related: https://github.com/pypa/setuptools/issues/1320.
