### ISSUE TITLE
Class variables without explicit docstrings inherit incorrect docstrings

### ISSUE THREAD

**Issue by MrYsLab** [pdoc3/pdoc#151]
### Expected Behavior
Class variables for an inherited class to be printed correctly. 

For example, if the class is defined as:
```
class GatewayBase:
    """
    This class provides a common front end abstraction for all asyncio hardware gateways.
    """
    # pin modes
    DIGITAL_INPUT_MODE = 0
    DIGITAL_OUTPUT_MODE = 1
    PWM_OUTPUT_MODE = 2
    ANALOG_INPUT_MODE = 3
    ANALOG_OUTPUT_MODE = 4
    DIGITAL_INPUT_PULLUP_MODE = 5
    I2C_MODE = 6
    TONE_MODE = 7
    SERVO_MODE = 8
    STEPPER_MODE = 9
    SONAR_MODE = 10
    WILD_CARD_MODE = 11

    # target gpio device types types
    ARDUINO = 0
    RPi = 1
    ESP8266 = 2
    CRICKIT = 3

    # noinspection PyDefaultArgument,PyRedundantParentheses
    def __init__(self, back_plane_ip_address=None, subscriber_port='43125',
                 publisher_port='43124', process_name='',
                 subscriber_list=None, board_type=None, ):
        pass
```
the pdoc3 output should appear similarly.

### Actual Behavior
However, what I see for each class variable is similar to the following screenshot:

![bug](https://user-images.githubusercontent.com/5189838/73122491-969e1780-3f53-11ea-8bed-417a9f6b661e.png)

### Additional info

- pdoc version: 0.7.2 and 0.7.4

**Comment by kernc** [comment]
Looks like a regression since 742c7dd3a75447862029c6f0d303cdd604c9ff15 (https://github.com/pdoc3/pdoc/pull/77, v0.7.0). Maybe docstrings shouldn't be inherited for raw, non-descriptor variables after all. :roll_eyes:

**Comment by MrYsLab** [comment]
Thanks for the quick fix.
