### ISSUE TITLE
Nested `<i>` tags inserted in side-bar wrapping navbar and footer

### ISSUE THREAD

**Issue by MPvHarmelen** [pdoc3/pdoc#161]
### Expected Behavior
I expect the HTML-tree to look like this:

```html
<!doctype html>
<html lang="en">
  <head>...</head>
  <body>
    <main>
      <article id="content">...</article>
      <nav id="sidebar">...</nav>
    </main>
    <footer id="footer">
      <p>Generated by <a href="https://pdoc3.github.io/pdoc"><cite>pdoc</cite> 0.7.5.dev4+g1709915.d20200207</a>.</p>
    </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad()</script>
  </body>
</html>
```

### Actual Behavior
When viewing the file in Firefox, the HTML-tree looks like this, even though the source is as expected:

```html
<!doctype html>
<html lang="en">
  <head>...</head>
  <body>
    <main>
      <article id="content">...</article>
      <i>
        <i>
          <i>
            <nav id="sidebar">...</nav>
          </i>
        </i>
      </i>
    </main>
    <i>
      <i>
        <i>
          <footer id="footer">
            <p>Generated by <a href="https://pdoc3.github.io/pdoc"><cite>pdoc</cite> 0.7.5.dev4+g1709915.d20200207</a>.</p>
          </footer>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
          <script>hljs.initHighlightingOnLoad()</script>
        </i>
      </i>
    </i>
  </body>
</html>
```

Weirdly enough, this only happens on the page for `resolve_coreference`: all other pages are fine.

### Steps to Reproduce

Create `mwe.py` containing:

```python
def mwe():
    """<I>"""
    ...
```

Run `pdoc --html mwe.py` and open `html/mwe.html` in a browser.

Note that the following leads to an empty docstring being shown in the HTML, but no nested `<i>` tags:

```python
def mwe():
    """<broken>"""
    ...
```

~~1. Visit https://mpvharmelen.github.io/coref_draft/resolve_coreference.html to see the navbar be weird and check the source to see the `<i>` tags nested three levels deep.
0. Run `wget https://mpvharmelen.github.io/coref_draft/resolve_coreference.html` to see with your own eyes that the `<i>` tags aren't there in the source HTML.~~ (I updated the documentation to avoid the problem.)

### Additional info

- pdoc version: 0.7.5.dev4+g1709915.d20200207
- firefox 72.0.2. Reproducible in private-mode with all extensions disabled.

**Comment by MPvHarmelen** [comment]
I suspect this has something to do with HTML-escaping. The page mentioned contains documentation strings containing text similar to `<some_stuff>`, which isn't rendered correctly. I'll be onto this later!

**Comment by MPvHarmelen** [comment]
In the PDF the text that looks like `<this>` is also not rendered at all, also probably because it's interpreted as HTML tags.

I can think of several ways of dealing with this problem, depending on whether we want to allow arbitrary HTML in docstrings:

1. (disallow html) Do a full html-escape on all docstrings before feeding them to a markdown engine.
   - This will probably cause lots of problems concerning markdown syntax using `>` for quotes or other characters that will be escaped.
2. (both) Try to carefully find "tags" that aren't closed and html-escape only those.
   - lots of work
   - slow
   - tailored too much to this specific use-case
3. (both) Try to recognise when this happens automatically and make lot's of noise when it does.
4. (both) Ignore it and accept the fact that someone will have the same problem again and hopefully find this thread telling them what is happening.

**Comment by kernc** [comment]
Strongly leaning towards 4. Markdown allows raw HTML by design. While we enable various markdown extensions that should make raw HTML mostly redundant, it's still basic markdown which is the core format we use here (numpydoc and google-style docstrings being translated via markdown).

**Comment by MPvHarmelen** [comment]
Agreed!
