### ISSUE TITLE
Doctest blocks not marked with Python as language and end detection doesn't work

### ISSUE THREAD

**Issue by Marrin** [pdoc3/pdoc#163]
Given this source:

```python
def f():
    """
    Description of `f`.
    
    Example:
        >>> f()
        Traceback (most recent call last):
            ...
        Exception: something went wrong
    """
        raise Exception("something went wrong")
```

### Expected Behavior

A code block covering the whole doctest block and with class "python" so the highlighter doesn't have to guess.  It consistently guesses Haskell by the way.

### Actual Behavior

A code block with class "python" that actually spans the whole doctest block.

### Additional info

Setting the doctest block as fenced code block with an explicit language name solves the highlighting problem, but then the traceback is displayed very weird. That code block then shows up as this in the HTML:

```text
>>> f()
Traceback (most recent call last):
    ...
**`Exception`**
:   something went wrong
```

- pdoc version: 0.7.4

**Comment by kernc** [comment]
> ### Actual Behavior
>
> A code block with class "python" that actually spans the whole doctest block.

This is what I see and consider a problem in `pdoc.html_helpers._ToMarkdown.google()` where `Exception` apparently gets interpreted as a param in Google-style docstring style.
![Screenshot_2020-02-17 test API documentation](https://user-images.githubusercontent.com/684364/74615000-f637af00-511c-11ea-9177-4a1e52102a78.png)
https://github.com/pdoc3/pdoc/blob/725bc1f257e34c952497f2a8541fae2a21dc3773/pdoc/html_helpers.py#L206-L219

If I use fenced code, it works completely as expected. Can you recheck?
```py
def f():
    """
    Description of `f`.

    Example:
    ```py
    >>> f()
    Traceback (most recent call last):
        ...
    Exception: something went wrong
    ```
    """
    raise Exception("something went wrong")
```

>  It consistently guesses Haskell by the way.

The auto-highlighting is up to Highlight.js. With such small examples featuring so little Python syntax it's unreasonable to expect more.
