### ISSUE TITLE
Submodules are not ignored even when excluded from __all__

### ISSUE THREAD

**Issue by Askannz** [pdoc3/pdoc#165]
According to the [doc](https://pdoc3.github.io/pdoc/doc/pdoc/),

> In addition, if a module defines `__all__`, then only the identifiers contained in this list will be considered public.

However, this does not seem to apply to submodules. Pdoc includes them in the generated doc regardless.

### Steps to Reproduce

```
mymodule
    __init__.py
    submodule.py
```
* `__init__.py` :
    ```python
    from .submodule import foo
    __all__ = ["foo"]
    ```
* `submodule.py` :
    ```python
    def foo():
        print("Pouet pouet") 
    ```

#### Result:
![pdoc3](https://user-images.githubusercontent.com/9202863/74704474-a82dc300-5264-11ea-9656-645f096ce52c.png)

`foo()` is documented as the top-module level, as expected since we put it in `__all__`. However `mymodule.submodule` is also documented, even though it was not specified in `__all__`.

### Additional info

- pdoc version: `pdoc3-0.7.4`

**Comment by kernc** [comment]
The [semantics of `__all__`](https://docs.python.org/3/tutorial/modules.html#importing-from-a-package) don't say anything about submodules; `__all__` is about per-module members only. This is defined by Python, and pdoc would not override it.

If you wish to exclude certain modules from being documented, you can:
* rename to modules to start with an underscore, such as is common for private API identifiers,
* list the modules in [`__pdoc__` dict](https://pdoc3.github.io/pdoc/doc/pdoc/#overriding-docstrings-with-__pdoc__), which should work for modules as well.

**Comment by Askannz** [comment]
Thanks for clarifying. I have a (relatively) large number of submodules to exclude in my current project, so putting them all in `__pdoc__` feels kinda clunky. Ignore by default + whitelisting would be a nice feature to have :wink:

**Comment by kernc** [comment]
Feel yourself encouraged to open a new issue for the feature request.

I otherwise agree, manually tracking lists of things is cumbersome and tends to go out of date. For the time being, private modules by way of naming [aren't](https://github.com/python/cpython/tree/master/Lib) [really](https://github.com/numpy/numpy/tree/master/numpy) [that](https://github.com/pandas-dev/pandas/tree/master/pandas) [uncommon](https://github.com/pallets/click/tree/master/click).
