### ISSUE TITLE
Some decorated functions are ignored by pdoc3

### ISSUE THREAD

**Issue by inhumantsar** [pdoc3/pdoc#166]
I'm not sure if this is a Click issue or a pdoc3 issue. It came up when running pdoc3 against our CLI project using [Click 7](https://click.palletsprojects.com/en/7.x/). Figured I'd report the issue to both projects just in case.

### Expected Behavior

Assuming we have a python package with one module containing the code below:

```python
import click

def testdeco(func):
    def wrapper(x):
        print('in deco')
        func(x)
    return wrapper

@click.command()
@click.option('-s', '--some-arg', 'somearg')
def somefunc(somearg):
    """some func docstring"""
    print('foo')

@testdeco
def decofunc(n):
    print(n)

def otherfunc():
    """other func docstring"""
    print('bar')

```

I'd expect pdoc3 to generate relevant docs for `somefunc()`

### Actual Behavior

![image](https://user-images.githubusercontent.com/494253/74775487-72d0a780-525b-11ea-84b6-9a00fd634431.png)

### Additional info

```
Click==7.0
Mako==1.1.1
Markdown==3.2.1
MarkupSafe==1.1.1
pdoc3==0.7.4
```

**Comment by kernc** [comment]
Clearly, `_is_function()` fails to return True for whatever objects `click.commands` are.
https://github.com/pdoc3/pdoc/blob/725bc1f257e34c952497f2a8541fae2a21dc3773/pdoc/__init__.py#L290-L291

**Comment by kernc** [comment]
Scratch that. In all likelihood we're missing a second `unwrap()` call here:
https://github.com/pdoc3/pdoc/blob/725bc1f257e34c952497f2a8541fae2a21dc3773/pdoc/__init__.py#L559-L562
`click.decorators.command.<locals>.decorator` will never be from our module. Can you confirm?

**Comment by inhumantsar** [comment]
> `click.decorators.command.<locals>.decorator` will never be from our module. Can you confirm?

i'm sorry? if you mean a situation like the reproduction above, no. that module would never call `decorator` directly.

**Comment by kernc** [comment]
I meant `is_from_this_module(obj)` won't be true for `obj` (which in your case _is_ `click.decorators.command.<locals>.decorator` object) unless `inspect.unwrap(obj)` was called on it beforehand.

----------

But I'm afraid the proposed solution won't work as click's decorators don't set `__wrapped__` (as is customary for decorators) via [`functools.update_wrapper()`](https://docs.python.org/3/library/functools.html#functools.update_wrapper) nor via [`functools.wraps()`](https://docs.python.org/3/library/functools.html#functools.wraps).
Instead they only set `__doc__` manually:
https://github.com/pallets/click/blob/56314dbdc6075307d2104b2ae640186acb81a8ef/click/decorators.py#L116
See relevant:
https://github.com/pallets/click/issues/127
https://github.com/pallets/click/pull/234
If they decide to add `__wrapped__` as well, this will become a pdoc3 bug. :smile_cat:

**Comment by kernc** [comment]
> unless `inspect.unwrap(obj)` was called on it beforehand.

In fact, it appears well-defined decorators [should set `__module__`](https://docs.python.org/3/library/functools.html#functools.update_wrapper) as well, so an additional `inspect.unwrap()` call is unnecessary.

This is not our bug.

A workaround is to declare `__all__`.
