### ISSUE TITLE
Set markdown format via __docformat__ or command line --docformat

### ISSUE THREAD

**Issue by peterjc** [pdoc3/pdoc#169]
I note that pdoc3 supports pure Markdown (with extensions), numpydoc, and Google-style docstrings formats, and you have partial reStructuredText support (see #110).

I do not see that you allow explicit declaration of which markup language (or flavour) is being used, although I see internally variable ``docformat`` can be ``"numpy"`` or ``"google"``.

I would like to be able to set a default at the command line with ``--docformat ...`` and/or override this at individual file level using``__docformat__ = "..."``  as done in epydoc. See also rejected PEP258:
 
https://www.python.org/dev/peps/pep-0258/#choice-of-docstring-format
http://epydoc.sourceforge.net/manual-usage.html

Cross reference https://github.com/mitmproxy/pdoc/issues/153 on the original pdoc project, and #158 on enabling markdown extensions.

**Comment by kernc** [comment]
Happy to change default param value to `docformat=None` and infer either supported format ('numpy' or 'google') from `module.obj.__docformat__`.
https://github.com/pdoc3/pdoc/blob/b8758dd520a20bc5f77387761fd181990242e6e8/pdoc/html_helpers.py#L378-L379
Shouldn't be hard at all. PR welcome.

**Comment by peterjc** [comment]
Personally I want to use ``--docformat restructuredtext`` at the command line (RST spelt out in full to match the convention established by epydoc).

**Comment by kernc** [comment]
This should now work.

To set it from the command line, one can use: `pdoc --config='docformat="numpy"' ...`

Whether to support reStructuredText, and how, is a different issue (https://github.com/pdoc3/pdoc/issues/110).
