### ISSUE TITLE
Modules not found with empty __init__.py

### ISSUE THREAD

**Issue by DaniGuardiola** [pdoc3/pdoc#170]
pdoc version: 0.7.4

I'm trying to serve the documentation of my project and I have a structure similar to this:

```
some_package/
  __init__.py
  a.py
  b.py
```

In the `__init__.py` file, I don't want to use `__all__` because it messes with the imports, so the content is just a docstring, like so:

```python
"""
Some description of the package.
"""

```

I then serve the documentation like this:

```
pdoc --http :8000 some_package
```

When I go to `localhost:8000`, I get the list of packages, with just the one `some_package`.

If I go into the package's page (`localhost:8000/some_package`) I get a `Module some_package not found.` message. However, if I go to a module's page, like `localhost:8000/some_package/a`, I get the module's documentation without an issue.

I would expect the package's page to display a list of modules.

I don't know if I'm doing something wrong or if this is some kind of bug. I've looked around and I couldn't find anything to help me on this issue.

Could someone please give me a hint? Thank you in advance :)

**Comment by kernc** [comment]
Following the steps laid out, trying with both 0.7.4 and master, I'm happy to report I **can't** reproduce the issue. :grin: 

```text
$ pdoc --http :8000 test_mod

Starting pdoc server on localhost:8000
pdoc server ready at http://localhost:8000
127.0.0.1 - - [27/Feb/2020 14:39:14] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Feb/2020 14:39:16] "GET /test_mod HTTP/1.1" 302 -
127.0.0.1 - - [27/Feb/2020 14:39:16] "GET /test_mod/ HTTP/1.1" 200 -
127.0.0.1 - - [27/Feb/2020 14:39:19] "GET /test_mod/a.html HTTP/1.1" 200 -
```

Is this, by chance, on Windos?

Here is the error you're seeing:
https://github.com/pdoc3/pdoc/blob/725bc1f257e34c952497f2a8541fae2a21dc3773/pdoc/cli.py#L225-L229
Obviously something failing in:
https://github.com/pdoc3/pdoc/blob/725bc1f257e34c952497f2a8541fae2a21dc3773/pdoc/cli.py#L244-L253

Welcome any helpful investigation you can do.


> I don't want to use `__all__` because it messes with the imports

You mean it messes pdoc or in general? `__all__` is _supposed to_ mess with non-explicit imports. But I don't particularly like it either.

**Comment by DaniGuardiola** [comment]
Hmm, thanks. I'm gonna try to dig into the pdoc source and see what's going on, because I might be wrong about the source of the issue.

> You mean it messes pdoc or in general?

In general. What do you mean with non-explicit imports?

I dislike `__all__` because if you have a `from a.b.c import Whatever` and in the `__init__.py` of `a` you have and `__all__` with some other member (for example `a.d`) it will get imported too, just to be able to add it to the `__all__` iterable. I haven't really dug into the behavior of imports that much but I found not using `__all__` was the easiest solution to my troubles in that sense.

**Comment by kernc** [comment]
-----
`from a.b.c import Whatever` doesn't import `a.d` into the same place (here) where `Whatever` is! It just imports `a` and by that makes its objects (i.e. `a.d`) available. That should be whether you define `__all__` or not.

**Comment by DaniGuardiola** [comment]
Ok, I got it. The problem was that a submodule had an broken import. I guess that the try/catch was originally used for the error that arises when the module/package you're trying to access directly is not found, but it turns out that the error also fires in this case as well.

I think the error should be a bit more descriptive. Something like "Module X couldn't be loaded because submodule X.a.b.c doesn't exist". Maybe distinguish between the two cases. I was able to fix my code to work with pdoc just by adding a `print_exc()` in the `except ImportError` block.

**Comment by DaniGuardiola** [comment]
In regards to the `__all__` topic, I actually investigated it in a kinda hacky way by replacing the builtin `__import__` function to add logs, and found out that importing directly (with no `__all__` shortcuts) did still execute `__import__` for other members listed in the `__all__`, even if they're not being available in your context. That behavior went away after I removed all instances of `__all__`.
