### ISSUE TITLE
Unable to disable sorting of Classes

### ISSUE THREAD

**Issue by kpchand** [pdoc3/pdoc#177]
### Expected Behavior
I have a base class and a bunch of classes which inherit from it. The doc generated strictly sorts using alphabetic order which makes the docs confusing as the base class is listed way below.

![image](https://user-images.githubusercontent.com/1081675/78510074-4a235380-77b0-11ea-8be6-3d990a9c5bea.png)

### Actual Behavior

It should sort as per definition order in module.

### Additional info

When the default didn't work, I tried to override the `sort_identifiers` option in the template but it still didn't work. If this feature exists, I can't find any documentation about using it.

In _html.mako_ file, I changed:

```
<%def name="show_module(module)">
  <%
  variables = module.variables(sort=sort_identifiers)
  classes = module.classes()  # Removed sort=sort_identifiers
  functions = module.functions(sort=sort_identifiers)
  submodules = module.submodules()
  %>
```

Then ran pdoc as:
` pdoc --html --force --template-dir=templates .\fireservice\fields.py`
But this didn't had any effect.

- pdoc version: pdoc.exe 0.7.5

**Comment by kernc** [comment]
> Then ran pdoc as:
> ` pdoc --html --force --template-dir=templates .\fireservice\fields.py`
> But this didn't had any effect.

Assuming templates dir contains the modified html.mako, that's exactly how it's supposed to work. The alternative would be to override _config.mako_ with something like:
```
<%!
sort_identifiers = False
%>
```
or to include the changed property on the command line directly (see `--config`):
```
pdoc3 --html -f -c sort_identifiers=False path/module
```

**Comment by kpchand** [comment]
> Assuming templates dir contains the modified html.mako, that's exactly how it's supposed to work. Can you confirm?

I can confirm that templates reside in the current dir and it contains the modified template file.

> ```
> pdoc3 --html -f -c sort_identifiers=False path/module
> ```

This worked for me!


This work

**Comment by kernc** [comment]
> ```py
>   classes = module.classes()  # Removed sort=sort_identifiers
> ```

Assuming the feature works as intended, the only other explanation can be that the application was incorrect. In fact, sorting identifiers is true by default. :smile: 
https://github.com/pdoc3/pdoc/blob/b8758dd520a20bc5f77387761fd181990242e6e8/pdoc/__init__.py#L782
Case closed. Thanks!

**Comment by veenstrajelmer** [comment]
The sort_identifiers option works great for html, but this seems not to be working when you use -pdf at output format (to an md file). Should this be a separate issue or not?

**Comment by kernc** [comment]
> Should this be a separate issue or not?

@veenstrajelmer Ideally a pull request! Use of `sort_identifiers` is indeed inconsistent in [pdf.mako](https://github.com/pdoc3/pdoc/blob/master/pdoc/templates/pdf.mako).

**Comment by veenstrajelmer** [comment]
I've been looking into pdf.mako and html.mako and see some differences. Unfortunately, I am not sure where the behaviour is different. Therefore I am not sure where/how to make this pull request, could you maybe arrange it or tell me where to do it?

**Comment by veenstrajelmer** [comment]
@kernc: Thanks for fixing this, works like a charm!
