### ISSUE TITLE
Documentation for C Extensions

### ISSUE THREAD

**Issue by rkaminsk** [pdoc3/pdoc#18]
I was trying to use pdoc to create the documentation of a C extensions. The generated documentation does not include the documentation for class methods.

You can see this for example when generating the documentation for python's `parser` module, which is a C extension.
```
pdoc --html parser
```
The class methods of ST class are missing. With pydoc, they are included.

- pdoc version: 0.5.1

**Comment by kernc** [comment]
Thank you. Will be released in 0.5.2 in a few days.
