### ISSUE TITLE
pdoc stops with setup.py

### ISSUE THREAD

**Issue by deterralba** [pdoc3/pdoc#180]
I cannot explain why this happens, but when I run `pdoc vision --html --force` with a subfolder
```
vision/
    __init__.py
    setup.py
    cli/...
```
and in the setup.py fle
```python
from setuptools import setup
setup(
    name='vision-cli',
    version='0.1',
    py_modules=['cli.main'],
    install_requires=['Click'],
    entry_points={
        'console_scripts': ['vision=vision.cli.main:cli'],
    },
)
```
the pdoc command stops and prints in the shell
```
usage: pdoc [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: pdoc --help [cmd1 cmd2 ...]
   or: pdoc --help-commands
   or: pdoc cmd --help
```
without other explanation nor stack trace nor output.

To fix this, I had to patch my setup.py file:
```
from setuptools import setup
import sys

is_pdoc = any('pdoc' in arg for arg in sys.argv)
if not is_pdoc:
    setup(
        name='vision-cli',
        version='0.1',
        py_modules=['cli.main'],
        install_requires=['Click'],
        entry_points={
            'console_scripts': ['vision=vision.cli.main:cli'],
        },
    )
```

And now it works. hopefully it will help someone some day.

**Comment by kernc** [comment]
Or the more agnostic [main guard](https://stackoverflow.com/a/19578335/1090455) [idiom](https://docs.python.org/3/library/__main__.html):
```py
from setuptools import setup
import sys


if __name__ == '__main__':
    setup(...)
```
This will make setup procedure work (as in `pip install .` or `python setup.py install` or similar), but also make the module importable like you've discovered.

Additionally, it's a common convention for Python packages to maintain source files in a top-level directory of the package/library name, and to keep setup.py outside, e.g.
```
vision-dir-on-disk
├── README.txt
├── setup.py
└── vision
    ├── cli
    │   ├── __init__.py
    │   └── x.py
    └── __init__.py
```

**Comment by deterralba** [comment]
Thank you for your answer. Indeed, using `if __name__ == '__main__':` is not often discussed for `setup.py` file, but it's perfectly fine according to you - and the [python mailing list](https://mail.python.org/pipermail/distutils-sig/2014-April/024118.html) :)
