### ISSUE TITLE
Display of search results overlaps with the scrollbar of the side navigation

### ISSUE THREAD

**Issue by kai687** [pdoc3/pdoc#182]
### Expected Behavior

The search results are displayed over the scrollbar. The scrollbar should not overlap.

### Actual Behavior

The scrollbar is visible through the search result display panel which looks funny. See screenshot.

### Steps to Reproduce

1. Go to https://pdoc3.github.io/pdoc/doc/pdoc/
2. Enter a term in the search field, e.g. 'License'
3. Observe the scroll bar being visible through the search results display. (see screenshot)

### Additional info

- pdoc version: it says pdoc 0.8.1 on the website.

![screenshot](https://user-images.githubusercontent.com/17420240/79573322-c37b4a00-80be-11ea-8ef0-a7c6b73ed7bd.png)

**Comment by davfsa** [comment]
Im not able to reproduce this. Generally this should not happen due to how HTML works. Could you tell me what web browser you are using?

**Comment by kai687** [comment]
- problem occurs in Chrome Version 81.0.4044.129 (Official Build) (64-bit)
- problem does **not** occur in Firefox 75.0 (64-bit)

**Comment by davfsa** [comment]
Can reproduce in chrome. This is a bug that should be reported to Chrome, not here, since there is nothing we can do to fix it.

**Comment by kernc** [comment]
Welcome to submit the bug to Chrome. It seems indeed their bug.
