### ISSUE TITLE
Google docstring: Including hyphen in argument type breaks formatting

### ISSUE THREAD

**Issue by polakowo** [pdoc3/pdoc#186]
Including a hyphen in the argument type of a Google-style docstring breaks formatting for that argument.

Consider the following docstring example:

```
        Args:
            x_labels (list of strings): x-axis labels, corresponds to index in pandas.
            trace_names (list of strings): trace names, corresponds to columns in pandas.
            data (any array-like object): data in any format that can be converted to NumPy.
            trace_kwargs (dict or list of dicts): keyword arguments passed to each trace.
            **layout_kwargs: keyword arguments for configuring layout.
        Returns:
            Updatable Plotly widget
```

Here is the screenshot, data argument isn't properly formatted.

![Screen Shot 2020-04-21 at 17 19 09](https://user-images.githubusercontent.com/2664108/79883726-8da6d000-83f4-11ea-87a3-2f75b4931b15.png)

Any way to display hyphens there?

- pdoc version: 0.8.1

**Comment by kernc** [comment]
Apparently the regex matching types doesn't include hyphens.

https://github.com/pdoc3/pdoc/blob/004204320773cb98a8f0cd5fa82e8095f517e488/pdoc/html_helpers.py#L246-L259

Numpy's is less strict.
https://github.com/pdoc3/pdoc/blob/004204320773cb98a8f0cd5fa82e8095f517e488/pdoc/html_helpers.py#L201-L204
