### ISSUE TITLE
Why are PDFs written to standard output 

### ISSUE THREAD

**Issue by arose13** [pdoc3/pdoc#187]
### Expected Behavior
`pdoc --pdf --output-dir docs cool_package`

Since I have to work on a windows computer piping output isn't possible (or at least trivial). Is there any reason why these outputs to console rather than a markdown file?

### Actual Behavior
```
Generated by *pdoc* 0.7.2 (<https://pdoc3.github.io>).

PDF-ready markdown written to standard output.
                              ^^^^^^^^^^^^^^^
Convert this file to PDF using e.g. Pandoc:

    pandoc --metadata=title:"MyProject Documentation"             \
           --toc --toc-depth=4 --from=markdown+abbreviations      \
           --pdf-engine=xelatex --variable=mainfont:"DejaVu Sans" \
           --output=pdf.pdf pdf.md
```

### Steps to Reproduce
NA

### Additional info

- pdoc version: 0.7.2

**Comment by kernc** [comment]
:thinking: No expert on Windows here, but [this support guide from Microsoft](https://support.microsoft.com/en-us/help/110930/redirecting-error-messages-from-command-prompt-stderr-stdout) indicates, quite surprisingly, that standard streams redirection on recent versions of Windos is exactly the same as on other, mature platforms, namely:
```bash
command... > output.txt
```
That doesn't work?

**Comment by arose13** [comment]
Omg! I been years since I've tried that I didn't know it was now possible. Thank you very much!
