### ISSUE TITLE
List generated files on `--html`

### ISSUE THREAD

**Issue by epogrebnyak** [pdoc3/pdoc#189]
Starting to use `pdoc3`, great package, fast access to documentation. 

A suggestion about README.md. The Usage section just mentions the inputs and no outputs:

> Pdoc will accept a Python module file, package directory or an import path.

It would have helped me to learn from usage section that by default pdoc3 will save generated documentation to `html/<package_name>` folder.  A user feels rather confused about not knowing what the program did.

Maybe can also add a message "Saved documentation to <path>" as console ouput.

I can do a PR, if needed.

**Comment by kernc** [comment]
> Maybe can also add a message "Saved documentation to " as console ouput.

Been thinking about this for a long while! A printed list of generated files certainly sounds practical. :+1:

**Comment by kernc** [comment]
Maybe a note on `--output-dir` in [help for `--html`](https://github.com/pdoc3/pdoc/blob/004204320773cb98a8f0cd5fa82e8095f517e488/pdoc/cli.py#L62-L66)? Feel free to revise.

**Comment by epogrebnyak** [comment]
> 
> 
> Maybe a note on `--output-dir` in [help for `--html`](https://github.com/pdoc3/pdoc/blob/004204320773cb98a8f0cd5fa82e8095f517e488/pdoc/cli.py#L62-L66)? Feel free to revise.

That message helps, but I think in the documentation one needs to learn about the behaviour earlier to be able to run the first example quickly and be confident to know where is the output.

**Comment by epogrebnyak** [comment]
> 
> 
> > Maybe can also add a message "Saved documentation to " as console ouput.
> 
> Been thinking about this for a long while! A printed list of generated files certainly sounds practical. 👍

Something in line of below?

```
Generated files:
d:\github\boo\docs\boo\columns.html
d:\github\boo\docs\boo\curl.html
d:\github\boo\docs\boo\errors.html
d:\github\boo\docs\boo\file.html
d:\github\boo\docs\boo\helper.html
d:\github\boo\docs\boo\index.html
d:\github\boo\docs\boo\main.html
d:\github\boo\docs\boo\okved.html
d:\github\boo\docs\boo\path.html
d:\github\boo\docs\boo\whatis.html
d:\github\boo\docs\boo\year.html
```



Would really help a new user! Let me consider how to implement for you with PR (`print()` is the easiest, but not the cleanest)

**Comment by kernc** [comment]
This certainly gives one the ability of quick _review_. :+1: 

And is useful in CLI sense. Look at the surrounding code, I think `print()` is used already. 
Maybe redirect `"Generated files:"` to `sys.stderr` instead of stdout, this will make it universally composable (piped into `xargs`, etc.).

**Comment by epogrebnyak** [comment]
Looks like we can achieve listing of files with a single `print(f)` in `recursive_write_files`, seems a bit too easy.

**Comment by kernc** [comment]
But that seems perfect! :grin:

There is no more elaborate logging currently in place, and printing just filenames can indeed be further used in scripting.

**Comment by epogrebnyak** [comment]
Send a PR with this: 

https://github.com/epogrebnyak/pdoc/blob/1bcde4dfe32f9aea43b2b63928acfb2ebffb3d54/pdoc/cli.py#L319-L325

**Comment by epogrebnyak** [comment]
Couple observations - later in code we use `sys.stdout.write`, which is similar to `print()`:

https://github.com/pdoc3/pdoc/blob/5d15e61f0991233d1ea94759a8070f71771b28f0/pdoc/cli.py#L497-L500

Is there a special reason to use `sys.stdout.write`? Maybe change it to `print()` for consistency?
It took a while for me to htink over why this case is different from print and I could not think of a good answer.

**Comment by kernc** [comment]
`print(..., end='\n')` auto-appends a newline, `file.write()` writes literally.

I had to check myself. :laughing:

**Comment by epogrebnyak** [comment]
Also a more general note - for Github the ideal example is `pdoc --html -o docs mypackage`, which produces documentation ready to be published for Github Pages. I think it is a strong usercase. 

Currently `pdoc --html -o docs mypackage` will create documentation in  `docs/mypackage`, not `docs`. This is a bit surprising, and to move documentation from `docs/mypackage` to `docs`, one needs an extra move command. 

Two ideas:
- change the behavior of `-o` switch (but that breaks your API)
- add `-O` or some other switch that writes exactly to specified `output_directory` directory, not `output_directory/package`

**Comment by epogrebnyak** [comment]
> 
> 
> `print(..., end='\n')` auto-appends a newline, `file.write()` writes literally.
> 
> I had to check myself. 😆

That numbering of newlines looks like serious stuff: `os.linesep * (1 + 2 * int(module != modules[-1]))`  :)

I understand now why you need `write ()`, was not clear from start.

**Comment by kernc** [comment]
> That numbering of newlines looks like serious stuff: `os.linesep * (1 + 2 * int(module != modules[-1]))` :)

Welcome to be as brief more clearly. :stuck_out_tongue:



> Also a more general note - for Github the ideal example is `pdoc --html -o docs mypackage`, which produces documentation ready to be published for Github Pages. I think it is a strong usercase.

Discussed with some ideas and workarounds in https://github.com/pdoc3/pdoc/issues/55.
