### ISSUE TITLE
Linking to internal class breaks for Parameters and Returns

### ISSUE THREAD

**Issue by srgkoshelev** [pdoc3/pdoc#190]
### Expected Behavior
When linking `SomeClass` as a type in Parameters or Returns the link should be produced.

### Actual Behavior
The link is wrapped in `<code> </code>` thus creating a literal string containing `<a title="test.SomeClass" href="#test.SomeClass">SomeClass</a>`.
In the description for parameter the link is ignored and only code environment remains.

### Steps to Reproduce

1. Create a `test/__init__.py` containing:
```
class SomeClass():
    """All roads lead here.
    """
    def __init__(self):
        pass


def random_func(weird_link, no_link):
    """Creates link here: `SomeClass`


    Parameters
    ----------
    weird_link : `SomeClass` instance
        No link in the description: `SomeClass`

    Returns
    -------
    `SomeClass`
        Behaves like description for weird_link
    """
    pass
```
2. `pdoc3 --html test`
3. Open `html/test/index.html`

### Additional info

- pdoc version: 0.7.2

**Comment by kernc** [comment]
> ```
>     weird_link : `SomeClass` instance
> ```

This should be just `param_name: its_type`, i.e. `weird_link: SomeClass`. Then it will link.

>         No link in the description: `SomeClass`

Weird. This should link, I think.

In any event, this has seen some overhaul recently in https://github.com/pdoc3/pdoc/pull/181. Please update to 0.8.x and see how that works for you.

>     Returns
>     -------
>     `SomeClass`

Again, types only; no backticks in structured fields; only in prose.

**Comment by srgkoshelev** [comment]
Awesome, thank you!
