### ISSUE TITLE
Strip docstring from source code examples

### ISSUE THREAD

**Issue by derek-adair** [pdoc3/pdoc#192]
It would be very nice to be able to just look at the source code w/o all the comments.

[Live Example](http://nfldb.derekadair.com/#nfldb.Play)

If you expand play you can see that the documentation text is quite long and does not need to be there.
![image](https://user-images.githubusercontent.com/847236/80844930-21328a80-8bc5-11ea-9615-47a0d5c36e1d.png)

It'd also be cool to remove any other config/text that is predictable.

**Comment by kernc** [comment]
I understand you'd like to collapse the repeated docstring in item's source code view.

Pdoc only outputs raw `<pre><code>`, leaving further markup to [Highlight.js](https://highlightjs.org/).

You can _remove_ the strings if you issue:
```js
Array.from(document.querySelectorAll(
    '.source code.python .hljs-class + .hljs-string, \
     .source code.python .hljs-function + .hljs-string')).forEach(
        el => el.parentNode.removeChild(el))
```
I guess something similar could be issued to wrap in `<details>`. I might be interested to carry something in under 300 characters, if you find it. :+1:

**Comment by derek-adair** [comment]
I was thinking something in the python code.  There is no reason to have the docstring in the code source link.

**Comment by derek-adair** [comment]
oh i misunderstood.  I'll have to dig in and submit a PR i guess.
