### ISSUE TITLE
Add configuration file

### ISSUE THREAD

**Issue by fabiosangregorio** [pdoc3/pdoc#193]
Running pdoc with all the config parameters can be a bit of a hassle, especially when developing the docs and experimenting with parameters tweaks.

E.g. 
```
pdoc --html --output-dir="docs/" --template-dir="docs/templates" --config show_source_code=False --force .
```

It would be nice if we could have a configuration file such as `.pdoc`, maybe in a .ini style, where the configuration could reside.

E.g.
```
[pdoc]
html = True
output_dir = "docs/"
template_dir = "docs/templates"
show_source_code = False
force = True
```

This would result in the much more compact CLI command `pdoc .` 

In my idea, any explicitly set CLI config parameters would override the `.pdoc` file parameters.

I would also add the option to specify a config file with `pdoc --config setup.cfg .` so that it can be possible to set the configuration in a global project config file.

This idea is heavily inspired by what [pydeps](https://github.com/thebjorn/pydeps) is currently handling configuration.

**Comment by kernc** [comment]
I wonder, where did you learn about `--config`, its possible values, and even `--template-dir` switch, yet seem to have missed mention of [_config.mako_ template](https://pdoc3.github.io/pdoc/doc/pdoc/#custom-templates) which works with it. :smiley:

**Comment by fabiosangregorio** [comment]
Ah sorry, I missed that part. You can go ahead and close the issue.

PS: is your profile picture a reference to Nazism? It certainly looks like so.

**Comment by kernc** [comment]
> PS: is your profile picture a reference to Nazism? It certainly looks like so.

It's indeed a [swastika](https://en.wikipedia.org/wiki/Swastika), which looks remotely similar to the Nazi symbol, but its intent and meaning here are hopefully wholly diametrical. :bow:
