### ISSUE TITLE
Comments in doctest code snippets shown as headings in sidebar TOC

### ISSUE THREAD

**Issue by plul** [pdoc3/pdoc#194]
Imagine that I write this in a module docstring:

```
"""
My math module.

Use it like this:

>>> # addition
>>> assert my_add(2, 2) == 4
>>> # subtraction
>>> assert my_sub(2, 2) == 0
"""
```

Then "addition" and "subtraction" become links in the sidebar.
I guess that they are incorrectly interpreted as markdown headers, when really they are python comments in a code block.

- pdoc version:
0.8.1

**Comment by kernc** [comment]
To markdown converter, those lines are simple text, not code blocks. For that, they'd have to be indented or ` ``` `-fenced. We go through some hoops to ensure unindented doctests are rendered properly:
https://github.com/pdoc3/pdoc/blob/004204320773cb98a8f0cd5fa82e8095f517e488/pdoc/html_helpers.py#L350-L359
I guess those same hoops (with memoization) should be applied when extracting TOC.

**Comment by kernc** [comment]
~~Interestingly,~~ Markdown considers `>>> # title` a title even when hash doesn't begin the line. It interprets it as a title within blockquote.
