### ISSUE TITLE
pdoc3 not skipping broken/old Python files

### ISSUE THREAD

**Issue by arcivanov** [pdoc3/pdoc#195]
I maintain [PyBuilder](https://github.com/pybuilder/pybuilder). We have a PDoc plugin, which was written for the now defunct PDoc. 

I've migrated PDoc plugin to PDoc3 for all Python 3.x versions and found the following issue:

```
    [DEBUG] Executing PDoc as: ['pdoc', '--html', '--overwrite', '--external-links', '--html-dir', '/tmp/IntegrationTestSupport6few1tm3/target/pdocs', 'pybuilder']
    [DEBUG] Executing command: 'pdoc' '--html' '--overwrite' '--external-links' '--html-dir' '/tmp/IntegrationTestSupport6few1tm3/target/pdocs' 'pybuilder'
    [ERROR] PDoc failed! See /tmp/IntegrationTestSupport6few1tm3/target/reports/pdoc.err for full details:
    	  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    	  File "/tmp/IntegrationTestSupport6few1tm3/src/main/python/pybuilder/excp_util_2.py", line 27
    	    raise ex, None, getattr(ex, "__traceback__", tb)
    	            ^
    	SyntaxError: invalid syntax
    	
    	During handling of the above exception, another exception occurred:
    	
    	Traceback (most recent call last):
    	  File "/tmp/IntegrationTestSupport6few1tm3/.pybuilder/plugins/cpython-3.8.2.final.0/bin/pdoc", line 8, in <module>
    	    sys.exit(main())
    	  File "/tmp/IntegrationTestSupport6few1tm3/.pybuilder/plugins/cpython-3.8.2.final.0/lib/python3.8/site-packages/pdoc/cli.py", line 452, in main
    	    modules = [pdoc.Module(module, docfilter=docfilter)
    	  File "/tmp/IntegrationTestSupport6few1tm3/.pybuilder/plugins/cpython-3.8.2.final.0/lib/python3.8/site-packages/pdoc/cli.py", line 452, in <listcomp>
    	    modules = [pdoc.Module(module, docfilter=docfilter)
    	  File "/tmp/IntegrationTestSupport6few1tm3/.pybuilder/plugins/cpython-3.8.2.final.0/lib/python3.8/site-packages/pdoc/__init__.py", line 650, in __init__
    	    self.doc[root] = m = Module(import_module(fullname),
    	  File "/tmp/IntegrationTestSupport6few1tm3/.pybuilder/plugins/cpython-3.8.2.final.0/lib/python3.8/site-packages/pdoc/__init__.py", line 198, in import_module
    	    raise ImportError('Error importing {!r}: {}'.format(module, e))
    	ImportError: Error importing 'pybuilder.excp_util_2': invalid syntax (excp_util_2.py, line 27)
    ------------------------------------------------------------
    BUILD FAILED - PDoc failed! See /tmp/IntegrationTestSupport6few1tm3/target/reports/pdoc.err for full details:
    	  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    	  File "/tmp/IntegrationTestSupport6few1tm3/src/main/python/pybuilder/excp_util_2.py", line 27
    	    raise ex, None, getattr(ex, "__traceback__", tb)
    	            ^
    	SyntaxError: invalid syntax
```

We have files in the source tree that are only loaded on certain versions of Python (2 vs 3, 3.5 vs 3.6 f-strings etc etc). 
The original PDoc used to just warn about not being able to load those. 
PDoc3 attempts to load them and fails completely.

It would be great if it were possible to make PDoc3 more flexible by simply warning and skipping the modules it could not load as the original PDoc did. Alternatively provide a way to skip certain files.

related to pybuilder/pybuilder#723, pybuilder/pybuilder#724

**Comment by arcivanov** [comment]
Relevant code: https://github.com/pdoc3/pdoc/blob/004204320773cb98a8f0cd5fa82e8095f517e488/pdoc/__init__.py#L197-L200

**Comment by kernc** [comment]
Warning instead of raising, conditional on `--warn-unimportable` (or similar), sounds reasonable. Care to make a PR for it?

Simultaneously, if Py2-only code paths are easily enumerable, [excluding modules via `__pdoc__` is an option](https://github.com/pdoc3/pdoc/issues/99#issuecomment-596721779):
```py
# package.py:

__pdoc__ = {
    "subpackage": False,
    "submodule": False,
    # package.subpackage and package.submodule will be skipped
}
```

**Comment by arcivanov** [comment]
> Finally, pdoc3 has an early forked Python2 branch (on PyPI) some claim to use, but its state is mainly indeterminate and, apart from minimal bugfixes, unsupported.

Issue is, I need to be able to skip PY2 code when running PDoc3 from Python 3 but not when from Python 2. Same applies running PDoc with 3.5 on 3.6+ code with f-strings etc.

**Comment by arcivanov** [comment]
I've contacted PDoc maintainer to see if they can cut a release as apparently the code has been advancing just not being published to PyPI for some reason. If not, I might cut a PR.

**Comment by arcivanov** [comment]
Related mitmproxy/pdoc#194

**Comment by kernc** [comment]
I meant if you maybe experience original PDoc maintainers as too passive. The code had indeed advanced in terms of moving around, but had also regressed, undoubtedly raising fret over any potential release.

**Comment by arcivanov** [comment]
Wonderful, thank you! Could you please cut a new release?

**Comment by kernc** [comment]
This should be already available. The CLI flag is `--skip-errors`. Thanks for testing it!
