### ISSUE TITLE
Link text displayed incorrectly

### ISSUE THREAD

**Issue by ButterflyBug** [pdoc3/pdoc#201]
The problem with displaying a link appears in the markdown file. To be more precise, once the link text is placed into [] and https or http is included, this link text is followed by the left angle bracket in generated documentation and leads to a non-existing page. In addition, the right angle bracket is added at the end of the reference.

### Expected Behavior

The link text which starts with https or http is correctly displayed in documentation - exactly the same as provided in [], i.e. :
- link text placed in [] in markdown file: `[https://google.com](https://google.com)`
- link text displayed in the documentation: `https://google.com`

### Actual Behavior

The text link displayed in documentation contains extra left angle bracket:

`<https://google.com`

What is more, the reference ends with the right angle bracket and as a result, it redirects to the page which does not exist:

`https://google.com/>`

### Steps to Reproduce

1. Create markdown file i.e. `readme.md` which contains:
```
[https://google.com](https://google.com)
```
2. Create python file i.e. `example.py` which contains:
```
"""
.. include:: ./readme.md
"""
```
3. Run `$ pdoc3 --http localhost:8080 example`
4. Open `$ http://localhost:8080`

![image](https://user-images.githubusercontent.com/49125893/82254153-a1d9e080-9952-11ea-8fc9-f17945cb88f1.png)

![image](https://user-images.githubusercontent.com/49125893/82254078-7bb44080-9952-11ea-8890-9a62e3a17415.png)

### Additional info

1. Operating system: Ubuntu 19.10
2. pdoc version: [pdoc 0.8.2.dev4+g048919e](https://github.com/pdoc3/pdoc/commit/048919ece483e0609094cee2460d3467d2e0efc3)
3. Python version: 3.8.0

**Comment by kernc** [comment]
Oops. :sweat_smile:  I believe the issue is in wrapping raw URLs in angle brackets for Python-[Markdown to see and anchor them](https://daringfireball.net/projects/markdown/syntax#autolink) (otherwise by default, marking-down merely `foo https://google.com foo` doesn't create a hyperlink).
https://github.com/pdoc3/pdoc/blob/048919ece483e0609094cee2460d3467d2e0efc3/pdoc/html_helpers.py#L361-L368
Can you propose a fix/workaround?

**Comment by ButterflyBug** [comment]
I will try ;D
