### ISSUE TITLE
Installation and Testing info as a part of documentation

### ISSUE THREAD

**Issue by ButterflyBug** [pdoc3/pdoc#204]
### Description

Once I decided to contribute to this project I had some difficulties in finding information on how to install dependencies and run tests. I expected to find those details in README or in the documentation. I've seen in https://github.com/pdoc3/pdoc/commit/03de77f804c0b2b9f129153a7a2968385c0c84c2# that you got rid of the Development part from README, probably for some significant reason :smile: 
I think that having this part described in a separate file keeps your documentation a clean one :smile:  but on the other hand, it would be also great to mention the installation and testing in contributing section (for example via link) or directly in README (again). What do you think? :smile:

**Comment by kernc** [comment]
> you got rid of the Development part from README, probably for some significant reason

It was [extended into](https://github.com/pdoc3/pdoc/commit/03de77f804c0b2b9f129153a7a2968385c0c84c2#diff-6a3371457528722a734f3c51d9238c13R23-R32) the developmental installation section. The _whole_ of [_contributing.md_](https://github.com/pdoc3/pdoc/blob/master/CONTRIBUTING.md) is about development. There's even a section about testing. GitHub [had](https://github.blog/2012-09-17-contributing-guidelines/) [promoted](https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors) this file scheme for some time now.

Non-developmental installation is [documented for the mere user](https://github.com/pdoc3/pdoc#installation). Are you saying a link to contributing info should be put back into the main readme? In that case, following the brevity of style, welcome. :smiley:

**Comment by kernc** [comment]
Fixed in https://github.com/pdoc3/pdoc/issues/205.
