### ISSUE TITLE
Conda package

### ISSUE THREAD

**Issue by ricardojumia** [pdoc3/pdoc#21]
I use python in a conda environment and would like to know if you're going to make pdoc3 available there.

I know this is not exactly an "issue" but I couldn't find your contact anywhere and I'd really appreciate your help.

Thank you!

**Comment by kernc** [comment]
I don't use Anaconda myself, but as far as I understand, packages from PyPI (installed with pip) should [work just the same](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html#installing-non-conda-packages)?

How does one make a package available in conda?

**Comment by ricardojumia** [comment]
You can install PyPI packages in conda but it's not recommended even with best practices - which are very cumbersome.
https://www.anaconda.com/using-pip-in-a-conda-environment/

As for making it available in conda, I've never done this myself but I think you can use conda build.
https://conda.io/projects/conda-build/en/latest/source/recipe.html

**Comment by AlexFiliakov** [comment]
This might be an enhancement? We use conda, so I may look into making pdoc3 available through the conda environment.

**Comment by ricardojumia** [comment]
I ended up installing it with pip and it worked. A conda build would nonetheless be useful to avoid conflicts in the future. And yes, this would be an enhancement.

**Comment by analog-cbarber** [comment]
pip install into a conda environment can work, but because pip and conda dependencies can be different this can lead to incorrect configurations or even crashes. For this reason, experienced conda users avoid pip installs whenever possible.

If you want wider adoption, you really should build a conda distribution and publish on conda-forge.

**Comment by kernc** [comment]
I agree but happen to not use conda at all. If someone wants to duly maintain a conda package on conda-forge, please step up. :+1:

**Comment by msarahan** [comment]
https://github.com/conda-forge/staged-recipes/pull/10220 will add this to conda-forge.

**Comment by kernc** [comment]
If anyone would like to help @msarahan co-maintain the package on conda-forge, welcome and appreciated.

**Comment by kernc** [comment]
The package is [available on conda-forge](https://anaconda.org/conda-forge/pdoc3).

**Comment by jacobwilliams** [comment]
https://github.com/conda-forge/pdoc3-feedstock  <---looks like it is out of date (stuck on 0.8.1 right now). Do you need another volunteer to help maintain this?

**Comment by msarahan** [comment]
Thanks for pointing this out. I set the bot to automerge the update PRs. If you'd like to help maintain it otherwise, please open an issue on the feedstock repo that has the following text in the body:

```
@conda-forge-admin, please add user @jacobwilliams 
```
