### ISSUE TITLE
Instance variables for sub-classes of `typing_extensions.TypedDict` not documented.

### ISSUE THREAD

**Issue by sg495** [pdoc3/pdoc#210]
### Expected Behavior

Instance variables for subclasses of `typing_extensions.TypedDict` should be documented similarly to what happens with instance variables for subclasses of `typing.NamedTuple`.

 Create a subclass of `typing.NamedTuple` with annotations:

```python
from typing import NamedTuple
class Employee(NamedTuple):
    """ An employee. """
    name: str
    """ The name of the employee. """
    id: int
    """ The id of the employee. """
```

Run `pdoc --config show_type_annotations=True` and you see both the class and the instance variables documented:

```
Classes
-------

`Employee(name: str, id: int)`
:   An employee.

    ### Ancestors (in MRO)

    * builtins.tuple

    ### Instance variables

    `id`
    :   The id of the employee.

    `name`
    :   The name of the employee.
```

Now create a subclass of `typing_extensions.TypedDict` with annotations:

```python
from typing_extensions import TypedDict
class Employee(TypedDict, total=True):
    """ An employee. """
    name: str
    """ The name of the employee. """
    id: int
    """ The id of the employee. """
```

When running `pdoc --config show_type_annotations=True`, you may similarly expect to see both the class and the instance variables documented:

```
Classes
-------

`Employee(*args, **kwargs)`
:   An employee.

    ### Ancestors (in MRO)

    * builtins.dict

    ### Instance variables

    `id`
    :   The id of the employee.

    `name`
    :   The name of the employee.
```

### Actual Behavior

Instance variables for subclasses of `typing_extensions.TypedDict` are not documented.

Create a subclass of `typing_extensions.TypedDict` with annotations:

```python
from typing_extensions import TypedDict
class Employee(TypedDict, total=True):
    """ An employee. """
    name: str
    """ The name of the employee. """
    id: int
    """ The id of the employee. """
```

Run `pdoc --config show_type_annotations=True` and you only see the class documentation, but not the instance variables:

```
Classes
-------

`Employee(*args, **kwargs)`
:   An employee.

    ### Ancestors (in MRO)

    * builtins.dict
```

### Steps to Reproduce

1. Create a subclass of `typing_extensions.TypedDict` with annotations for the dictionary fields.
2. Run `pdoc` (or `pdoc --config show_type_annotations=True`) to generate documentation for it.

### Additional info

- pdoc version:
```
C:\Users\sg495>pdoc --version
pdoc.exe 0.8.1
```

**Comment by kernc** [comment]
The issue stems from the fact that `inspect.getmembers(Employee)` doesn't list members `name` and `id` in its enumeration.
https://github.com/pdoc3/pdoc/blob/048919ece483e0609094cee2460d3467d2e0efc3/pdoc/__init__.py#L874-L879

Related issue: https://github.com/pdoc3/pdoc/issues/200.

**Comment by kernc** [comment]
As long as we're happy to see `Foo.f` in:
```py
import types

class Foo:
    f: types.FunctionType
```
documented as a variable instead of a function, https://github.com/pdoc3/pdoc/pull/226 will fix this. Thanks! :grin:
