### ISSUE TITLE
Hyperlinks not created for type aruments of collections with more than one type parameter

### ISSUE THREAD

**Issue by sg495** [pdoc3/pdoc#211]
### Expected Behavior

When using type annotations and generating HTML documentation (e.g. with `pdoc --config show_type_annotations=True --html test.py` used below), hyperlinks are automatically created for all type annotations using classes from the module.

One would expect hyperlinks to also be created when the classes appear as type parameters in the typed collections (and other type constructors) from the `typing` module.
Indeed, this appears to work as expected when using typed collections taking a single type parameter, such as `typing.List` and `typing.Set`.

### Actual Behavior

Hyperlinks are not created for type parameters of `typing` collections and type constructors taking more than one type parameter, such as `typing.Dict`, `typing.Tuple` or `typing.Union`.

The Inner HTML from the `article` tag of sample HTML documentation is included at the end of this issue.

This issue seems related to #145, but is still occurring with the latest version I could install with `pip` (version 0.8.1). Adding spaces as suggested in that issue (e.g. `Dict[ str, Employee ]` instead of `Dict[str, Employee]`) does not solve the probem for me.

### Steps to Reproduce

1. Use type hints involving typed collections or orther type constructors from the `typing` module which take more than one type parameter.
2. Run `pdoc --config show_type_annotations=True --html` to generate HTML documentation with type annotations.

### Additional info

- pdoc version:
```
C:\Users\sg495>pdoc --version
pdoc.exe 0.8.1
```

### Sample HTML documentation

<header>
<h1 class="title">Module <code>test</code></h1>
</header>
<section id="section-intro">
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python hljs"><span class="hljs-keyword">from</span> typing <span class="hljs-keyword">import</span> Dict, List, Mapping, Set, Tuple, Union

<span class="hljs-class"><span class="hljs-keyword">class</span> <span class="hljs-title">Employee</span>:</span>
    <span class="hljs-string">""" An employee. """</span>
    name: str
    ID: int

<span class="hljs-function"><span class="hljs-keyword">def</span> <span class="hljs-title">foo_list</span><span class="hljs-params">(employees: List[Employee])</span>:</span>
    ...

<span class="hljs-function"><span class="hljs-keyword">def</span> <span class="hljs-title">foo_tuple_variadic</span><span class="hljs-params">(employees: Tuple[Employee, ...])</span>:</span>
    ...

<span class="hljs-function"><span class="hljs-keyword">def</span> <span class="hljs-title">foo_tuple_fixed</span><span class="hljs-params">(employees: Tuple[Employee, str])</span>:</span>
    ...

<span class="hljs-function"><span class="hljs-keyword">def</span> <span class="hljs-title">foo_set</span><span class="hljs-params">(employees: Set[Employee])</span>:</span>
    ...

<span class="hljs-function"><span class="hljs-keyword">def</span> <span class="hljs-title">foo_dict</span><span class="hljs-params">(employees: Dict[str, Employee])</span>:</span>
    ...

<span class="hljs-function"><span class="hljs-keyword">def</span> <span class="hljs-title">foo_union</span><span class="hljs-params">(employees: Union[Employee, str])</span>:</span>
    ...</code></pre>
</details>
</section>
<section>
</section>
<section>
</section>
<section>
<h2 class="section-title" id="header-functions">Functions</h2>
<dl>
<dt id="test.foo_dict"><code class="name flex">
<span>def <span class="ident">foo_dict</span></span>(<span>employees:&nbsp;Dict[str,&nbsp;test.Employee])</span>
</code></dt>
<dd>
<section class="desc"></section>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python hljs"><span class="hljs-function"><span class="hljs-keyword">def</span> <span class="hljs-title">foo_dict</span><span class="hljs-params">(employees: Dict[str, Employee])</span>:</span>
    ...</code></pre>
</details>
</dd>
<dt id="test.foo_list"><code class="name flex">
<span>def <span class="ident">foo_list</span></span>(<span>employees:&nbsp;List[<a title="test.Employee" href="#test.Employee">Employee</a>])</span>
</code></dt>
<dd>
<section class="desc"></section>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python hljs"><span class="hljs-function"><span class="hljs-keyword">def</span> <span class="hljs-title">foo_list</span><span class="hljs-params">(employees: List[Employee])</span>:</span>
    ...</code></pre>
</details>
</dd>
<dt id="test.foo_set"><code class="name flex">
<span>def <span class="ident">foo_set</span></span>(<span>employees:&nbsp;Set[<a title="test.Employee" href="#test.Employee">Employee</a>])</span>
</code></dt>
<dd>
<section class="desc"></section>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python hljs"><span class="hljs-function"><span class="hljs-keyword">def</span> <span class="hljs-title">foo_set</span><span class="hljs-params">(employees: Set[Employee])</span>:</span>
    ...</code></pre>
</details>
</dd>
<dt id="test.foo_tuple_fixed"><code class="name flex">
<span>def <span class="ident">foo_tuple_fixed</span></span>(<span>employees:&nbsp;Tuple[test.Employee,&nbsp;str])</span>
</code></dt>
<dd>
<section class="desc"></section>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python hljs"><span class="hljs-function"><span class="hljs-keyword">def</span> <span class="hljs-title">foo_tuple_fixed</span><span class="hljs-params">(employees: Tuple[Employee, str])</span>:</span>
    ...</code></pre>
</details>
</dd>
<dt id="test.foo_tuple_variadic"><code class="name flex">
<span>def <span class="ident">foo_tuple_variadic</span></span>(<span>employees:&nbsp;Tuple[test.Employee,&nbsp;...])</span>
</code></dt>
<dd>
<section class="desc"></section>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python hljs"><span class="hljs-function"><span class="hljs-keyword">def</span> <span class="hljs-title">foo_tuple_variadic</span><span class="hljs-params">(employees: Tuple[Employee, ...])</span>:</span>
    ...</code></pre>
</details>
</dd>
<dt id="test.foo_union"><code class="name flex">
<span>def <span class="ident">foo_union</span></span>(<span>employees:&nbsp;Union[test.Employee,&nbsp;str])</span>
</code></dt>
<dd>
<section class="desc"></section>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python hljs"><span class="hljs-function"><span class="hljs-keyword">def</span> <span class="hljs-title">foo_union</span><span class="hljs-params">(employees: Union[Employee, str])</span>:</span>
    ...</code></pre>
</details>
</dd>
</dl>
</section>
<section>
<h2 class="section-title" id="header-classes">Classes</h2>
<dl>
<dt id="test.Employee"><code class="flex name class">
<span>class <span class="ident">Employee</span></span>
</code></dt>
<dd>
<section class="desc"><p>An employee.</p></section>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python hljs"><span class="hljs-class"><span class="hljs-keyword">class</span> <span class="hljs-title">Employee</span>:</span>
    <span class="hljs-string">""" An employee. """</span>
    name: str
    ID: int</code></pre>
</details>
</dd>
</dl>
</section>

**Comment by kernc** [comment]
The issue is in lines:
https://github.com/pdoc3/pdoc/blob/ea3d4f638d6d4824318e4b96b4ff73039646f39b/pdoc/__init__.py#L1288-L1293
Since spaces are replaced with `\N{NBSP}`, `s.rsplit()` doesn't split on `annotation` text which is no longer there.
