### ISSUE TITLE
Type hints of instance variables are not documented

### ISSUE THREAD

**Issue by sg495** [pdoc3/pdoc#212]
### Expected Behavior

Just as the type hints for instance methods are documented, so should the type hints for instance variables.

Consider for example:

```python
class Employee:
    """ An employee. """
    name: str
    """ The name of the employee. """
    @property
    def ID(self) -> int:
        """ The id of the employee. """
        return len(self.name)
```

Running `pdoc --config show_type_annotations=True` one might expect something like this:

```
Classes
-------
`Employee()`
:   An employee.

    ### Instance variables

    `name: str`
    :   The name of the employee.

    `ID: int`
    :   The id of the employee.
```

### Actual Behavior

Type hints for instance variables are not documented, neither for attributes nor for properties.
Instance variables implemented by attributes are not documented at all unless the documentation is given in `__init__` (where the type hints cannot be used), even in those cases where the attributes are declared by giving a type hint for them.

```python
class Employee:
    """ An employee. """
    name: str
    """ The name of the employee. """
    @property
    def ID(self) -> int:
        """ The id of the employee. """
        return len(self.name)
```

Running `pdoc --config show_type_annotations=True` results in the instance variable `name` being ignored, and in both type hints being ignored:

```
Classes
-------

`Employee()`
:   An employee.

    ### Instance variables

    `ID`
    :   The id of the employee.
```

### Steps to Reproduce

1. Create any class with type hints for type variables.
2. Run `pdoc --config show_type_annotations=True`

### Additional info

- pdoc version:
```
C:\Users\sg495>pdoc --version
pdoc.exe 0.8.1
```

**Comment by kernc** [comment]
The reason type annotations aren't shown for markdown output is that _text.mako_ template was missed in https://github.com/pdoc3/pdoc/pull/175 and its follow-ups (such as https://github.com/pdoc3/pdoc/commit/2f3db5f16370145193cbd4ea49af00c22fc246ee most recently).
https://github.com/pdoc3/pdoc/blob/ea3d4f638d6d4824318e4b96b4ff73039646f39b/pdoc/templates/text.mako#L14-L27

The reason `name` isn't listed at all is, again, that `inspect.getmembers(Employee)` doesn't list it in its enumeration. :roll_eyes: (Related issues: #210, #200.)
