### ISSUE TITLE
Submodules are not showing in generated HTML file

### ISSUE THREAD

**Issue by JiKook31** [pdoc3/pdoc#215]
I don't think it's an actual issue, but I couldn't find any solution for my problem, so I'm writing here. Can anyone please help me and tell me what is needed to be done in order for submodules section to be included in HTML page?

### Expected Behavior
HTML file contains documentation of specified file and submodules section

### Actual Behavior
No submodules section is generated

### Steps to Reproduce
1. Directory structure:
| file_a.py
| \_\_init\_\_.py (empty)
| src
_____| file_b.py
_____| \_\_init\_\_.py (empty)

2. file_b is imported in file_a (`from src import file_b`) and HTML page is generated for file_a in root directory:
`pdoc --html file_a`

### Additional info

- pdoc version: 0.8.1

**Comment by kernc** [comment]
> No submodules section is generated
>
> file_b is imported in file_a

Simply importing a module does not put it within/under the current package hierarchy. Essentially, file_b is _not_ a Python submodule of file_a, and pdoc reflects that.

A more customary [directory layout for python projects](https://stackoverflow.com/a/5998845/1090455) is:
```
project_checkout_dir
├── project
│   ├── __init__.py
│   ├── module_a.py
│   └── module_b.py
├── README
└── setup.py
```
This way, one can:
```bash
cd project_checkout_dir
pdoc --html project
```
