### ISSUE TITLE
Document multiple versions of a project

### ISSUE THREAD

**Issue by H4dr1en** [pdoc3/pdoc#217]
Hi, 

First of all: thanks for the great work!

I would like have CI/CD of the documentation of my projects in a private static website and I am looking for a way to navigate between the different versions of the projects. Something close to what readthedocs provides.

My first guess was to have the documentation built for each version in different subfolders and edit the mako templates to show this kind of dropdown bar with the list of available version.

Is there a more straightfoward /already available/recommended way to achieve this?

**Comment by kernc** [comment]
Thanks! Nothing so far. Your approach seems reasonable. Checking out tagged releases and generating output in versioned subfolders, all the while injecting a common header switcher template seems doable rather easily in a few straight lines of POSIX shell.

You're strongly encouraged to share your recipe afterwards! :smiley:

**Comment by rozsasarpi** [comment]
In our projects -- hosted on GitLab -- we solved this with using GitLab pages and Environments, see e.g. 
https://stackoverflow.com/questions/55596789/deploying-gitlab-pages-for-different-branches/58402821#58402821

Currently we automatically generate a unique static documentation page (using `pdoc3`) for each branch. It is not a perfect solution but it does the job and easy to set up. I cannot share an example project as they are all private ones but I can give guidance if this approach would suit your needs.

**Comment by H4dr1en** [comment]
Thanks for your answers! I ended up with the following setup:
- a bash script that pulls a repo, checkout the different tags and retrieve the /docs folder of each git tag.
- a cron job per repo that calls this bash script periodically
- a caddy file server to browse the folder where all repos and versions are stored
