### ISSUE TITLE
Multiple line return description doesn't render well

### ISSUE THREAD

**Issue by yochem** [pdoc3/pdoc#219]
### Expected Behavior
![image](https://user-images.githubusercontent.com/23235841/85070893-e3121a00-b1b6-11ea-97cc-bb6516ec4644.png)

Expected behaviour would be that the words 'which is the answer of everything' would be in the same style as the rest of the text below `Returns`.

### Actual Behavior
As can be seen above, text on next lines in return statements are rendered as normal text.

### Steps to Reproduce

1. open test.py and insert this:
```python
def f():
    """
    Returns:
        A very special number
        which is the answer of everything.
    """
    return 42
```
2.`$  pdoc3 --html test.py`
3. `$ open html/test.html`

### Additional info
- pdoc version: 0.8.1
- MacOS version: 10.15.5 (19F101)
- Python version: 3.7.7

**Comment by kernc** [comment]
Thanks. This appears to be a [valid Google-style docstring](https://google.github.io/styleguide/pyguide.html#doc-function-args), so it's indeed a bug.
