### ISSUE TITLE
Make closing stdin optional?

### ISSUE THREAD

**Issue by nicolaskruchten** [pdoc3/pdoc#22]
For the module I'm working on, this defensive line is actually breaking things because a dependency of a dependency is checking if `stdin` is open: https://github.com/pdoc3/pdoc/blob/master/pdoc/cli.py#L285

Would it be possible to allow this behaviour to be turned off via a flag or environment variable? If you'd accept such a PR I'd be happy to contribute it :)

**Comment by kernc** [comment]
I'm not entirely sure [why it was introduced](https://github.com/pdoc3/pdoc/commit/94b8c3a1fb07d899a6f5dbbc5247798589e792c9) in the first place; I'd likely prefer to consider modules messing with stdin outside their `__name__ == '__main__'` block wholly misbehaved.

I think it would be acceptable to make the default remain open and only close it upon `--close-stdin`.

**Comment by nicolaskruchten** [comment]
I agree that these modules are misbehaving, but I can't really control dependencies of dependencies :) I'll try to get a PR in today, leaving the current behaviour on by default but allowing for it to be disabled.

**Comment by kernc** [comment]
I'm happy with inverting the default. We've made some best-effort incompatibility changes recently, so this won't strike anyone as odd. Times were different [when this was introduced](https://github.com/pdoc3/pdoc/blob/a2926a7766c2745d24cd8cb69e3c3077971b82e8/pdoc#L349-L357). :smile:
