### ISSUE TITLE
Cross-references in Google-style docstrings rendered incorrectly

### ISSUE THREAD

**Issue by professorchaos97** [pdoc3/pdoc#220]
### Expected Behavior
Cross-references should be formatted like everything else, except with hyperlinks, like this Numpy-style docstring does:

```python
class ClassA:
    """Some class.

    Attributes
    ----------
    a : int
        The answer to life, the universe and everything.
    b : `ClassB`
        Some object.
    """
    def __init__(self):
        self.a = 42
        self.b = ClassB()

class ClassB:
    """Some class."""
    pass
```
![Screenshot at 2020-06-20 15-58-38](https://user-images.githubusercontent.com/39624370/85203639-65155680-b30f-11ea-9520-6a2725ebfbb3.png)

### Actual Behavior
With Google-style docstrings like in the following snippet, the formatting is missing.
```python
class ClassA:
    """Some class.

    Attributes:
        a (int): The answer to life, the universe and everything.
        b (`ClassB`): Some object.
    """
    def __init__(self):
        self.a = 42
        self.b = ClassB()

class ClassB:
    """Some class."""
    pass

```
![Screenshot at 2020-06-20 15-51-03](https://user-images.githubusercontent.com/39624370/85203632-5c248500-b30f-11ea-999d-ba1a7a6a270a.png)

### Steps to Reproduce

- Run with `pdoc3 --html`

### Additional info

- pdoc version: 0.8.1

**Comment by kernc** [comment]
```text
    Attributes
    ----------
    a : int
        The answer to life, the universe and everything.
    b : `ClassB`
        Some object.

    Attributes:
        a (int): The answer to life, the universe and everything.
        b (`ClassB`): Some object.
```

You don't backtick references in docstring type parameters. Leave those as plain text. They are wrapped in `<code>` and hyperlinked by default.

**Comment by professorchaos97** [comment]
Oh wow, I am actually an idiot. I used the backticks because I wasn't getting hyperlinks in a submodule, turns out I didn't specify the complete path (and then did when using the backticks after I found it in the documentation). Thanks for the quick response!
