### ISSUE TITLE
How to document projects using Kivy?

### ISSUE THREAD

**Issue by Buddelpi** [pdoc3/pdoc#222]
### Expected Behavior
When running the simple pdoc command on the main file of the project the documentation is generated properly in the Doc folder.
The command used:  _pdoc3 --html --output-dir Doc --force main.py_

### Actual Behavior
When running the above command, somehow kivy starts to run and documentation is not generated. The following output is shown:
```
Andras-MacBook-Pro:MyKivyProg delpi$ pdoc3 --html --output-dir Doc --force main.py
[INFO   ] [Logger      ] Record log in /Users/delpi/.kivy/logs/kivy_20-06-25_3.txt
[ERROR  ] [Core        ] option --html not recognized
Kivy Usage: pdoc3 [OPTION...]::

        -h, --help
            Prints this help message.
        -d, --debug
            Shows debug log.
        -a, --auto-fullscreen
            Force 'auto' fullscreen mode (no resolution change).
            Uses your display's resolution. This is most likely what you want.
        -c, --config section:key[:value]
            Set a custom [section] key=value in the configuration object.
        -f, --fullscreen
            Force running in fullscreen mode.
        -k, --fake-fullscreen
            Force 'fake' fullscreen mode (no window border/decoration).
            Uses the resolution specified by width and height in your config.
        -w, --windowed
            Force running in a window.
        -p, --provider id:provider[,options]
            Add an input provider (eg: ccvtable1:tuio,192.168.0.1:3333).
        -m mod, --module=mod
            Activate a module (use "list" to get a list of available modules).
        -r, --rotation
            Rotate the window's contents (0, 90, 180, 270).
        -s, --save
            Save current Kivy configuration.
        --size=640x480
            Size of window geometry.
        --dpi=96
            Manually overload the Window DPI (for testing only.)
```

### Steps to Reproduce

1. Run pdoc on a kivy projects main file
2.
3.

### Additional info

- pdoc version: pdoc3 0.8.1

**Comment by kernc** [comment]
Please see this [footnote](https://pdoc3.github.io/pdoc/doc/pdoc/#fn:execution) or this similar question https://github.com/pdoc3/pdoc/issues/180. Since the modules are executed, you need to `if __name__ == '__main__':` guard your main Kivy entry point.

**Comment by Buddelpi** [comment]
Thank you for your answer.
Actually I already had the main guard around the Kivy entry point, as follows:

```
if __name__ == '__main__':
    MyApp().run()
```

Am I doing something wrong or there is still something to do to run pdoc properly with Kivy?

**Comment by kernc** [comment]
> I already had the main guard around the Kivy entry point

That's really curious then. Definitely has to do with some global Kivy code somewhere.
Can you build a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example) to reproduce the issue with?

**Comment by Buddelpi** [comment]
Sure.
I get the same result with this test code as well. (I checked now and I get the same for any of my Kivy based programs)

```
from kivy.app import App
from kivy.uix.label import Label

class MainApp(App):
    def build(self):
        label = Label(text='Hello from Kivy',
                      size_hint=(.5, .5),
                      pos_hint={'center_x': .5, 'center_y': .5})

        return label

if __name__ == '__main__':
    app = MainApp()
    app.run()
```

**Comment by Buddelpi** [comment]
What is also interesting, is that I also get the same result if I run pdoc on single python files, where I have defined some classes inherited from Kivy classes, but there are no function calls in these files. 

For example something like this:

```
from kivy.uix.widget import Widget

class anInheritedClass(Widget):
    anAttribute = NumericProperty(0)

    def aMethod(self):
        return True
```

**Comment by kernc** [comment]
Ok, `pdoc test_kivy.py` for the above two examples _works_. What triggers it is `--html` switch, resulting in Kivy's:
```
[ERROR  ] [Core        ] option --html not recognized
```
Kivy taking over program arguments even when not executed. While decidedly unusual, we could maybe follow the advice here https://github.com/ipython/ipython/issues/9133#issuecomment-172107637 and reset:
```py
sys.argv[1:] = []
```
after parsing our own arguments. :thinking: 

A quick workaround for you is to set [KIVY_NO_ARGS environment variable](https://kivy.org/doc/stable/guide/environment.html#configuration) before invoking pdoc:
```bash
KIVY_NO_ARGS=1 pdoc3 --html -o Doc -f main.py
```

**Comment by kernc** [comment]
> we could maybe follow the advice here [ipython/ipython#9133 (comment)](https://github.com/ipython/ipython/issues/9133#issuecomment-172107637) and reset `sys.argv`

:-1:

Revisit when the problem pops up more widely (e.g. in other like frameworks).
