### ISSUE TITLE
0.8.2 - some headings not displayed in the index

### ISSUE THREAD

**Issue by polakowo** [pdoc3/pdoc#223]
By upgrading from 0.8.1 to 0.8.2 some of my headings are not shown in the index. The source is [here](https://github.com/polakowo/vectorbt/blob/master/vectorbt/__init__.py). It shows "How it works", "Performance", but ignores "Usability" and other headings up to "base". The HTML output is [here](https://github.com/polakowo/vectorbt/blob/ac90f19f5a78ce2b83114b1bc6e33530258e45a5/docs/index.html#L1381). The way it should be is illustrated [here](https://polakowo.io/vectorbt/docs/index.html) (0.8.1).

**Comment by kernc** [comment]
Thanks @polakowo. Expect a fixup release later today. :sweat_smile:
