### ISSUE TITLE
Make identifiers sorting optional

### ISSUE THREAD

**Issue by nicolaskruchten** [pdoc3/pdoc#23]
Would you accept a PR to make sorting optional in the documentation (new CLI arg, defaulting to current behaviour)? I rather like the order in which the functions/methods are declared in my module and I'd rather the documentation follow that order rather than a strictly alphabetical one :)

**Comment by kernc** [comment]
Certainly! What approach were you going to go about it? I think I'd prefer the flag passed to methods (e.g. `Class.functions(sort=True)`) from inside the theme than passed in `Module` / `Class` constructors.

**Comment by nicolaskruchten** [comment]
That makes sense to me, thanks for the input!

**Comment by nicolaskruchten** [comment]
Unfortunately this will not be trivial, as `inspect.getmembers()` returns items pre-sorted :(

**Comment by kernc** [comment]
In Python 3.6+, traversing .\_\_dict\_\_ should retain definition order (?). This shouldn't be a problem since we filter "own" members anyway:
https://github.com/pdoc3/pdoc/blob/c423762573b227e0025d670b58137fb7aa57498d/pdoc/__init__.py#L1134-L1139

**Comment by nicolaskruchten** [comment]
Right but the issue is that the inspect module already sorts items before returning them so the initial order is already lost by the time this code executes.

**Comment by kernc** [comment]
I thought you were intent on changing the code. :grinning:

We can iterate over `self.obj.__dict__` as a replacement for `inspect.getmembers()`. :+1:

**Comment by nicolaskruchten** [comment]
Ah gotcha. I wasn’t sure how deep you were OK with me going in terms of these modifications :) should I aim to remove the use of inspect altogether?

**Comment by kernc** [comment]
Altogether no. It's actually the preferred API, so only where no other way around, like here.
