### ISSUE TITLE
nptyping annotations point to internal types

### ISSUE THREAD

**Issue by EmJay276** [pdoc3/pdoc#231]
Building the html documentation does not resolve the nptyping types correctly, see variable "C" below

### Expected Behavior

> <html lang="en">
> <body>
> <main>
> <article id="content">
> <section>
> <h2 class="section-title" id="header-classes">Classes</h2>
> <dl>
> <dt id="core.example.Material"><code class="flex name class">
> <span>class <span class="ident">Material</span></span>
> <span>(</span><span>E: float)</span>
> </code></dt>
> <dd>
> <div class="desc"><p>Stores material data</p></div>
> <h3>Instance variables</h3>
> <dl>
> <dt id="core.example.Material.C"><code class="name">var <span class="ident">C</span> : numpy.ndarray[(6, 6), Float[64]]</code> <-------------</dt>
> <dd>
> <div class="desc"><p>material stiffness matrix</p></div>
> </dd>
> <dt id="core.example.Material.E1"><code class="name">var <span class="ident">E1</span> : float</code></dt>
> <dd>
> <div class="desc"><p>Young's modulus</p></div>
> </dd>
> </dl>
> </dd>
> </dl>
> </section>
> </article>
> </body>
> </html>

### Actual Behavior

> <html lang="en">
> <body>
> <main>
> <article id="content">
> <section>
> <h2 class="section-title" id="header-classes">Classes</h2>
> <dl>
> <dt id="core.example.Material"><code class="flex name class">
> <span>class <span class="ident">Material</span></span>
> <span>(</span><span>E: float)</span>
> </code></dt>
> <dd>
> <div class="desc"><p>Stores material data</p></div>
> <h3>Instance variables</h3>
> <dl>
> <dt id="core.example.Material.C"><code class="name">var <span class="ident">C</span> : nptyping.types._ndarray.NDArray</code> <-------------</dt>
> <dd>
> <div class="desc"><p>material stiffness matrix</p></div>
> </dd>
> <dt id="core.example.Material.E1"><code class="name">var <span class="ident">E1</span> : float</code></dt>
> <dd>
> <div class="desc"><p>Young's modulus</p></div>
> </dd>
> </dl>
> </dd>
> </dl>
> </section>
> </article>
> </body>
> </html>

### Steps to Reproduce
```py
import nptyping as npt
import numpy as np


class Material:
    """
    Stores material data
    """
    E1: float
    C: npt.NDArray[(6, 6), np.double]

    def __init__(self, E: float):
        self.E1 = E
        """Young's modulus"""
        self.C = np.zeros((6, 6), dtype=np.double)
        """material stiffness matrix"""
```

### Additional info

- pdoc version: 0.8.1

**Comment by kernc** [comment]
```python
>>> import inspect, typing
>>> annot = typing.get_type_hints(Material)['C']

>>> annot                            # pure repr is fine
NDArray[(6, 6), Float[64]]

>>> inspect.formatannotation(annot)  # but we call this on it
'nptyping.types._ndarray.NDArray'
```
And `inspect.formatannotation()` uses class' `.__module__` ...

https://github.com/pdoc3/pdoc/blob/04960e41b9bb598b664a50078f4c233817326170/pdoc/__init__.py#L1222
