### ISSUE TITLE
pdoc server running in Docker container

### ISSUE THREAD

**Issue by johncalab** [pdoc3/pdoc#232]
### Expected Behavior
Expect to access pdoc server on localhost:8080, but no requests reach the container.

### Steps to Reproduce

1. Create docker container with docker container run -p 8080:8080 image_name
2. Run pdoc server from within container: pdoc --http : module_name
3. go to localhost:8080

### Additional info

- pdoc version: latest

Publishing the ports works fine with jupyter notebooks, but I can't figure out how to talk to pdoc from outside docker.

**Comment by kernc** [comment]
Try to run: `pdoc --http 0.0.0.0:8080 ...` ([explanation](https://stackoverflow.com/questions/38834434/how-are-127-0-0-1-0-0-0-0-and-localhost-different)). ~~Maybe that should be the default.~~ :thinking: 
https://github.com/pdoc3/pdoc/blob/04960e41b9bb598b664a50078f4c233817326170/pdoc/cli.py#L123

> * pdoc version: latest

Not that it matters much here, but specifying version succinctly like this requires one of the posterity to be aware of the post date and then look up the corresponding version in the [release history](https://github.com/pdoc3/pdoc/blob/master/CHANGELOG) ...

**Comment by johncalab** [comment]
You are right, that's sloppy. pdoc version 0.8.3.

**Comment by johncalab** [comment]
by the way, it WORKED!

Solution:

run docker container with: docker container run -p 8080:8080

from inside the container, run the pdoc server with: pdoc --http 0.0.0.0:8080
