### ISSUE TITLE
Homepage quote bug

### ISSUE THREAD

**Issue by pathway** [pdoc3/pdoc#235]
### Expected Behavior
No language on the homepage that implies that sexual abuse does not exist.

### Actual Behavior
```
Documentation is like sex: when it is good, it is very, very good; and when it is bad, it is better than nothing.
```
This implies enjoyment of any type of sexual experience is always above zero.  This denies the possibility of sexual abuse.

Anyone who has, or has ever met someone who has, experienced sexual abuse would disagree.

### Steps to Reproduce

1. Visit https://pdoc3.github.io/pdoc/
2. reads: "Documentation is like sex: when it is good, it is very, very good; and when it is bad, it is better than nothing."

### Additional info

- pdoc version: pdoc3 website as of when I filed the issue.

**Comment by pathway** [comment]
Also, thanks for the awesome repo!

**Comment by kernc** [comment]
The internet is full of quotes not everyone "agrees" with.
