### ISSUE TITLE
__init__method is not listed in its own section in class docs

### ISSUE THREAD

**Issue by jkugler** [pdoc3/pdoc#239]
### Expected Behavior
I have a class which inherits and overrides certain behavior, including the constructor (`__init__`). I would expect the doc strings for the class, constructor, and overridden method to all be separate, and the methods all listed.

### Actual Behavior
The doc strings for the class and constructor are put together, and there is no section for the __init__ method.

### Steps to Reproduce
```
class ArgumentParser(argparse.ArgumentParser):
    """A custom argument parser"""

    def __init__(self, *args, **kwargs):
        """Sets the program name to the command invoked by dk, if needed"""
        if len(sys.argv) > 1:
            argparse.ArgumentParser.__init__(self, prog=sys.argv[1], *args, **kwargs)
        else:
            argparse.ArgumentParser.__init__(self, *args, **kwargs)

    def error(self, message):
        """Raises an exception instead of exit
```

### Additional info

- pdoc version: pdoc3 0.8.4

See picture for the output of the pdoc3.

![Screenshot_20200806_134627](https://user-images.githubusercontent.com/78939/89585947-3b46bf00-d7eb-11ea-8896-746ee572d7bd.png)

**Comment by jkugler** [comment]
Never mind. Found this: https://pdoc3.github.io/pdoc/doc/pdoc/#what-objects-are-documented&gsc.tab=0

I never considered `__init__ ` to be a private method, I guess. :)

**Comment by kernc** [comment]
`__init__` is special-cased since https://github.com/pdoc3/pdoc/issues/24.
