### ISSUE TITLE
Treat __init__ differently than other methods

### ISSUE THREAD

**Issue by b52** [pdoc3/pdoc#24]
I use Google's docstring style by documenting `Class.__init__(self)` methods in the `Class` docstring. Which means, I always have an `__init__` method rendered without any documentation but the parameters and the default values. On the flip side, I have a large `Class` docstring rendered which contains explanations for all these parameters. Basically, everything is split up.

What about an option to tackle this case including proper output?

[For example](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.HuberRegressor.html#sklearn.linear_model.HuberRegressor), the one from `sklearn` where the `__init__` signature is included in the `Class`:
![image](https://user-images.githubusercontent.com/23704/52360702-ec289e00-2a3c-11e9-93a0-82159c14ee39.png)

**Comment by kernc** [comment]
So pdoc currently shows `HuberRegressor` as:
![screenshot_2019-02-06_23-20-32](https://user-images.githubusercontent.com/684364/52377730-07f46a00-2a66-11e9-95b5-7501956b89d0.png)

How exactly would you prefer it?

**Comment by b52** [comment]
I, personally, prefer to illustrate how you call the class, i.e., join the `__init__` documentation and the `Class` documentation, given a lower importance to the inheritance.

Trying to sketch it, I would make it look like this:
```
class MyAwesomeClass(param_a, param_b=3):
    inherits: Mixin1, Mixin2 (I would visually reduce the importance of this line)
  
  My class is the freakin' BEST!

  Parameters:
    param_a : Just a param
    param_b : Another one pew pew

  Attributes:
    ...
```

Additionally, I think the attributes documentation section should be placed in Instance variables if I'm not mistaken.

**Comment by kernc** [comment]
This looks particular and specific. :grimacing: **Classes shown as callable in stead of their \_\_inits\_\_** can be easily achieved by overriding _html.mako_ with a [custom template](https://pdoc3.github.io/pdoc/doc/pdoc/#custom-templates). The API is pretty stable at this point. I'm certainly :-1: a command-line switch. Perhaps a [_config.mako_ tunable](https://numpydoc.readthedocs.io/en/latest/format.html#class-docstring).

**Listing Attributes as Instance variables** would be trickier and would require manipulating the docstring and the Class object sooner in the pipeline. Numpydoc defines Attributes too, so I guess Attributes should _always_ be listed as instance variables? But if one is documenting attributes in this way and not, say, pdoc-supported [PEP-224](https://www.python.org/dev/peps/pep-0224/) way, then they won't even have an _Instance variables_ section (they'll just have their Attributes section)?

Pdoc already **lists inherited identifiers from ancestor Class objects** it knows about (i.e. those that are defined within Modules that are being documented).
![screenshot_2019-02-07_00-57-05](https://user-images.githubusercontent.com/684364/52381998-e8fcd480-2a73-11e9-8cd7-5b1251c8f9b5.png)
It doesn't list identifiers from other projects or builtins. Doing so might require substantial refactoring. The rust traits link points to rust stdlib documentation. Run pdoc on CPython/Lib and you will get the same full inherited lists (hypothetically; not having my hopes up :grinning:).

**Comment by b52** [comment]
Concerning the first point. What about changing the default template? Obviously this is a very subjective thing, but I personally think showing classes as callable makes sense, since this is the way you would write out the code when using this class. Thus I think it would make sense to adapt the default style into this direction. What is your opinion on this?
(I was thinking that pdoc3 might become something like PEP8 for style, in the sense that you do not have to fiddle with  the details to much but get a consistent and uniform output, i.e., not a Sphinx where I have to tweak every little but, more like `rustdoc` for Python)

Concerning the second paragraph. Just for clarification, I assume that attributes is a synonym for instance variable. Thus I think these two things should be placed in the same doc output, whether I like to place docstring next to the variables or in the class documentation in an 'Attributes' section.

For the last part, I did not know that. What about making a bit more direct by including a way to see the actual documentation right in that very place, maybe initially hidden by a collapsible element?

**Comment by kernc** [comment]
> What about changing the default template?

And Sphinx also does it this way. Good, I agree. This way, we can rid us of \_\_init\_\_ as the only method prefixed with an underscore. PR welcome.

Don't know about something like PEP8 for style (:sweat_smile:), but following the conventions and serving the 95% use case certainly is the idea.

**Comment by kernc** [comment]
Re Attributes listed as Instance variables, it is the same. But no one in their right mind uses both ways (intermixed) to document their class' members, so they will only ever end up with one of the two subsections. Attributes are technically Instance variables and we could parse them out and then attach them as `pdoc.Variable` objects as is done currently ..., but we are not a type checker to be forcing that assertion, and it seems a lot of work. If you find you can solve it in an elegant manner, certainly welcome.

**Comment by kernc** [comment]
> What about making a bit more direct by including a way to see the actual documentation right in that very place

Currently, there is _config.mako_ flag which you can tune:
https://github.com/pdoc3/pdoc/blob/371a83944955f9880022d84130034db1af7559bf/pdoc/templates/config.mako#L4
and which is then passed to `pdoc.Class` methods:
https://github.com/pdoc3/pdoc/blob/371a83944955f9880022d84130034db1af7559bf/pdoc/templates/html.mako#L169-L172

This also lists inherited members, but they are dimmed (greyed out).
Improvements welcome. :+1:

**Comment by kernc** [comment]
@b52 Are you still interested in this (callable class instead of separate \_\_init\_\_) and enough to give it a shot? It'd be a good thing to have in the next release. :grin:

**Comment by b52** [comment]
@kernc Definitely, I was just occupied with finalizing a paper, but I might have a few hours this week, at latest the upcoming weekend.

**Comment by b52** [comment]
@kernc Got some pointers where to start for doing the `__init__` thing?

**Comment by kernc** [comment]
I think maybe with a test containing a class with the two docstrings, expecting them joined? I guess most changes, shouldn't be a lot, really, would be in `pdoc.Class`.

**Comment by kernc** [comment]
A little bit ad-hoc but seems to work. @b52, welcome to test current master on your project.

**Comment by b52** [comment]
@kernc Looks very good! I think it solves the problem nicely.
