### ISSUE TITLE
AttributeError: module 'pdoc' has no attribute '__version__'

### ISSUE THREAD

**Issue by Double-Felix** [pdoc3/pdoc#241]
### Expected Behavior
`pdoc --html modulename` should generate documentation for the module. Running any command returns this error (including `pdoc --help`).

### Actual Behavior
It returns an attribute error
```
Traceback (most recent call last):
  File "d:\python\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Python\Scripts\pdoc.exe\__main__.py", line 4, in <module>
  File "d:\python\lib\site-packages\pdoc\cli.py", line 27, in <module>
    '--version', action='version', version='%(prog)s ' + pdoc.__version__)
AttributeError: module 'pdoc' has no attribute '__version__'
```

### Additional info

- pdoc version: 0.8.4

**Comment by kernc** [comment]
Interesting. How was it installed? On what Python version? 

The attribute should, in fact, be available?
https://github.com/pdoc3/pdoc/blob/cd84fb3b0c512a203742cfdfaa26ba6fb0e535aa/pdoc/__init__.py#L35-L38

**Comment by Double-Felix** [comment]
> Interesting. How was it installed? On what Python version?
> 
> The attribute should, in fact, be available?
> https://github.com/pdoc3/pdoc/blob/cd84fb3b0c512a203742cfdfaa26ba6fb0e535aa/pdoc/__init__.py#L35-L38

I installed it with `pip install pdoc3` and I'm on Python 3.8

**Comment by kernc** [comment]
Well, that's very curious. Is _D:\Python\Scripts\pdoc.exe\\\_\_main\_\_.py_ possibly a real file? What does it contain? If it's something like:

https://github.com/pdoc3/pdoc/blob/cd84fb3b0c512a203742cfdfaa26ba6fb0e535aa/pdoc/__main__.py#L1-L6

module `pdoc` with any of its `__version__` should be loaded by the time of `main()`. :thinking:

Is your `pip --version` pip3 on the same Python3 environment?

Since you're able to reproduce it, if you know any Python, welcome to investigate! :smiley:

**Comment by Double-Felix** [comment]
Sorry for the late reply. pip version is 20.1. And the only `__main__.py` file I can find in relation to `pdoc` is in `D:\Python\Lib\site-packages\pdoc\__main__.py`

**Comment by kernc** [comment]
Was the trailing `_` possibly intentional? The file should be `_version.py`.
https://github.com/pdoc3/pdoc/blob/cd84fb3b0c512a203742cfdfaa26ba6fb0e535aa/pdoc/__init__.py#L36
```bash
$ cat venv/lib/python3.7/site-packages/pdoc/_version.py

# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
version = '0.8.4'
```

**Comment by Double-Felix** [comment]
It seems re-installing it fixed the issue. Documentation properly generates now. Thanks for all your help.

**Comment by kernc** [comment]
Ah, thanks for reporting back. A definite duplicate of https://github.com/pdoc3/pdoc/issues/131 then. :sweat_smile:
