### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by rajvijay68** [pdoc3/pdoc#244]
### Expected Behavior

Ignore imports from other files

Since this involves just static analysis of the files, does it actually need to import? Can it ignore in case a module is not found?

### Actual Behavior

It tries to import files. Say I want to generate docs for a standalone script, which might import from other scripts.

### Steps to Reproduce

1. pdoc --html myfile.py
2.
3.

### Additional info
- pdoc version:
```
% pdoc --version
pdoc 0.8.4
```

**Comment by kernc** [comment]
> I want to generate docs for a standalone script, which might import from other scripts.

Yeah, those scripts need to be available to import for documenting the module. Pdoc currently [imports](https://pdoc3.github.io/pdoc/doc/pdoc/#fn:execution).

There is:
```bash
$ pdoc --help
...
  --skip-errors         Upon unimportable modules, warn instead of raising.
```
Does that work for you?

**Comment by rajvijay68** [comment]
Thank you, that is super useful!
