### ISSUE TITLE
Warning when running pdoc

### ISSUE THREAD

**Issue by bje-** [pdoc3/pdoc#247]
When running `pdoc3`, I see:

```
/home/bje/.local/lib/python3.8/site-packages/matplotlib/backends/backend_gtk3.py:40: DeprecationWarning: Gdk.Cursor.new is deprecated
  cursors.MOVE:          Gdk.Cursor.new(Gdk.CursorType.FLEUR),
```

### Expected Behavior

No warning.

### Actual Behavior

I see a warning.

### Steps to Reproduce

1. Install `pdoc3` 0.9.1 with pip.
2. Run `pdoc --html <module>`

### Additional info

- pdoc version:
pdoc3 0.9.1

**Comment by kernc** [comment]
Pdoc [imports the modules it documents](https://pdoc3.github.io/pdoc/doc/pdoc/#fn:execution).

Somewhere along the way, matplotlib is imported and its GTK3 backend includes the deprecated code. The warning is not related to pdoc nor is it particularly alarming.

You can run pdoc with [`PYTHONWARNINGS`](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONWARNINGS) environment variable set, i.e.:
```bash
export PYTHONWARNINGS="ignore,default:::mymodule[.*]"  # ignore warnings, except in "mymodule" and its subpackages
```

**Comment by bje-** [comment]
How does pdoc decide which modules to import? My own code doesn't produce this warning at runtime, so just trying to track it down. Thanks.

**Comment by kernc** [comment]
It imports just the modules you pass on the command line:
https://github.com/pdoc3/pdoc/blob/6cfbc4fa0f09de79c51aedb435707a4dcd3b01b9/pdoc/cli.py#L537-L539
and all their submodules, recursively:
https://github.com/pdoc3/pdoc/blob/6cfbc4fa0f09de79c51aedb435707a4dcd3b01b9/pdoc/__init__.py#L664
`DeprecationWarning` is "[ignored by default](https://docs.python.org/3/library/warnings.html#the-warnings-filter), unless triggered by code in `__main__`".

"Your own code" either doesn't import everything like pdoc does or the warning is somehow hidden. In the latter case, try force it:
```bash
$ PYTHONWARNINGS="error::DeprecationWarning" python my_own_code.py
```

**Comment by bje-** [comment]
Turns out matplotlib has not supported the Gtk backend for a long time. Somehow, an aspect of my matplotlib installation regressed and I lost the backend setup I have been using for years. Thanks!
