### ISSUE TITLE
__init__ with @overload prevents pdoc from documenting instance variables

### ISSUE THREAD

**Issue by nosewings** [pdoc3/pdoc#248]
### Expected Behavior

If a class `@overload`s its `__init__` method, variable docstrings should be taken from the implementation.

### Actual Behavior

Docstrings are taken from the first `@overload`, not the implementation.

### Steps to Reproduce

Minimal example:

    from typing import Union, Literal, overload

    class Example:
        @overload
        def __init__(self, typ: Literal["str"], x: str):
            pass

        @overload
        def __init__(self, typ: Literal["int"], x: int):
            pass

        def __init__(self, typ: Union[Literal["str"], Literal["int"]], x: Union[str, int]):
            self.x = x
            """
            Value provided in the constructor.
            """

### Additional info

Currently, one can work around this limitation by putting the docstring in the first `@overload`ed version; e.g.:

    class Example:
        @overload
        def __init__(self, typ: Literal["str"], x: str):
            self.x = x
            """
            Value provided in the constructor.
            """

        @overload
        def __init__(self, typ: Literal["int"], x: int):
            pass

        def __init__(self, typ: Union[Literal["str"], Literal["int"]], x: Union[str, int]):
            self.x = x

However, this is less than ideal.

- pdoc version: 0.8.1

**Comment by kernc** [comment]
We parse documented instance variables from the class ASTs. We look into the _first_ defined method named `__init__`:
https://github.com/pdoc3/pdoc/blob/6cfbc4fa0f09de79c51aedb435707a4dcd3b01b9/pdoc/__init__.py#L252-L268

Perhaps we should be taking the _last_?

Or the one with an empty `.decorator_list`?

Or merge documented variables from all of them? :thinking:

Thoughts / PR welcome.

**Comment by nosewings** [comment]
Seems simplest to just take the last one. (Surely `__init__` can be decorated some other way?)

**Comment by nosewings** [comment]
Actually, in the future, what I'd want most is the ability to take docstrings from class-level typed variable declarations.

I find it strange that this doesn't already happen, since a statement `x: int` at the class level should become an assignment to `None` in the AST. I'll look in to that.

This PR should still be good right now, at least.

**Comment by kernc** [comment]
> a statement `x: int` at the class level should become an assignment to `None`

If you mean something like:
```py
>>> class A:
...    a: int

>>> assert A.a is None
AttributeError: type object 'A' has no attribute 'a'

>>> A.__annotations__
{'a': int}
```

the implicit assignment is _not_ the case.


> what I'd want most is the ability to take docstrings from class-level typed variable declarations.

That should already work?

https://github.com/pdoc3/pdoc/blob/6cfbc4fa0f09de79c51aedb435707a4dcd3b01b9/pdoc/test/__init__.py#L895-L897

**Comment by nosewings** [comment]
Sure, but

```python
>>> x = "class A: a: int"
>>> import ast
>>> ast.parse(x).body[0].body[0]
<_ast.AnnAssign at ...>
```

But I see now that pdoc doesn't look for those.
