### ISSUE TITLE
lunr search not found for nested folders package

### ISSUE THREAD

**Issue by y0m1g** [pdoc3/pdoc#250]
### Expected Behavior

Search displays actual results

### Actual Behavior

File not found (`search.html`)

### Steps to Reproduce

The sources of my package live under an extra folder, used as namespace ~~which is inherited from a previous dirty implementation~~, as such:
```
src/
  namespace/
    __init__.py
    package/
      app.py   
  setup.py
```

Because of that, the docs generated using:
```
pdoc3 'namespace.package' --html --force -o docs/ --config 'lunr_search={"fuzziness": 1}'
```

look like:
```
docs/
  namespace/
    package/
      app.html
      index.js
      index.html
      search.html
```

Opening `index.html` in a browser and searching for a keyword, the console reports an error looking for the resource file `docs/namespace/search.html` (instead of `docs/namespace/package/search.html`).

### Additional info

- Moving `index.js` and `search.html` to `docs/namespace/` fixes the issue and displays the search results properly.

- Not sure what would be better between editing this line:
https://github.com/pdoc3/pdoc/blob/d369b88297b19a78cf8373574ccecceeaea9931a/pdoc/templates/_lunr_search.inc.mako#L39
and change `pdoc`'s behaviour so that `search.html` and `index.js` are generated under `docs/` while keeping the other doc files under `docs/namespace/package/`...

- pdoc version: 0.9.1

**Comment by y0m1g** [comment]
BTW thanks for the great job integrating `lunr`, @davfsa! 🙂

**Comment by kernc** [comment]
@y0m1g Can't you just: `pdoc3 namespace ...`?

**Comment by y0m1g** [comment]
@kernc you're right, that makes it work!

I get `index.html`, `index.js` and `search.html` created under `docs/namespace`, and the rest of the doc under `docs/namespace/package`.

However, now I'm facing a different problem: as I have several other packages using the same structure (in different repos), I'll have to somehow merge together the different versions of `index.html`, `index.js` and `search.html` files that are created for each one of my packages.
Also, as certain package import others, let's say a `core_package` imported in both `package1` and `package2`, the doc generated for these 2 packages now include the doc for `core_package` as well... That's why I was using `pdoc3 namespace.package ...` in the first place, for a better separation of concerns.
But I agree this architecture problem is not directly related to `pdoc`... but I thought that it could be valuable to share.

**Comment by kernc** [comment]
Sure is. Might as well be buggy paths computation to look into.

But can't you _install_ all the distinct project packages (i.e. `namespace.project1`, `namespace.project2`, ...) and _then_ do: `cd ~; pdoc3 namespace ...`? That should pick your installed namespace, which contains all your subprojects, resulting in a single search/index ...

**Comment by y0m1g** [comment]
I wish I could do that!
Be for the moment not every package can be installed in the same environment as others, either because of dependencies conflicts, or because 1 is still not compatible with Python 3 (because of a dependency stuck to 2.7)...

So what I'm doing is having each repo generate its own doc, and then upload them onto a S3 bucket with static website hosting enabled, under different folders.
But I do have a main index page listing all folders to maintain so we can access all docs from one place; I suppose (manually) maintaining this file or (manually) merging pdoc's generated files in the namespace root is more or less the same kind of hassle in the end.

**Comment by davfsa** [comment]
> BTW thanks for the great job integrating `lunr`, @davfsa! slightly_smiling_face

No problem, glad I could help. This looks like an issue I have actually tried to tackle several times, but I think I might have found a fix for this. Im going to test it out and will open a pr if it works

**Comment by kernc** [comment]
Found another (better) way: outputting search parts directly into `args.output_dir`. :+1:
