### ISSUE TITLE
pdoc output as markdown

### ISSUE THREAD

**Issue by ptyshevs** [pdoc3/pdoc#257]
### Expected Behavior

Instead of output as `--pdf` or `--html`, I'm looking to output same *.html's  as *.md.

### Actual Behavior

The only option I see is to create custom post-processing script to rename all files under `html/<package_name>` directory.

- pdoc version: 0.9.1

**Comment by kernc** [comment]
If you pass neither `--html` nor `--pdf` switch, you get pure Markdown(Extra) output (_text.mako_ template). If you add additionally `-o` flag, you get it written as a bunch of \*.md files:
```bash
pdoc --output-dir=docs my_modules ...
```

**Comment by ptyshevs** [comment]
Thanks for your response. It turns out if you don't specify `--output-dir=<something>`, it actually doesn't create anything.

**Comment by kernc** [comment]
Indeed, without `-o` flag, the generated markdown is merely printed to standard output (a legacy behavior).

If you feel the documentation is lacking, improvements welcome.
