### ISSUE TITLE
normal text after single-backtick linked reference rendered/recognized as code

### ISSUE THREAD

**Issue by zmoon** [pdoc3/pdoc#260]
I may just be doing something wrong though...

### Actual Behavior

![pdoc_bug1](https://user-images.githubusercontent.com/15079414/93109040-8cb35b00-f681-11ea-9a4c-eec9a27bdb2d.png)

Stuff on following lines gets recognized as code too.

If I don't include the comma, it breaks the page layout.

### Steps to Reproduce

![pdoc_bug2](https://user-images.githubusercontent.com/15079414/93109049-8f15b500-f681-11ea-88b4-44434ceba22b.png)

### Additional info

- pdoc version: 0.9.1

**Comment by kernc** [comment]
The 'See Also' section is special-cased:
https://github.com/pdoc3/pdoc/blob/39a1e73241584e6f754edd69cab6e1cc5008a158/pdoc/html_helpers.py#L188-L191
to follow the [numpydoc convention (§12)](https://numpydoc.readthedocs.io/en/latest/format.html#sections):
```text
See Also
--------
increment: same but sans type annotations
```
See also: https://github.com/numpy/numpydoc/issues/170.

**Comment by zmoon** [comment]
Ah, I see, thanks!
