### ISSUE TITLE
Generate docs for jupyter notebooks?

### ISSUE THREAD

**Issue by csinva** [pdoc3/pdoc#262]
Wonderful package! Is there any planned support for jupyter notebooks? Would be really nice to have documentation that automatically extracts the markdown pieces of jupyter notebooks, especially for documenting data-science projects.

**Comment by kernc** [comment]
How would you expect that to work?

Notebooks are not really Python modules, and they have a suite of conversion-to-HTML tools already built around them. E.g. see [`jupyter nbconvert`](https://nbconvert.readthedocs.io/en/latest/usage.html). Another option would be [`jupytext --to py`](https://github.com/mwouts/jupytext#command-line-conversion) and then pdoc on _that_. :thinking:
I use both of those tools successfully [in another project](https://kernc.github.io/backtesting.py/doc/backtesting/#tutorials).

**Comment by csinva** [comment]
Thanks for the quick reply! Those are some very good pointers - they likely are sufficient for general use-cases. Feel free to close 😄 . 

What I had envisioned was something that would treat a folder of notebooks similar to a module. Very common practice in data-science projects is to have a `src` module of useful functions and a folder of notebooks which do analysis using the `src` module (e.g. see the standard cookiecutter-data-science template).

In most data-science projects I have seen, the `notebooks` folder quickly accumulates a large number of notebooks and it is difficult to tell what each does / how they are related without opening each notebook one-by-one. Thus it would be extremely useful to auto-generate a documentation-outline of all the notebooks in the folder based on their markdown cells! But maybe this is beyond the scope of this project...

Thanks again!

**Comment by kernc** [comment]
I believe `jupytext --to py notebooks`, followed by `pdoc --template-dir custom-templates notebooks` might fit your use case. In _./_[_custom-templates_](https://pdoc3.github.io/pdoc/doc/pdoc/#custom-templates), you create _text.mako_ with the following contents:
```
<% from pdoc.html_helpers import extract_toc %>
${extract_toc(module.docstring)}
```
(A slight documentation bug there if you notice. :sweat_smile:)
