### ISSUE TITLE
Numpydoc "Examples" section formatting

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [pdoc3/pdoc#263]
### Expected Behavior

Numpy have the section "Examples" which shows how to use the code. I would be nice to show this in the same way as parameters and returns.

### Actual Behavior

Right now it is stripped from the docstring so if using the following the "Examples" is not shown in the genreated HTML.

```
def my_func(
    server: str,
) -> sqlalchemy.engine.Engine:
    """
    Convenience function for generating SQLAlchemy Engine. 

    Parameters
    ----------
    server : str
        Name or IP address of the server. 

    Returns
    -------
    sqlalchemy.engine.Engine

    Examples
    -------
    >>> mymodule .sql import my_func
    """
```

### Steps to Reproduce

1. Copy the docstring
2. Run pdoc --html mymodule

### Additional info

- pdoc version: 0.9.1

**Comment by kernc** [comment]
What do you mean stripped away? :astonished: This works for me.

![Screenshot_2020-09-22 foo API documentation](https://user-images.githubusercontent.com/684364/93900831-23bd8a00-fcf6-11ea-8fcf-22144fb5142f.png)

**Comment by thomasfrederikhoeck** [comment]
Okay, it was not stripped away (but more temporarily hidden). 😃  If I'm using `--http` and the function is in the `__all__` for the module it is not updated (even when I hit F5) when I change the docstring. It only happens if it is "lifted a level up" with `__all__ `an to if to go to the file where the function is defined.

**Comment by kernc** [comment]
> It only happens if it is "lifted a level up" with `__all__ `an to if to go to the file where the function is defined.

I don't think I comprehend.

Can you maybe open a new issue with a minimal reproducible example? IIUC, it's not the Examples section in particular, but a stale docstring in general? Must be some caching issue ... :thinking:

**Comment by thomasfrederikhoeck** [comment]
Will do tomoz.
