### ISSUE TITLE
how to add a getting started quide

### ISSUE THREAD

**Issue by koaning** [pdoc3/pdoc#27]
hi all, 

i really love the new view of pdoc3 and i'd love to upgrade, but i was wondering how it might be possible to add things like a "getting started guide" to the documentation page. at the moment i love how all the docstrings are properly converted into documentation but i can't find out how to add things like "examples" or "caveat" pages to my documentation. is this possible with pdoc3? 

either way, thanks for making this!

**Comment by koaning** [comment]
it seems like all these things can be added to `pdoc` but not at separate pages. is this correct?

**Comment by kernc** [comment]
To add prose documentation (getting started, examples, caveats, ...), write _module docstrings_. Documentation hierarchy follows module hierarchy. See https://github.com/pdoc3/pdoc/blob/c423762573b227e0025d670b58137fb7aa57498d/pdoc/__init__.py#L1-L343

To write new, separate pages, you would have to introduce new, separate modules. E.g. _examples.py_:
```py
"""
Just some examples for illustration purposes. No code.

...
"""
```

**Comment by kernc** [comment]
Since https://github.com/pdoc3/pdoc/pull/16 (will be featured in 0.6.0), you can also use `.. incldude::` directive to include e.g. an external example .py file.

**Comment by koaning** [comment]
Is this documented anywhere?

**Comment by kernc** [comment]
Currently, just here:
https://github.com/pdoc3/pdoc/blob/bb59d806504962664ab34bb450a8cbcbc6292e51/pdoc/__init__.py#L183-L211
Will become part of hosted documentation once the version containing it is released.
