### ISSUE TITLE
Render the type annotations (and docstring?) of each overload

### ISSUE THREAD

**Issue by catern** [pdoc3/pdoc#275]
### Expected Behavior

When using typing.overload, an overloaded function should show the type annotation, and maybe the docstring, of each function that's part of the overload. 

Maybe by rendering the function as several functions? That's what Sphinx does, see for example the test for Sphinx added in https://github.com/sphinx-doc/sphinx/commit/fb2f777079506a6ed36077ae98c2b267d25b16b5 

### Actual Behavior

Only the type annotation and docstring of the implementation function is shown; since often the implementation function has a substantially more complicated type annotation, or even no annotation at all, this results in worse docs.

### Steps to Reproduce

Stealing the example from https://github.com/sphinx-doc/sphinx/issues/7787

```
@overload
def my_bytes(n: int):
    """ construct an empty array of n bytes """

@overload
def my_bytes(s: bytes):
    """ copy an existing bytes-like object """

def my_bytes(b):
    """ Some common docstring """
    return bytes(b)
```

This should render something with the type annotations over the overload, but instead renders with no type annotations.

### Additional info

- pdoc version: 0.9.1

**Comment by kernc** [comment]
Unfortunately, [pdoc _executes_ documented modules](https://pdoc3.github.io/pdoc/doc/pdoc/#fn:execution). For your example above, this means every subsequent `my_bytes()` definition overwrites the previous one, and only the last one is visible on a _live_ module object.

Until such time as pdoc becomes purely AST-based (interested?), I'm afraid this is a cantfix. :disappointed:

**Comment by USSX-Hares** [comment]
@kernc if I'll prepare a PR for that, would you include it?

**Comment by USSX-Hares** [comment]
Starting from 3.11, we have `typing.get_overloads()` (https://docs.python.org/3/library/typing.html#typing.get_overloads), which might be a reason to reopen this feature request.
