### ISSUE TITLE
Numpydoc "References" don't link properly

### ISSUE THREAD

**Issue by cory-kinney** [pdoc3/pdoc#280]
### Expected Behavior

[Numpydoc section 14](https://numpydoc.readthedocs.io/en/latest/format.html) provides the following syntax for creating a reference inside a **References** section
```rst
.. [1] O. McNoleg, "The integration of GIS, remote sensing,
   expert systems and adaptive co-kriging for environmental habitat
   modelling of the Highland Haggis using object-oriented, fuzzy-logic
   and neural-network techniques," Computers & Geosciences, vol. 22,
   pp. 585-588, 1996.
```
that can be linked in a **Notes** section with the following syntax `[1]_`.

### Actual Behavior

The reference displays as raw strings with no link.

### Additional info

pdoc version: 0.9.1

This is my first time submitting an issue on GitHub and today is my first day using Numpydoc/pdoc, so if I'm doing something wrong just let me know!

**Comment by kernc** [comment]
Congratz, your first issue is exemplary! :grin: 


> Numpydoc section 14 provides the following syntax for creating references

This is really a [reStructuredText syntax for anchors/links](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#hyperlink-targets). Works outside Numpydoc sections just as well, provided the underlying style/format is reStructuredText ...

In pdoc, however, the underlying syntax is [Markdown](https://pdoc3.github.io/pdoc/doc/pdoc/#supported-docstring-formats), and various Googledoc/Numpydoc (+some reST) particularities are just mocked for by way of simple transformations into markdown. Support for raw reST is just being worked on in https://github.com/pdoc3/pdoc/pull/274.

Therefore, I suggest you use [markdown footnotes](https://python-markdown.github.io/extensions/footnotes/), or wait for whatever we come up with in https://github.com/pdoc3/pdoc/pull/274.
