### ISSUE TITLE
Docstrings for variables from doc-comments above

### ISSUE THREAD

**Issue by csm10495** [pdoc3/pdoc#289]
I see that 

```
module_variable = 1
"""Docstring for module_variable."""
```

works for giving the module_variable a docstring.

Is there anyway that something like this could also (or optionally) be supported: 

```
# Docstring for module_variable.
module_variable = 1
```

It seems rather rare for a docstring to follow after a variable declaration; for me it's much more commonly in front of the declaration. It also is more common to be of the single line-comment (via #) variety. 

Similar ask for class variable docstrings as well.

**Comment by kernc** [comment]
This is from [PEP 224](https://www.python.org/dev/peps/pep-0224/). The proposal was officially rejected, but [software projects do use it](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#directive-autodata).
Python AST parsing, [which we rely on](https://github.com/pdoc3/pdoc/blob/bec63077a03b2136e6982825d327073ed76cc20a/pdoc/__init__.py#L243-L245), only supports [_typing_ comments](https://docs.python.org/3/library/ast.html#ast.PyCF_TYPE_COMMENTS) (since 3.8).

Welcome to investigate how Sphinx fetches:
```py
#: doc comment from a previous line
variable = 1
```

**Comment by csm10495** [comment]
@kernc , would you consider a PR that adds this capability? I have a version on my local copy that seems to work. Right now that's via adding some logic to `_pep224_docstrings()` to look above a declaration for a single-line docstring on the same indent level after an actual pep224 definition can't be found.

This code is more/less shoved into that function before return:
```
    for assign_node in ast.iter_child_nodes(tree):
        if not isinstance(assign_node, ast_Assignments):
            continue

        if isinstance(assign_node, ast.Assign) and len(assign_node.targets) == 1:
            target = assign_node.targets[0]
        elif isinstance(assign_node, ast_AnnAssign):
            target = assign_node.target
            # Skip the annotation. PEP 526 says:
            # > Putting the instance variable annotations together in the class
            # > makes it easier to find them, and helps a first-time reader of the code.
        else:
            continue

        if not _init_tree and isinstance(target, ast.Name):
            name = target.id
        elif (_init_tree and
              isinstance(target, ast.Attribute) and
              isinstance(target.value, ast.Name) and
              target.value.id == 'self'):
            name = target.attr
        else:
            continue

        if name not in vars:
            # Check if there is a single-line comment indented to the same level just above this
            docstring_lineno = assign_node.lineno - 2
            assign_node_lineno = assign_node.lineno - 1
            if docstring_lineno >= 0:
                source_lines = doc_obj.source.splitlines()
                possible_docstring = source_lines[docstring_lineno].replace('\t', '    ')
                assignment_line = source_lines[assign_node_lineno].replace('\t', '    ')
                if len(assignment_line) - len(assignment_line.lstrip(' ')) == len(possible_docstring) - len(possible_docstring.lstrip(' ')):
                    # Indentation matches
                    stripped = possible_docstring.lstrip(' ')
                    if stripped.startswith('#'):
                        docstring = stripped.split('#', 1)[1].strip()
                        vars[name] = docstring
```

Now this is likely more copy-paste than desired. Any thoughts?

**Comment by kernc** [comment]
Sure, would be a great addition. But is this how Sphinx does it? Sphinx since v1.1 [also supports](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#directive-autodata) doc-comments trailing on the same line, i.e.:
```py
CONST = 1  #: The CONST constant's docstring
```
If one, I'd like the other too. Note, _doc_-comments — startswith `#:`.

Have you found it in their source?

**Comment by csm10495** [comment]
I think it's around line 380 in https://www.github.com/sphinx-doc/sphinx/tree/3.x/sphinx%2Fpycode%2Fparser.py

I don't think we should enforce needing a : after #. With some changes we could support multiline as well.

**Comment by kernc** [comment]
> I don't think we should enforce needing a : after #

There's no other way to go about it. Standards are for upholding. You might not want just every comment to export to public documentation.
