### ISSUE TITLE
There is a way to ignore a python file to build docs?

### ISSUE THREAD

**Issue by riibeirogabriel** [pdoc3/pdoc#293]

**Comment by kernc** [comment]
The way to skip a module from being processed by pdoc is to rename it so the filename begins with an underscore, or, alternatively, by putting its qualified name mapped to False in the [global `__pdoc__` dict](https://pdoc3.github.io/pdoc/doc/pdoc/#overriding-docstrings-with-__pdoc__).

**Comment by riibeirogabriel** [comment]
@kernc thanks! the undescore feature to hide file in a package is from python or pdoc?

**Comment by kernc** [comment]
Neither pdoc nor Python. Prefixing private/implementation-specific code with an underscore is a [common programming convention](https://pdoc3.github.io/pdoc/doc/pdoc/#fn:private), not only in Python but other languages as well.
