### ISSUE TITLE
 pdoc3 --version crashes for version 0.5.2

### ISSUE THREAD

**Issue by kwijk** [pdoc3/pdoc#30]
When I install pdoc3 0.5.2 via pip3 install pydoc3 on ubuntu 18.04 it installs ok, but running it gives the following error:

```
> pdoc3 --version
...
AttributeError: module 'pdoc' has no attribute '__version__'

```

The command works fine after installing pdoc 0.5.1

# expected behavior
No crash

# pdoc3 version
0.5.2

**Comment by kwijk** [comment]
I closed issue as I cannot anymore reproduce. I reinstalling pydoc3 0.52 and now it works...

**Comment by kernc** [comment]
Duplicate of https://github.com/pdoc3/pdoc/issues/131.
