### ISSUE TITLE
Use of Nazi symbols in the footer on the project website

### ISSUE THREAD

**Issue by Operator2024** [pdoc3/pdoc#310]
Hi people! I found Nazi symbols https://pdoc3.github.io/pdoc/ in the footer. Do you think this is normal? or is it just a typo
There's a screenshot - https://1drv.ms/u/s!AtV6DG59xKaXrlO49xdqCON6JGpC?e=KJv1FI

**Comment by kernc** [comment]
They're _not_ Nazi symbols, mind you. Rather, they are [_Buddhist_ symbols](https://en.wikipedia.org/wiki/Swastika#Buddhism). :sweat_smile: It's fairly easy to mistake the two, but I don't think the Unicode Consortium would ever agree to add [symbol characters](https://en.wikipedia.org/wiki/Swastika#Written_characters) that glorify Nazism.

**Comment by Operator2024** [comment]
Ok, sorry guys! I didn't think about the Unicode consortium ... maybe you're right

**Comment by cgobat** [comment]
The unfortunate fact of the matter is that when people see that symbol on the project's webpage, Buddhism is *not* going to be the first thing that comes to mind. The very same Wikipedia page you linked states

> it continues to be strongly associated with [Nazism](https://en.wikipedia.org/wiki/Nazism), [antisemitism](https://en.wikipedia.org/wiki/Antisemitism), [white supremacism](https://en.wikipedia.org/wiki/White_supremacy), or simply [evil](https://en.wikipedia.org/wiki/Evil)

I cannot imagine that this is a desirable impression to be giving to site visitors, especially given the lack of context or logical reason for why the symbol is there. @kernc, could you take a look at #424?
