### ISSUE TITLE
[Request] Tool for Dash docset generation

### ISSUE THREAD

**Issue by xilopaint** [pdoc3/pdoc#315]
Documentation sources built with Sphinx, PyDoctor and others have tools like [doc2dash](https://github.com/hynek/doc2dash) intended to generate Dash docsets. It would be nice to have something that could generate dash docsets out of pdoc docs.

I've tried to build a docset for [Backtesting.py](https://github.com/kernc/backtesting.py) with no success.

See this: https://kapeli.com/docsets

**Comment by kernc** [comment]
Seems like compatibility with Sphinx and PyDoctor is [a feature of doc2dash itself](https://doc2dash.readthedocs.io/en/stable/formats.html)? Not sure what to do about it here. :grimacing: 

Have you tried creating Dash docsets [from any HTML documentation](https://kapeli.com/docsets#dashDocset)?

**Comment by xilopaint** [comment]
> Seems like compatibility with Sphinx and PyDoctor is [a feature of doc2dash itself](https://doc2dash.readthedocs.io/en/stable/formats.html)?

Yes.

> Have you tried creating Dash docsets [from any HTML documentation](https://kapeli.com/docsets#dashDocset)?

I tried to do it using [Dashing](https://github.com/technosophos/dashing#readme) but it's hard and I gave up. doc2dash easily and efficiently creates docsets out of documentations built with Sphinx and do the mapping work between the elements of the docs and the [Dash entry types](https://kapeli.com/docsets#supportedentrytypes). With Dashing you have to do it manually.
