### ISSUE TITLE
--html works but --http doesn't

### ISSUE THREAD

**Issue by nicolaskruchten** [pdoc3/pdoc#33]
### Expected Behavior

Static and live generation should work the same way.

### Actual Behavior

In my project I can run `pdoc my_module --html` and it runs fine, generating HTML etc but while `pdoc my_module --http localhost:8080` starts the web server, the page fails to render with `ModuleNotFoundError: No module named 'my_module'`

### Steps to Reproduce

1. `git clone git@github.com:plotly/plotly_express.git` (maybe install some deps)
2. `pdoc plotly_express --html` vs `pdoc plotly_express --http localhost:8080`

**Comment by kernc** [comment]
After git clone, I ran `pip install -e .` in the plotly_express directory. Can't seem to reproduce the issue:
```text
$ pdoc plotly_express --http localhost:8080 
Starting pdoc server on localhost:8080
pdoc server ready at http://localhost:8080
127.0.0.1 - - [17/Feb/2019 16:33:30] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Feb/2019 16:33:32] "GET /plotly_express HTTP/1.1" 302 -
127.0.0.1 - - [17/Feb/2019 16:33:32] "GET /plotly_express/ HTTP/1.1" 200 -
127.0.0.1 - - [17/Feb/2019 16:33:42] "GET /plotly_express/colors/index.html HTTP/1.1" 302 -
127.0.0.1 - - [17/Feb/2019 16:33:42] "GET /plotly_express/colors/ HTTP/1.1" 200 -
127.0.0.1 - - [17/Feb/2019 16:33:50] "GET /plotly_express/colors/diverging.html HTTP/1.1" 200 -
```
If I don't install plotly_express, I get the following error:
```
Exception happened during processing of request from ('127.0.0.1', 46388)
Traceback (most recent call last):
  File "/home/user/pdoc/pdoc/__init__.py", line 540, in import_module
    module.__loader__.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/tmp/plotly_express/plotly_express/_px.py", line 5, in <module>
    from .colors.qualitative import Plotly as default_qualitative_seq
SystemError: Parent module 'plotly_express' not loaded, cannot perform relative import

```
But this is due to pdoc importing the documented module, plotly_express using relative imports, and Python not honoring relative imports from non-packages (i.e. filesystem paths).

**Comment by nicolaskruchten** [comment]
Right, I was trying this without installing locally. I guess this is just not a supported use case?

**Comment by kernc** [comment]
I see. The discrepancy between `--html` (which even without installing works) and `--http` was unintended. Looking into it.

**Comment by kernc** [comment]
It has to do with these lines
https://github.com/pdoc3/pdoc/blob/53544d87d6e0c23993a8ee440b7e46cf831136e6/pdoc/cli.py#L333-L334
I guess we can just move them a few lines up ...
