### ISSUE TITLE
Feature Request: Specify hljs Style

### ISSUE THREAD

**Issue by KyleKing** [pdoc3/pdoc#34]
For working with Highlight.js outside of Node, how do people typically import the CSS files? Do you download the file and import locally or are they hosted on an online CDN?

For the default template, would you consider setting the default style to one of `Foundation`, `Github Gist`, `Atom One Light`, or `A 11 Y Light` that provide better highlighting of variables and built-ins?

Try the hljs demo: https://highlightjs.org/static/demo/

**Comment by kernc** [comment]
Currently, to avoid bikeshedding, the default highlight style is "github", loaded from CDN:

https://github.com/pdoc3/pdoc/blob/24a561ceef1b96575e818504869abc0b5b44589d/pdoc/templates/html.mako#L352-L354

A [_config.mako_ tunable](https://github.com/pdoc3/pdoc/blob/24a561ceef1b96575e818504869abc0b5b44589d/pdoc/templates/config.mako) `highlight_style` (defaulting to `'github'`) would be reviewed favourably.

**Comment by KyleKing** [comment]
Up too early this morning and just couldn't get this commit right. I've only ever used `git push origin --force` on ` git --bare init` repositories, and probably won't use it on Github again 🐑
