### ISSUE TITLE
Default argument gets rendered evaluated instead of rendering unevaluated

### ISSUE THREAD

**Issue by germanium** [pdoc3/pdoc#359]
### Expected Behavior

```python
class MyClass:
    __init__(self, arg1=os.getenv("my_env_var")):
        """MyClass description

            arg1 (str): My arg1 description
        """
```

I would expect it to render

```python
class MyClass (arg1=os.getenv("my_env_var"))
```

### Actual Behavior

It actually renders it with the result of evaluating the default argument. 

```python
class MyClass (arg1=<actual env variable value>)
```

In this example this behavior can be very dangerous if the environment that builds the documentation has secrets in the environment variable `my_env_var`. 

### Additional info

- pdoc version: 0.9.1

**Comment by kernc** [comment]
Unlike `os.environ` itself and a few other singletons which we account for:
https://github.com/pdoc3/pdoc/blob/f358893e4fcfd7f29857a7ff5491b606ff146d39/pdoc/__init__.py#L1453-L1462
... `os.getenv('my_env_var')` is _evaluated_ before being assigned as `arg1` default.
```py
>>> import os; os.environ['my_env_var'] = 'this'
>>> def foo(*, arg1=os.environ['my_env_var']): pass
>>> foo.__kwdefaults__
{'arg1': 'this'}
```
So unfortunately, this is not possible. :disappointed:
