### ISSUE TITLE
Plain `http:` / `https:` links are formatted as reST/attributes and unclickable

### ISSUE THREAD

**Issue by KyleKing** [pdoc3/pdoc#37]
### Summary

Should pdoc handle plain links like `http://crummy.com/software/BeautifulSoup/` and format them as clickable links: [http://crummy.com/software/BeautifulSoup/](http://crummy.com/software/BeautifulSoup/)? Right now the colon is tricks pdoc into formatting the link as reST.

For example, in the BS4 docs generated by pdoc the link is split on the colon making it unclickable:

<img width="902" alt="screen shot 2019-02-24 at 05 57 18" src="https://user-images.githubusercontent.com/3784339/53298426-f1873600-37fb-11e9-9d56-a052b9c65014.png">

### Reproduce with:

1. `pip install beautifulsoup4`
1.  `pdoc3 bs4 --html`

**Comment by kernc** [comment]
The issue affects version 0.5.2 and was introduced in 7500791bef2ff61c4d8bab093b6e2b6ece446836.
