### ISSUE TITLE
Red Font for Text Inside Single and Double Quotes, Inside an Ordered List?

### ISSUE THREAD

**Issue by windowshopr** [pdoc3/pdoc#379]
I'm making some documentation on a genetic algorithm package that I've made, and I noticed that the text inside an ordered list:

1. Makes some words bold randomly
2. If preceded by a double or single quote, will turn the font red

Here is a snapshot of the output:

![image](https://user-images.githubusercontent.com/40477419/148633602-dee01fc1-dc17-46ff-890d-1d680e033f43.png)

And here is that same snippet of code:

![image](https://user-images.githubusercontent.com/40477419/148633626-e1aea5aa-664b-4e45-8d41-c928503b1515.png)

This is all within the very top """comment""" section of my source code. You'll notice I added the escape slash \ before each quote in the list in an effort to see if that would help, but I think it's a markdown/formatting thing, I'm just not sure how to fix it. The bolding thing seems weird too as I don't use ** around the words being bolded.

What can I do to fix this? Thanks!

**Comment by kernc** [comment]
The contents in question is obviously indented at least four spaces and thus [interpreted as a verbatim code block](https://www.markdownguide.org/basic-syntax/#code-blocks) which gets colored by HighlightJS (bold are keywords—curious what language was autodetected).

Your docstrings should render fine if you format them like so:
```py
def foo():
    """
    Paragraph introducing a list:

    1. Something something.
       Continuation indented 3-spaces to match list item start.
    2. Something else ...
       ...
    """
    ...
