### ISSUE TITLE
HTML Conversion issues

### ISSUE THREAD

**Issue by newbbbiieee** [pdoc3/pdoc#383]
Below is my sample code:

![image](https://user-images.githubusercontent.com/98737611/151767135-f6330a6d-3831-46d7-844e-24dc3a099da8.png)

**Output:**
When i used pdoc to see the documentation in text format, everything looks fine.
Command: pdoc sample.py
![image](https://user-images.githubusercontent.com/98737611/151766903-1e5d052c-6ef4-4fad-b1d0-3b25da92d1fa.png)

But when i try to generate the same in HTML format, xml elements are missing and also all the whitespaces are stripped out.
Command: pdoc --html sample.py
![image](https://user-images.githubusercontent.com/98737611/151767004-a16e2dd1-c110-4e94-979e-6c69645bedfe.png)

There is some basic concept im missing out here.. can you please let me know what im doing wrong...
(Expectation is to have the same text format reflected in my html output)

Note: im using pdoc version 0.10.0

**Comment by kernc** [comment]
See that "2"? If you use your [browser's inspector tool](https://www.google.com/search?q=browser+inspect+element), you'll see the surrounding XML is there. [Raw HTML (XML) is valid Markdown](https://daringfireball.net/projects/markdown/syntax#html), so pdoc leaves it intact. If you want your XML code to show as an example _code snippet_ in Markdown, either [indent the code block with 4 spaces](https://github.github.com/gfm/#indented-code-blocks) or (preferred) delimit it with [fences and a language infostring](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting).

Note, Markdown also has an extension [specification for formatting tables](https://www.markdownguide.org/extended-syntax/#tables).
