### ISSUE TITLE
Documentation shows unexpected ForwardRef(None) inside Union.

### ISSUE THREAD

**Issue by hhoppe** [pdoc3/pdoc#395]
Input:
```
from typing import Union

def test1_func(arg: Union[None, str, int]) -> None:
  return
```

Resulting documentation:
`def test1_func(arg: Union[ForwardRef(None), str, int]) ‑> None`

Expected documentation:
`def test1_func(arg: Union[None, str, int]) ‑> None`

!pdoc --version
pdoc 0.10.0

**Comment by hhoppe** [comment]
Actually, it would be even better (clearer and more concise) if this produced the Python 3.10 syntax:

`def test1_func(arg: str | int | None) ‑> None`

It seems that `pdoc` does so some of the time -- maybe only for `Optional[simple_type]`?

**Comment by hhoppe** [comment]
Maybe an option to output `int | float | None` rather than `Optional[int | float]`?
It seems to be the modern trend.

**Comment by kernc** [comment]
No options—sane defaults. Thanks!
