### ISSUE TITLE
Offensive quote on main documentation page could turn off potential users

### ISSUE THREAD

**Issue by wagenadl** [pdoc3/pdoc#397]
### Expected Behavior

Documentation should be welcoming to all.

### Actual Behavior

Quote about bad sex being better than none could easily be offensive or triggering to anyone who actually experienced bad sex.

### Steps to Reproduce

Just visit the website (https://pdoc3.github.io/pdoc/).

### Additional info

No offense intended. Just hoping to contribute to a more inclusive open source universe.

**Comment by okuboshigeo** [comment]
The pdoc3 maintainer had previously stated that he does not mind that it offends some people (#235). If you dislike that, maybe you want to check out [pdoc](https://pdoc.dev) or [Sphinx](https://www.sphinx-doc.org/).

**Comment by kernc** [comment]
Don't forget an even more revealing issue https://github.com/pdoc3/pdoc/issues/346.

Ideed, thanks for the feedback, but it is my sincere layman's view that people who get as easily and uncontrollably triggered by out-of-context quotes on the internet should, in fact, work on coping with their condition much harder. Everyone has experienced some "bad" sex, yet this doesn't change the fact, nor should it divert their disposition, that sex, _in general_, is good and natural and pleasant. Anyone can _choose_ to be offended by anything, and hoping to avoid it is a delusion I won't partake. Kindly take your war elsewhere.

**Comment by alexpirine** [comment]
@kernc I understand this is your (forked) project, but you should think of adapting it to the public or keeping it for yourself.

People just want a library to generate documentation, not to read sexual “jokes” or to have swastikas in their generated documentation with possible reference to nazism.

Whether you deny it or not, the association exists.

**Comment by kernc** [comment]
> swastikas in their generated documentation with possible reference to nazism

For the record, there are no swastikas (or jokes) in the generated docs other than those the user puts in herself!

**Comment by dirkroorda** [comment]
Cherishing diversity and inclusivity implies that one can enjoy the quality of somebody's work even when not agreeing with how the person expresses itself.
The world will become a very small place if we require to be perfectly comfortable with each other.
