### ISSUE TITLE
Continuation char in doctests lead to unsightly gaps in HTML generated documentation

### ISSUE THREAD

**Issue by bje-** [pdoc3/pdoc#406]
### Expected Behavior

Whitespace after the backslash should be ignored until the first non-whitespace character is encountered.

### Actual Behavior

Too much whitespace is shown in the generated documentation. See the first docstring for the [Battery](http://nemo.ozlabs.org/pdoc/generators.html) class, for example. Source code can be expanded from the top right of this page for reference.

### Additional info

- pdoc version: 0.10.0

**Comment by kernc** [comment]
> Whitespace after the backslash should be ignored until the first non-whitespace character is encountered.

I'm quite sure backslash is meant to cancel _only the first following newline_ character, not all whitespace. Compare:
```py
>>> '\
...              foo'

'             foo'
```
Have you tried marking your doctest/example like so:
```
>>> b = Battery(polygons.WILDCARD, 400, 2,
...             discharge_hours=hours, rte=1)
>>> b.stored = 400
```
?
