### ISSUE TITLE
Skip-errors not recogniazed

### ISSUE THREAD

**Issue by b7leung** [pdoc3/pdoc#409]
### Expected Behavior
Generating documentation.

### Actual Behavior
I get an error saying "error: option --skip-errors not recognized"

### Steps to Reproduce

1. ```pdoc --skip-errors --html .```

### Additional info

- pdoc version: 0.10.0

**Comment by kernc** [comment]
You're most likely invoking the other/wrong pdoc package. To fix it, try:
```bash
pip uninstall pdoc
pip install --force-reinstall pdoc3
```
