### ISSUE TITLE
search field wont appear in generated html file

### ISSUE THREAD

**Issue by bananisacte** [pdoc3/pdoc#412]
### Expected Behavior
when i generate a HTML file of my `.py` file in code with all the comments, i want to see "search" field on the left side above all the functions, i saw in the commits that the search was implanted

### Actual Behavior
generating the file using command will not show me the search field

### Steps to Reproduce

1. run the following command `pdoc --html .\main.py --output-dir docs --force`
2. open the main.html file from doc folder in webview from pycharm
3. under "INDEX" no search bar

### Additional info

- pdoc version: 0.10.0

**Comment by kernc** [comment]
Implemented, but not enabled by default. You have to tweak [relevant parts of _config.mako_](https://github.com/pdoc3/pdoc/blob/60f77d2e6c033f62be8a9351c863246e5f88b4a1/pdoc/templates/config.mako#L45-L56) and use `--template-dir` switch, or use switches like `--config "lunr_search={}"` or `--config "google_search_query='...'"`, with `...` replaced by your desired google query filter (see config example).
