### ISSUE TITLE
generating the whole project documentation with 1 command

### ISSUE THREAD

**Issue by bananisacte** [pdoc3/pdoc#413]
### Expected Behavior
ately i've started using pdoc3 to document my whole project, right now i have a problem generating a HTML that contain the whole project in 1 command, and not going every.py file one by one

the project structure is like this:
```
--pythonProject
    |  file_a.py
    |  file_b.py
    --folder
        |  file_c.py
        |  file_d.py
    --docs
```

### Actual Behavior
i tried the following command : `pdoc --html .\fila_a.py --output-dir docs  --force --config "lunr_search={}"` and it genetrates the following file in docs folder -> file_a.html
is there a way to generate 1 file for all the `.py` files i have in code?
also tried  `pdoc --html .\ --output-dir docs  --force --config "lunr_search={}"`
but getting an error for `pytest` library that not in my project at all
also tried pdoc --html pythonProject --output-dir docs  --force --config "lunr_search={}"
and it says that it cant find module `pythonProject`

### Steps to Reproduce

1. pdoc --html .\ --output-dir docs  --force --config "lunr_search={}"
2. return error for pytest library
3.

### Additional info

- pdoc version: 0.10.0

**Comment by bananisacte** [comment]
after digging a little bit further inside all the `issues` tab in this repo, i successfully found the missing peice of the puzzle :)

**Comment by ComanderKai77** [comment]
@bananisacte Would you mind sharing your solution?
