### ISSUE TITLE
Support search in docpage

### ISSUE THREAD

**Issue by tisonkun** [pdoc3/pdoc#415]
Currently, it seems the search support restricts into google search or lunr search that needs configured. Is it possible to provide in page search support like https://pulsar.apache.org/api/python/2.10.2/pulsar.html?

I'm going to migrate the page linked above to pdoc3 since pdoc3 has a better styled theme. But the searching function is significant to retain.

**Comment by kernc** [comment]
Lunr search should be [fairly easy to configure](https://github.com/pdoc3/pdoc/issues/412#issuecomment-1295015991), no? Adding a single command line switch (`--config "lunr_search={}"`) should do it ...

**Comment by tisonkun** [comment]
Resolved by hosting the files with a server instead of directly open the HTML files...
