### ISSUE TITLE
--skip-errors flag does not work

### ISSUE THREAD

**Issue by Nathan-Harlan** [pdoc3/pdoc#421]
### Expected Behavior
pdoc  test.py --skip-errors --html -f

Should generate an html doc and skip import errors

### Actual Behavior
Import Error is raised :ModuleNotFoundError, and html file is not created

### Steps to Reproduce

1. create a basic test.py script with an import at the top that cannot be found: import does_not_exist as dne
2. run pdoc  test.py --skip-errors --html -f form the CLI
3. remove the import line and run again to see confirm the output.

### Additional info
- I could be overlooking something but I have not been able to find a way to quickly ignore these errors from the CLI even though it seems like the functionality was once added. 
- pdoc version: pdoc.exe 0.10.0
- Thanks for the help!

**Comment by dingetje** [comment]
I can confirm the --skip-errors command line option is not working as expected.
