### ISSUE TITLE
syntax error with match-case function

### ISSUE THREAD

**Issue by rqm243** [pdoc3/pdoc#428]
Hi trying to run pdoc for a module but keeps coming up with a syntax error.

The command used to run pdoc:
```bash
pdoc {PKG_name} --html --output-dir public --config "syntax_highlighting=False"  
```

This generates an error:
```bash
    match num:
          ^
SyntaxError: invalid syntax
```

- pdoc version: 0.10.0

**Comment by kernc** [comment]
The error most likely comes from the fact that your codebase contains [`match` keywords](https://peps.python.org/pep-0622/), but you're running pdoc in an environment with Python version < 3.10, before the keyword was made available ...

Please reopen if not the case.
