### ISSUE TITLE
Text files generation

### ISSUE THREAD

**Issue by b09dan** [pdoc3/pdoc#43]
### Expected Behavior

At the home page of the project it is stated that library has an ability of "Plain text, HTML, or PDF output". It is expected to have such command:

`pdoc3 --text --text-dir ./documentation_dir module_name`

### Actual Behavior

pdoc3 help says that there is no such option like text and it does't provide a name of this option: `pdoc3: error: unrecognized arguments: --text`

### Additional info

- pdoc version: pdoc3 0.5.3

**Comment by kernc** [comment]
Have you tried plainly `pdoc module_name` which outputs slightly adapted original markdown?

**Comment by b09dan** [comment]
@kernc thanks for reply! Yeah, but I thought it has different functionality, as it doesn't look whole project recursively, like pdoc with option “--html” does. May be there is a possibility to have similar output (html file on each module that are specified through imports in selected module)?
E.g. it is result of `pdoc3 --html --html-dir documentation backend`:
```bash
/srv/documentation/
└── backend
    ├── config
    │   ├── dev_config.html
    │   ├── index.html
    │   ├── params.html
    │   └── prod_config.html
    ├── helpers
    │   ├── index.html
    │   └── is_int.html
    ├── index.html
    ├── modules
    │   ├── ai_consultant
    │   │   ├── index.html
    │   │   ├── models.html
    │   │   └── route.html
    │   ├── authentication
    │   │   ├── auth.html
    │   │   ├── index.html
    │   │   └── models.html
    │   ├── home_page
    │   │   ├── home_page.html
    │   │   └── index.html
    │   ├── index.html
    │   ├── process_mining
    │   │   └── index.html
    │   └── survey
    │       ├── index.html
    │       ├── interact
    │       │   ├── answer_creator.html
    │       │   ├── index.html
    │       │   ├── session_setter.html
    │       │   └── survey_getter.html
    │       ├── manage
    │       │   ├── index.html
    │       │   ├── language_getter.html
    │       │   ├── survey_assessment.html
    │       │   ├── survey_creator.html
    │       │   ├── survey_dimension_type_getter.html
    │       │   ├── survey_getter.html
    │       │   ├── survey_scope_getter.html
    │       │   ├── survey_updater.html
    │       │   └── user_getter.html
    │       ├── models.html
    │       └── routes.html
    └── run.html
```
And it is output of `pdoc3 backend`

**Comment by kernc** [comment]
Indeed, it's different. I believe the text output was initially meant more for instant in-terminal module doc viewing.

You could achieve about the thing you expect with:
```bash
find project/dir -name '*.py' \! -ipath '*/_[a-z]*' \
    -exec sh -c 'mkdir -p "md/$(dirname "$1")"; pdoc "$1" > "md/$(dirname "$1")/$(basename "$1").md"' -- {} \;

tree md
```
This is somewhat involved, and it's not particularly portable, so your request is justified.

May I ask why you seek to get text files?

**Comment by b09dan** [comment]
@kernc thanks, I also thought about similar solution! I will try to implement it in your library in the future!

> May I ask why you seek to get text files?

I have two main reasons:
1. I need to import generated documentation to the project wiki. It doesn't take any effort with markdown.
2. My chef wants to see docs in single document  (It is easy to convert markdown files to .docx/.pdf/.odt)

**Comment by themmes** [comment]
Quick question @b09dan if using your second suggestion `pdoc backend` where would I find the generated `.md` doc files? Or how could I specify say `--md-dir` ?

**Comment by b09dan** [comment]
It would be generated in the same directory of corresponding .py file. As I understood there is no any option to modify this behavior. 
__________________________________________________ 
С уважением, 
Богдан Лашков 
i@bogdan.co

**Comment by kernc** [comment]
I think, ideally, `--html-dir` would become `--output-dir`, and that's where the files lie.
