### ISSUE TITLE
"x | y" does not work but "Union[x, y]" does

### ISSUE THREAD

**Issue by AnthonyZJiang** [pdoc3/pdoc#441]
e.g. for a method:

```
def get_val() -> int | str:
    """Get value.

    Returns:
        int | str: the value.
    """
    pass
```

### Expected Behavior

def get_val() ‑> int | str
Get value.

**Returns**
    _int | str_
The value.

### Actual Behavior

def get_val() ‑> int | str
Get value.

**Returns** 
    int | None The value.

See more details in the attached picture

### Additional info

- pdoc version: 0.10.0

# Example 1
Here is the example in action, comparing | and Union:
![image](https://github.com/pdoc3/pdoc/assets/8778250/e6aed3fd-61f1-4fe9-8e06-068130a510f9)

# Example 2
Here's another example of using | instead of Union:
![image](https://github.com/pdoc3/pdoc/assets/8778250/bc27a5e6-911d-41ea-8fba-badbd6d9c164)

**Comment by ERosendo** [comment]
@kernc is Anyone working on a fix for this yet? I'd be happy to take a look and see if I can help fix it.

**Comment by ERosendo** [comment]
@AnthonyZJiang, can you rerun the command and let us know if the problem you encountered earlier is fixed? Any additional details you can give would be helpful if it's still happening.

**Comment by AnthonyZJiang** [comment]
The issue is solved. The doc was generated correctly. I appreciate your dedication and fast response.
