### ISSUE TITLE
pdoc3 0.11.0 installation regression vs 0.10.0.

### ISSUE THREAD

**Issue by MattiasDC** [pdoc3/pdoc#444]
### Expected Behavior
`uv pip install pdoc3==0.11.0` installs pdoc3 successfully.

### Actual Behavior
uv fails to install pdoc3, while it has no problems installing version 0.10.0

I get the following error; it seems like the build/setup installation requirements are failing:
`  File "~/.cache/uv/.tmp5mxxWy/.venv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'tomli>=1; python_version < "3.11"' distribution was not found and is required by the application`
### Steps to Reproduce

1. Install uv
2. `uv venv`
3. `. .venv/bin/actuvate`
4. `uv pip install pdoc3==0.11.0`

### Additional info

- pdoc version: 0.11.0

**Comment by kernc** [comment]
Correct me if I'm wrong, but this doesn't look our issue nor of a dependency of ours:
https://github.com/pdoc3/pdoc/blob/d1136eafa45315bf5e89596197a24804e4790ee6/setup.py#L49-L56

https://github.com/search?type=code&q=tomli%3E%3D1%3B+python_version+%3C+%223.11%22

**Comment by MattiasDC** [comment]
I checked on another system and there it works as expected. Closing as problem lies with my system.
