### ISSUE TITLE
version 0.11 is not compatible with python 3.7

### ISSUE THREAD

**Issue by b02laire** [pdoc3/pdoc#445]
Version 0.11 of pdoc3 is not compatible with python 3.7 (despite the pypi page stipulating it is compatible with version >= 3.7), due to the use of typing.Literal which was added in python 3.8

### Expected Behavior
calling  `pdoc3 --html -o ./my_documentation/html /path/to/package` should generate an html documentation.

### Actual Behavior
The command will throw an error:

```shell
Traceback (most recent call last):
  File "/home/user/path/to/venv/bin/pdoc3", line 5, in <module>
    from pdoc.cli import main
  File "/home/user/path/to/venv/lib/python3.7/site-packages/pdoc/__init__.py", line 25, in <module>
    from typing import (  # noqa: F401
ImportError: cannot import name 'Literal' from 'typing' (/usr/lib/python3.7/typing.py)
```

Note than forcing pip to install version 0.10 will fix the issue.
### Steps to Reproduce

1. Create a venv using python 3.7 as interpreter 
2. Install pdoc3 version 0.11
3. Call pdoc3 to generate documentation: `pdoc3 --html -o ./my_documentation/html /path/to/package` 

### Additional info

- pdoc3 version: 0.11
- OS: Ubuntu 22.04
- Python 3.7

**Comment by kernc** [comment]
Well, Python v3.7 is in Debian oldoldstable, and it has been [EOL'd already last year](https://devguide.python.org/versions/). Is there a good reason for you to postpone updating? I'm leaning to bumping minimum Python version to 3.9 or 3.11 by policy, as [corresponded by CI already](https://github.com/pdoc3/pdoc/commit/65459eab0b2c25cc87dc4c33328eb7c620068c26).

But if one mere `Literal` is in question, we can also revert ...

**Comment by b02laire** [comment]
Currently we're unable to migrate our infrastructure to a newer version of Debian, but capping our version of pdoc3 to 0.10 should be enough for our usage.  

No need to revert anything, I just wanted to let you know the minium Python version should be bumped :slightly_smiling_face:
