### ISSUE TITLE
Dispaly Global Variables in pdoc

### ISSUE THREAD

**Issue by KyleKing** [pdoc3/pdoc#46]
For example, in a `definitions.py` file, I might have:

```py
"""Definitions: Create Global Reference Variables."""

import math
from pathlib import Path

# Base directory path
PTH_PROJ = Path.home() / 'Program Files (x86)/FooBar'

# Some Dictionary
COUNT_MAP = {
    'one': 1,
    'eleven': 11,
    'septendecillion': math.pow(10, 54),
}
```

Is there a way to show these public global variables (`PTH_PROJ` and `COUNT_MAP`) in the generated pdoc documentation?

**Comment by kernc** [comment]
Yes, you can [document public variables](https://pdoc3.github.io/pdoc/doc/pdoc/#docstrings-for-variables) by using PEP 224-proposed docstrings for variables, i.e. string literal directly following variable assignment:
```py
PTH_PROJ = Path.home()
"""Base directory path"""

COUNT_MAP = {}
"""Some dictionary"""
```

**Comment by KyleKing** [comment]
Awesome, thanks!
