### ISSUE TITLE
Feature request: consider supporting 2-spaces-indentation

### ISSUE THREAD

**Issue by wq2012** [pdoc3/pdoc#5]
### Expected Behavior

Some python libraries use 2-spaces-indentation instead of 4 spaces or single tab.

The user would expect being able to use an argument to support that.

### Actual Behavior

Currently no argument seems to support that.

And by default it will generate badly formatted documentation for such libraries.

### Steps to Reproduce

N/A

### Additional info

- pdoc version:
0.5.1

**Comment by kernc** [comment]
I was reluctant to accept this at first as everybody knows that the one true legible indentation for Python is 4-space indentation. But apparently [there](https://github.com/tensorflow/tensorflow) [really are](https://github.com/google/pytype) well-established projects that remain to follow the [_old_](https://google.github.io/styleguide/pyguide.html#s3.4-indentation) Google pystyle recommendation of 2-space indents. It thus makes sense to support this intentation in Google-style documentation as well.

**Comment by wq2012** [comment]
Thanks a lot for the update.

Indeed, the issue is because of google's old and internal styles.

FYI, I'm using pdoc for [this repo](https://github.com/google/uis-rnn), which is based on 2-space indentation.

[Generated docs](https://google.github.io/uis-rnn/) now look great! Thanks for the changes.

**Comment by kernc** [comment]
Support for Google docstrings is fairly recent. If you have any other ideas for improvement, they are very welcome.
