### ISSUE TITLE
Ignore sub-modules

### ISSUE THREAD

**Issue by cs01** [pdoc3/pdoc#52]
First of all I want to say I absolutely LOVE how easy it is to install and run `pdoc`. So thank you!

The feature I am requesting is the ability to ignore certain sub-modules. For example, on my docs (https://cs01.github.io/pygdbmi/), I don't want `pygdbmi.StringStream` or `pygdbmi.printcolor` to appear in generated documentation.

Maybe something like:
```
pdoc3 --ignoreRegex "StringStream|printcolor" --html mypackage
```

**Comment by kernc** [comment]
Does using [`__pdoc__` dict](https://pdoc3.github.io/pdoc/doc/pdoc/#overriding-docstrings-with-__pdoc__) maybe work for you?
```py
# pygdbmi.py

__pdoc__ = {
    'StringStream`: False,
    'printcolor': False,
}
```

**Comment by cs01** [comment]
That works, thank you! I put it in my `__init__.py` file.

**Comment by kernc** [comment]
At the top or [at the bottom](https://docs.python.org/3/library/argparse.html#epilog). Documentation improvements welcome!

**Comment by kernc** [comment]
Duplicate of https://github.com/pdoc3/pdoc/issues/12.

**Comment by mrduhart** [comment]
> Does using [`__pdoc__` dict](https://pdoc3.github.io/pdoc/doc/pdoc/#overriding-docstrings-with-__pdoc__) work for you?
> 
> ```python
> # pygdbmi.py
> 
> __pdoc__ = {
>     'StringStream`: False,
>     'printcolor': False,
> }
> ```

I have spent some 20 minutes reading through the [pdoc documentation](https://pdoc3.github.io/pdoc/doc/pdoc/#command-line-interface), the repo issues and testing what you suggest here with my own package.

...it wouldn't hurt to add a working example of how to omit specific package modules to the docs.

> There is nothing in the programming field more despicable than an undocumented program. — Ed Yourdon ;)
