### ISSUE TITLE
add custom homepage intro

### ISSUE THREAD

**Issue by cs01** [pdoc3/pdoc#53]
It would be nice if the homepage allowed some more context to be written. For example, passing the path to an arbitrary markdown file, such as the README.md, or any other arbitrary content.

Example call:
```
pdoc --index README.md --html mypackage
```

**Comment by kernc** [comment]
We support [`.. include::` reST directive](https://pdoc3.github.io/pdoc/doc/pdoc/#supported-rest-directives).

I.e., in your main module:
```py
"""
.. include:: ../README.md
"""
...
```

**Comment by cs01** [comment]
Thanks that definitely helps. I have some html in my markdown and it looks like it has some trouble formatting it. 
![image](https://user-images.githubusercontent.com/5715368/56940802-72e19a00-6ac5-11e9-898d-5d6b9345bc13.png)

This is what it seems to have trouble with in the README.md:
```
<h1 align="center">
pygdbmi - Get Structured Output from GDB's Machine Interface
</h1>

<p align="center">
<a href="https://travis-ci.org/cs01/pygdbmi">
<img src="https://travis-ci.org/cs01/pygdbmi.svg?branch=master" />
</a>

<a href="https://pypi.org/project/pygdbmi/">
<img src="https://img.shields.io/badge/pypi-v0.9.0.1-blue.svg"/>
</a>

<img src="https://img.shields.io/badge/python-2.7,3.4,3.5,3.6,pypy-blue.svg"/>
<a href="https://github.com/ambv/black"><img src="https://img.shields.io/badge/code%20style-black-000000.svg" alt="Code style: black" /></a>
</p>
```

**Comment by kernc** [comment]
Yikes! Care to open a new issue for this?

**Comment by kernc** [comment]
Should be fixed in master. :flushed: Thanks!

**Comment by cs01** [comment]
Thanks! That is definitely better. There is still some abnormal formatting though.

This is generated
![image](https://user-images.githubusercontent.com/5715368/56973659-26787780-6b22-11e9-879e-8944f9afb363.png)

From this markdown source code
```
**Documentation**: https://cs01.github.io/pygdbmi/
**Source Code**: https://github.com/cs01/pygdbmi
```

**Comment by kernc** [comment]
Should be fixed in master. Thanks again! And keep them coming! :laughing:

**Comment by cs01** [comment]
Nice, thanks for all the quick responses 👍 .
