### ISSUE TITLE
numpydoc: Return types without description not displayed correctly

### ISSUE THREAD

**Issue by rkaminsk** [pdoc3/pdoc#54]
I am using numpydoc style docstrings. But when undocumented return types are used, then the type is displayed as normal text. For example in:
```python
"""
Returns
-------
None
"""
```
When adding a description, then it is rendered correctly:

```python
"""
Returns
-------
None
    Nothing to return.
"""
```

I am using pdoc 0.5.4.

**Comment by rkaminsk** [comment]
I had a look at how this could be fixed. As far as I can see one would have to handle it as a special case similar to what is done with the `See Also` section. For my purposes, I simply hacked the `to_html` function in `html.mako`, which I modified already anyway. If you are interested, I can implement it a little nicer in pdoc and open a pull request.

```python
_re_returns = re.compile(r"^(?<=Returns\n-{7}\n)(?P<type>[^\n]*)(?=(\Z|\n\Z|\n[^ ]))", re.MULTILINE)

def _rep_returns(match):
    return '{}\n    DUMMY DESRIPTION TO REMOVE'.format(match.group('type'))

def to_html(text):
    text = _re_returns.sub(_rep_returns, text)
    text = _to_html(text, module=module, link=link)
    text = text.replace('<dd>DUMMY DESRIPTION TO REMOVE</dd>', '')
    return tex
```

**Comment by kernc** [comment]
I, too, thought it probably wouldn't go without special casing. I'd be interested in a solution involving md→md transformation like the one for See Also.

In fact, a Returns section with a single return type without description is not that different from See Also section with a single reference ... :thinking:

**Comment by rkaminsk** [comment]
> In fact, a Returns section with a single return type without description is not that different from See Also section with a single reference ...

True. But at first I thought that
```
"""
Returns
-------
None
    Nothing to return.
"""
```
is rendered correctly when in fact it is not. `None` is set like an identifier but it is a type. Right?

**Comment by kernc** [comment]
Right. :sweat_smile:

**Comment by kernc** [comment]
@rkaminsk Care enough to fix it? :grin:

**Comment by rkaminsk** [comment]
I was already hinting that I would. :smile: Might take a couple of days though before I have time to touch this again. I'll open a pull request once ready.

**Comment by rkaminsk** [comment]
I had a closer look. It seems like different regular expression have to be used for different sections. There are two groups:

1. `Returns`, `Yields`, `Raises`, `Warns`
2. `Parameters`, `Receives`, `Other Parameters`

So I would add a regular expression to match a section (from the header to the next section header or the end).  Then, within a matched section replace based on the section type.

The additional step is needed because both groups have to be treated differently. An entry without the `: ...` part corresponds to a parameter name in the first group and to a type in the second group.

I don't see a way to do it with one regular expression with the `re` module as it is done at the moment. It would be possible with the `regex` module. But then the expressions would get even tougher to read.

Shouldn't be too complicated. :smile:

**Comment by kernc** [comment]
Good. :+1:
