### ISSUE TITLE
Support PEP 484 type hints

### ISSUE THREAD

**Issue by nbraud** [pdoc3/pdoc#6]
### Expected Behavior

When generating doc for a package that is annotated with [PEP 484] type hints, I would expect the type hints to be present in the documentation.

[PEP 484]: https://www.python.org/dev/peps/pep-0484/

For example, the following definition
```python3
def foo(x: Bar, repeat : int = 1):
    """Foo-cate a Bar a number of times (default: 1)."""
    ...
```

results in the type hints being available in the REPL's `help()`:
```python3
>>> help(foo)
foo(x: __main__.Bar, repeat: int = 1)
    Foo-cate a Bar a number of times (default: 1).
```

and it should well as be present in the pdoc-generated documents:
```markdown
$ pdoc example.py
Module example
==============

Functions
---------

`foo(x: Bar, repeat: int = 1)`
:   Foo-cate a Bar a number of times (default: 1).

Classes
-------

`Bar`
```

### Actual Behavior

`pdoc` ignores the type-hints:
```markdown
$ pdoc example.py
Module example
==============

Functions
---------

`foo(x, repeat=1)`
:   Foo-cate a Bar a number of times (default: 1).

Classes
-------

`Bar`
```

Type hints document the expected types of parameters and return values.  As such, they convey a lot of information for the documentation's user, when present.

See [PEP 484] for a discussion of type hints.

### Steps to Reproduce

Generate documentation for a module that uses type hints

### Additional info

- pdoc version: 0.5.1
- Python version: 3.7.2 (default, Jan  3 2019, 02:55:40)

**Comment by kernc** [comment]
Would you be interested in doing a pull request for that?

You would need to
* [ ] add a new method `pdoc.Function.annotations()` (likened to [`pdoc.Function.params()`](https://github.com/pdoc3/pdoc/blob/e7868e286c260650daeee478a8b2f1e9ed4c8767/pdoc/__init__.py#L1341-L1396), likely simpler), and
* [ ] modify HTML template to ([conditionally](https://github.com/pdoc3/pdoc/blob/e7868e286c260650daeee478a8b2f1e9ed4c8767/pdoc/templates/html.mako#L19-L32)) show type annotations.

**Comment by nbraud** [comment]
@kernc Sorry, I had entirely missed you replied here.  Yes, obviously I'm pretty interested in writing the code for this  ^.^

**Comment by omtinez** [comment]
@nbraud do you plan on submitting a PR with [your commit](https://github.com/nbraud/pdoc/commit/1d67571fc0bc280c06eb973ec9cfa360ac24c63a)?

**Comment by kernc** [comment]
@omtinez PR https://github.com/pdoc3/pdoc/pull/7 is in progress. Welcome to continue where it's left off.

**Comment by kernc** [comment]
This is not done. Text template doesn't look into config.mako nor does it print types by default. I'll see what I can do about that and about hyperlinking documented types in HTML output.

**Comment by kernc** [comment]
Hyperlinked types testable with:
```bash
pdoc --html -c show_type_annotations=True your_module
```

**Comment by DaniGuardiola** [comment]
Types are not showing up on my project. Fresh `pdoc3` install so I assume it is the latest version published, testing it with `--http` option. Am I missing something? Thanks :)

**Comment by DaniGuardiola** [comment]
After some more testing I've seen it works pretty well, nice!

I have a couple of suggestions:

- Class / instance property and variable types are not being documented.
- Standard library types could be linked to the official online documentation, specially the `Typings` library.

**Comment by kernc** [comment]
@DaniGuardiola, care to open a new issue for missing variable/property annotations?
