### ISSUE TITLE
live reload when serving locally

### ISSUE THREAD

**Issue by cs01** [pdoc3/pdoc#60]
https://twitter.com/burntsushi5/status/1124671095725002752

**Comment by kernc** [comment]
While the web page needs to be refreshed manually, the server doesn't (shouldn't) require to be shut down and restarted as module reloading is in place.
https://github.com/pdoc3/pdoc/blob/f5b4a5484a2add2ab1b276267248fe54e1dbf1a0/pdoc/__init__.py#L169-L175

If there's a bug somewhere, the `import_module()` mechanism is being improved as we speak.

**Comment by cs01** [comment]
Ah I was editing docs for pdoc itself, hence the server wasn't reloading. Still the client-side reload is a nice feature. What do you think?

**Comment by kernc** [comment]
If something can be done in about three lines of WebSocket JS API and maybe twice that on the Python end without heavy extra dependencies, absolutely love to see it.
