### ISSUE TITLE
use default host/port when serving

### ISSUE THREAD

**Issue by cs01** [pdoc3/pdoc#61]
Make CLI API more friendly such that it defaults to using `localhost:8000` if no host/port is specified.

**Comment by kernc** [comment]
When only colon is provided (`--http :`), the defaults _are_ used.

There's no way to make the parameter to `--http` optional. I.e. how can Python (argparse) know "foo" is not a host/port specification?
```bash
pdoc --http foo bar
```

**Comment by cs01** [comment]
The cli would have to either add commands such as `pdoc build PACKAGE`, `pdoc serve PACKAGE` or change the meaning of `--http` to be `action=store_true` and add another optional parameter `--url`.

**Comment by kernc** [comment]
But you don't like `--http :` that you only really type out once? :slightly_smiling_face:

**Comment by cs01** [comment]
I am sure I am getting a little annoying by now 😄 but no, I want a default to be something I don't have to type. Otherwise it's not really a default, even if it is only one character.
