### ISSUE TITLE
Logo like pdoc3 docs 

### ISSUE THREAD

**Issue by SoulSen** [pdoc3/pdoc#71]
Is there a way to add a logo like the pdoc3 docs have?

**Comment by kernc** [comment]
pdoc3 docs use [custom _logo.mako_ template](https://pdoc3.github.io/pdoc/doc/pdoc/#custom-templates)
https://github.com/pdoc3/pdoc/blob/f2d8fe04575f35d6afec7c5c465d39d73e13ced3/doc/pdoc_template/logo.mako#L1-L5
with some additional CSS in _head.mako_:
https://github.com/pdoc3/pdoc/blob/f2d8fe04575f35d6afec7c5c465d39d73e13ced3/doc/pdoc_template/head.mako#L1-L24

The docs are then built with `--template-dir` switch.

**Comment by SoulSen** [comment]
Thanks
