### ISSUE TITLE
Splitting the intro page into multiple pages

### ISSUE THREAD

**Issue by shbhuk** [pdoc3/pdoc#73]
Hi,
Is there any functionality such that all the contents are not shown on the same page.
For example on the pdocs documentation website, if each of the subsections had its own page? 
Is this already implemented?

**Comment by kernc** [comment]
Why not simply split your project into sensible submodules ([example](https://koaning.github.io/brent/))?

**Comment by shbhuk** [comment]
Hi,
The code is already split into separate modules. 
I ask for this functionality for the text/tutorial/examples etc.

**Comment by kernc** [comment]
Including other markdown files is possible via the [`.. include::` directive](https://pdoc3.github.io/pdoc/doc/pdoc/#supported-rest-directives).
https://github.com/pdoc3/pdoc/blob/f2d8fe04575f35d6afec7c5c465d39d73e13ced3/pdoc/__init__.py#L1-L9

**Comment by kernc** [comment]
I see. How would this work?

pdoc is meant mainly for API docs! Its primary use case is short usage introduction preceding API reference.

**Comment by shbhuk** [comment]
I get that. However would be nice if different `..include::` files went to different pages. 
What do you think?

**Comment by kernc** [comment]
Certainly not with [`.. include::`](http://docutils.sourceforge.net/docs/ref/rst/directives.html#including-an-external-document-fragment) as this directive has an established, known outcome.

It's not that hard to make a hyperlink explicitly:
```markdown

Find more examples on the [Examples] page.

[Examples]: ./examples.html
```

That extra page can then be constructed by any convenient means.

If you're counting mostly on prose documentation, perhaps what you're after is more in line with how [Sphinx](https://www.sphinx-doc.org/), [MkDocs](https://www.mkdocs.org/), or even [Nikola](https://getnikola.com/) operate. (Unfortunately, [Nikola only supports old pdoc](https://plugins.getnikola.com/v8/pdoc/) as a plugin.)

**Comment by kernc** [comment]
Why not just make a submodule `examples` with little/no public API code, instead containing just prose introduction? You can then link to it with:
```
`my_project.examples`
```

**Comment by kernc** [comment]
Opposing the idea, I'll close for the time being. _Docs hierarchy follows module hierarchy_ is one of the main selling points of the program. I think the comment above shows the appropriate way to go.

If you care to find a strong counter argument, envision further details, and propose a reasonable implementation, welcome to comment/reopen.
