### ISSUE TITLE
able to only display docstring (and not display source code)?

### ISSUE THREAD

**Issue by zachvalenta** [pdoc3/pdoc#81]
Is pdoc able to only display docstrings and omit displaying the source code?

<img width="770" alt="Screen Shot 2019-07-23 at 2 05 16 PM" src="https://user-images.githubusercontent.com/11388735/61736018-2b307e80-ad53-11e9-9902-86049d440f0f.png">

### Additional info

- pdoc version: 0.6.3

**Comment by kernc** [comment]
Yes, see [`show_source_code`](https://github.com/pdoc3/pdoc/blob/c48c722adba1b6509e8716fc38ec4a76c7c83d85/pdoc/templates/config.mako#L11-L13) template tunable in config.mako.

Running `pdoc` with `-c show_source_code=False` command line argument should work.

**Comment by zachvalenta** [comment]
worked like a charm; thanks!

![Screen Shot 2019-07-24 at 12 51 50 PM](https://user-images.githubusercontent.com/11388735/61812639-e4558e00-ae11-11e9-80ad-3d6dda083581.png)

**Comment by EugeniaVeselova** [comment]
It would be very helpful to highlight this method in documentation!

**Comment by zachvalenta** [comment]
be happy to open a PR; @kernc what do you think?

**Comment by kernc** [comment]
@zachvalenta Sure. Which section do you think?

**Comment by kernc** [comment]
Maybe also a [link to FAQ](https://github.com/pdoc3/pdoc/issues?q=is%3Aissue+label%3Aquestion)?

**Comment by zachvalenta** [comment]
> @zachvalenta Sure. Which section do you think?

https://github.com/pdoc3/pdoc/blob/master/pdoc/documentation.md#command-line-interface -> how about here?

**Comment by zachvalenta** [comment]
> Maybe also a [link to FAQ](https://github.com/pdoc3/pdoc/issues?q=is%3Aissue+label%3Aquestion)?

I don't grok the link here; can you elaborate?

**Comment by kernc** [comment]
I meant, consider also linking to the FAQ to make similar answers even more discoverable.

**Comment by zachvalenta** [comment]
> I meant, consider also linking to the FAQ to make similar answers even more discoverable.

Gotcha, that link just seems to go to a list of issues. I dug around but don't see an `faq.md` or section of the docs explicitly labeled 'FAQ'. Am I missing something?

**Comment by kernc** [comment]
Yes, a list of issues tagged _question_. The format is convenient and it looks like it will stick. :grin:
