### ISSUE TITLE
citation for quote from Github pages

### ISSUE THREAD

**Issue by zachvalenta** [pdoc3/pdoc#82]
There's a quote at the bottom of the [Github pages site](https://pdoc3.github.io/pdoc/):

> There is nothing in the programming field more despicable than an undocumented program. — Ed Young

Do you have a citation for it?

**Comment by kernc** [comment]
I don't remember where I filtered the quotes from, but apparently that one is wrong. :sweat_smile:
Should be _Ed Yourdon_. :+1:
