### ISSUE TITLE
Feature Request: allow syntax highlighting without showing source code

### ISSUE THREAD

**Issue by Jeremy-Stafford** [pdoc3/pdoc#84]
The `highlight.js` styles are only included if `show_source_code` is true, which means that syntax highlighting in doc-strings is only available when `show_source_code` is true. This _can_ be solved by editing the `html.mako` template, but it would be easier if there was a flag (eg `enable_syntax_highlighting`) which did specifically included the `highlight.js` styles.

**Comment by kernc** [comment]
Something like `syntax_highlighting = bool(show_source_code)`? PR welcome. :+1:
