### ISSUE TITLE
Please remove the swastika from the web site

### ISSUE THREAD

**Issue by mthuurne** [pdoc3/pdoc#87]
@kernc: The swastika is a symbol that has very different interpretations, depending on context. In #64 you explain that you intend it in a Buddhist sense, but since there is no context on the web site itself, it is easy for a visitor to interpret it as a Nazi symbol instead, and for most people in the West that will be default interpretation.

I think it would be better to avoid all possible misinterpretations by just leaving the space blank or use a symbol that has less variation in interpretation.

**Comment by kernc** [comment]
Made you look. :grin:

I don't see how many intelligent people reaching the website would be readily prone to confusing an object so lightly contrasted and so out of context of Nazi propaganda (particularly considering how that's now illegal most places; i.e. hate speech), and instead not find it curiously odd and rather inviting for them to maybe question their assumptions, as you have.

It's controversial, but save for the few lucky ones, most people miss it anyway. It's not a real issue as much as it's a matter of weird taste, is it not?

**Comment by mthuurne** [comment]
It is a real issue for me, since I don't want to link to the site as it is now. Therefore I won't be using pdoc3 in my projects anymore, which is a shame, since at a technical level it is a good tool.

**Comment by derek-adair** [comment]
Shameful what those nazi's did, its been around since [500 B.C](https://en.wikipedia.org/wiki/Swastika#Etymology_and_nomenclature).  Unfortunately, best to remove it as the subtle differences will be missed by all those not educated in the history of religion.

**Comment by mvasilkov** [comment]
Please keep it, if only for the sake of messing with these astonishingly entitled people on the interwebs.

**Comment by dhimmel** [comment]
> ![image](https://user-images.githubusercontent.com/1117703/66500890-5bed9d80-ea90-11e9-8806-5e26b8c3a7a6.png)

It appears to me that the association of pdoc3 with the swastika, regardless of the intention, is preventing adoption of the package / driving potential users to other pdoc forks. So @kernc I think you have a choice between greater adoption and continuing with the "wierd taste".

Given your cunning technical acumen (I learned a lot from you review and help in #102), it would be a shame to see this project not adopted. I guess the question to ask is which is more important: the widespread usage of pdoc3 or the statement you are looking to make with the profile image? Is there some other way you could make your point without harming the adoption of this package?

**Comment by 0xLcrgs** [comment]
lmao, entitled ret@rds
