### ISSUE TITLE
Incorporating argparse help

### ISSUE THREAD

**Issue by liliblu** [pdoc3/pdoc#89]
Hello, I was wondering if there is an option for incorporating --help from argparse into the auto documentation? If not, is there a work-around that you have encountered or could think of?
Thank you!

- pdoc version: pdoc 0.6.3

**Comment by kernc** [comment]
A simple workflow that comes to mind is to first export usage help into a file:
```bash
my_prog --help > usage.txt
```
And then include the file inside a docstring (e.g. module docstring) where you want the usage help to appear:
```py
"""
This is my program, which does ...
This is how you use it:

    .. include:: usage.txt

...
```

**Comment by liliblu** [comment]
That works great, thank you!

For a slightly more complicated but adaptable way to do this, i found that using this [tool](https://github.com/9999years/argdown) to convert help to markdown was useful. 

the I use this code to grab all parsers and subparsers --help.
if ```python _make_parser()``` is a function that returns your parser:
```python
parser = _make_parser()
subparsers_actions = [
    action.choices for action in parser._actions if isinstance(action, argparse._SubParsersAction)
]
helps = {}
for choices in subparsers_actions:
    for choice, subparser in choices.items():
        helps[choice] = argdown.md_help(subparser)

doc = []
for k, v in helps.items():
    doc.extend(['# Program: %s' % k, v])
__doc__ = '\n'.join(doc)
```
This should automatically add any updated help docs into the pdoc auto documentation without writing a new txt file. 

Thanks for the quick answer!

**Comment by kernc** [comment]
Yeah, `__doc__` is a dynamic attribute. :sweat_smile:
