### ISSUE TITLE
Feature suggestion: Getting index.html contents from a markdown file

### ISSUE THREAD

**Issue by wq2012** [pdoc3/pdoc#9]
### Expected Behavior

Well, it's not something important, but a nice-to-have feature.

Currently the `<article>` part of `index.html` comes of the docstring of `__init__.py`. However, some authors prefer to leave the details of the package/module in a markdown file like `README.md`, for easier access to the audience, instead of `__init__.py`.

It might be a nice feature if `pdoc` has an argument that supports converting a markdown file to HTML and injecting the converted HTML part into the `<article>` part of `index.html`.

### Actual Behavior

N/A

### Steps to Reproduce

N/A

### Additional info

- pdoc version:
0.5.1

**Comment by kernc** [comment]
Which README.md would that be? The one in the same directory as \_\_init\_\_.py or one upper?

Only README.md or also readme.md, README.txt, README.rst?

**Comment by kernc** [comment]
The way it would yield the most is with [reST `.. include::` directive](http://docutils.sourceforge.net/docs/ref/rst/directives.html#including-an-external-document-fragment).

How do you feel about that?

**Comment by kernc** [comment]
If anyone would have a stab at that, the code is here.
There's already an exception for `.. image::` and `.. figure::`.
https://github.com/pdoc3/pdoc/blob/e2739ced41b66450138c5372378ded8543b9c309/pdoc/html_helpers.py#L189-L215

**Comment by wq2012** [comment]
From the user's perspective, I was thinking of using it like:

```
pdoc mymodule --html --inject-markdown-to-index=/PATH/TO/MY/README.md
```

**Comment by kernc** [comment]
I think that's too ambiguous. Every package with \_\_init\_\_.py has an index. Which index?

Then, you can't control whether the injection is appended to or replaces the existing docstring.

Do you particularly dislike the `.. include::` approach?

**Comment by b52** [comment]
I'm in favor of the `.. include::` approach. Seems easy enough while allowing a lot more flexibility.

On a different page, what is rendered as index when I make `pdoc` build multiple modules?

**Comment by wq2012** [comment]
`.. include::` is definitely good! Flexibility is great.

I was just mentioning an alternative user interface in my previous comment.

**Comment by kernc** [comment]
>
> On a different page, what is rendered as index when I make pdoc build
> multiple modules?
>
Each disjunct package produces its own directory. There is no index.html to
bind them.

**Comment by b52** [comment]
@kernc If you give me some pointers I'll happily write up a PR.

**Comment by kernc** [comment]
* [ ] Make [another admonition `type` exception](https://github.com/pdoc3/pdoc/issues/9#issuecomment-457429725) for `'include'` (probably call another function if more than a couple of lines).
  * [ ] Open up a file, read and return its contents but with each line preceded by `indent`. 
    * [ ] If the file doesn't exist, re-raise a more descriptive exception.
  * [ ] Relative paths should probably be relative to include statement appearance. You will need to pass `module` to `_ToMarkdown.admonitions()` to be able to handle relative includes.
  * [ ] I don't think you need to worry about [directive options](http://docutils.sourceforge.net/docs/ref/rst/directives.html#including-an-external-document-fragment) (`:start-line:`, `:end-line:`, ...) that you would find in `text`. Unless you find them trivial to implement, I'm completely happy if we don't support them or maybe add them later on an as-needed basis.
* [ ] Add a documentation subsection ["Supported reST directives"](https://github.com/pdoc3/pdoc/blob/7500791bef2ff61c4d8bab093b6e2b6ece446836/pdoc/__init__.py#L183-L194), describing in brief what directives are supported and how.

**Comment by b52** [comment]
I wrote up everything as described (minus the start end stuff) in PR #16 .

There is one problem though, the `module` is `Undefined` in my test cases, which means I cannot build a proper path. Any hints?
