### ISSUE TITLE
Whitelisting using `__pdoc__` dict

### ISSUE THREAD

**Issue by Sieboldianus** [pdoc3/pdoc#90]
I've tested pdoc3 and found it a very nice alternative to Sphinx. However, my package doesn't seem to be fully documented. I've a main module which can be imported, and a [\_\_main\_\_.py](https://github.com/Sieboldianus/TagMaps/blob/master/tagmaps/__main__.py) which gets activate if a user directly runs my package in a CLI, e.g.:

```python
if __name__ == "__main__":
    main()
```

This is a pretty standard Python layout. I am not sure if I this is expected behavior for pdoc3.

### Expected Behavior

[\_\_main\_\_.py](https://github.com/Sieboldianus/TagMaps/blob/master/tagmaps/__main__.py) should be automatically documented.

### Actual Behavior

[\_\_main\_\_.py](https://github.com/Sieboldianus/TagMaps/blob/master/tagmaps/__main__.py) isn't included in pdoc3 generated docs

### Steps to Reproduce

1. Clone this [repo](https://github.com/Sieboldianus/TagMaps)
2. Install locally without deps `python setup.py --no-deps`
3. run `pdoc --html tagmaps`

### Additional info

- pdoc version: 0.3.11

**Comment by kernc** [comment]
I believe any modules starting with an underscore are treated as private API.
https://github.com/pdoc3/pdoc/blob/a4a9a22056e8c2182ff5ea8d65b4718ee79439bc/pdoc/__init__.py#L597-L599

IMHO it'd be best advised to document \_\_main\_\_.py, which really only acts as main entry point into your package when run as `python -m your_package`, within \_\_init\_\_.py. Does that make sense? :thinking:

Certainly I don't want to make any dunder module always listed as such.

I'd welcome a feature to be able to include specific identifiers with:
```py
__pdoc__[some_identifier] = True
__pdoc__['your_project.__main__'] = True
```
Similarly to how they can be forced [excluded with `False`](https://pdoc3.github.io/pdoc/doc/pdoc/#overriding-docstrings-with-__pdoc__).

**Comment by Sieboldianus** [comment]
> IMHO it'd be best advised to document __main__.py, which really only acts as main entry point into your package when run as `python -m your_package`, within __init__.py. Does that make sense? 🤔

Yes, that's how it works for most packages. __main__.py is really a [special convention](https://docs.python.org/3/library/__main__.html) by python, which would justify special treatment by pdoc3, e.g. `__pdoc__['your_project.__main__'] = True` 👍

**Comment by kernc** [comment]
Fixed in https://github.com/pdoc3/pdoc/pull/144, https://github.com/pdoc3/pdoc/commit/d0d925998050a1bd6f1fe6a95efe0f44eb65fe84.
