### ISSUE TITLE
Programmatic usage example needs updating

### ISSUE THREAD

**Issue by stevegore** [pdoc3/pdoc#91]
### Expected Behavior
Running the example should return documentation with no exceptions

### Actual Behavior
Running the example with actual module names fails with: `AttributeError: 'str' object has no attribute '__name__'`

### Steps to Reproduce

1. Copy paste the example provided
2. Replace 'a', 'b' with module names or a path to a module.
3. Execute.

Attempting to use `pdoc.import_module(mod)` is not sufficient to make the example viable.

### Additional info

- pdoc version: 0.6.3

**Comment by kernc** [comment]
I guess I thought I made the call to `import_module()` optional ages ago. :sweat_smile:
PR https://github.com/pdoc3/pdoc/pull/92 should fix it. Care to verify?

**Comment by stevegore** [comment]
Hi, tested it out and it's working as expected now. Thanks!

**Comment by stevegore** [comment]
Related question though - I'm trying to work out how to create the module listing programmatically. It looks like your mako template changes format based on context:

```mako
<%
    module_list = 'modules' in context.keys()  # Whether we're showing module list in server mode
%>
```

But I'm looking for a convenient way of getting the module list to appear. Does such a method exist?

**Comment by kernc** [comment]
It's not related. Can you please open a new issue for this? :grin:
