### ISSUE TITLE
Avoid URL manipulation inside code blocks

### ISSUE THREAD

**Issue by AlexFiliakov** [pdoc3/pdoc#96]
### Expected Behavior
When a docstring has URL inside a code block, display the text as-is without adding any extraneous characters.

### Actual Behavior
Inside code blocks, the URL gets surrounded with <>

(If the code block containing the URL is intended to be copy-pasted somewhere, the appended <> causes problems)

### Steps to Reproduce

1. set your docstring to """For questions ```refer to https://www.google.com```"""
2. generate pdoc3
3. Documentation will say: For questions ```refer to <https://www.google.com```>

(I don't want <> at all, though it also appends > outside of the code block)

### Additional info

- pdoc version: 0.6.3

**Comment by kernc** [comment]
Agreed, code blocks should remain verbatim. Unfortunately, pdoc uses regexes to preprocess raw text into markdown, so detecting and excepting for code blocks might be tricky ...
https://github.com/pdoc3/pdoc/blob/9d71e3269f32c00828d7698d07ca2df0ef8007cc/pdoc/html_helpers.py#L318-L320
PR welcome!
