### ISSUE TITLE
pdoc3 decorator issue

### ISSUE THREAD

**Issue by Sieboldianus** [pdoc3/pdoc#98]
I work heavily with decorators in my packages, mostly to reduce repetition of code (repeated pre-checks needed for multiple functions; repeatedly needed automatic conversion of input/output data). Unfortunately, this bug affects the most important public api class most because this is where I use decorators most (e.g. to check valid user interaction).

# Expected Behavior

Most importantly, the documentation should show the function that is decorated, not the decorator itself. Not sure about the best way to docuemnt Decorators - they should be shown in Source Code Window as is. If they are not named with an underscore (_), it makes sense listing them separately.

### Actual Behavior

Functions decorated with decorators (@MyDecClass.check_values()) will be replaced by the decorator Code in pdoc3, including any docstrings - e.g. if the function has a docstring, but is decorated with a decorator without docstring, no docstring will be shown.

### Steps to Reproduce

1. Create a function with a decorator, e.g.:

```python

class EchoClass():
    """Parent class with public api functions for package"""
    self.echo_data = None

    class _PrivateDecorators():
        """Private Decorators for checking functions in EchoClass"""
        @staticmethod
        def _init_data_check(func):
            """Check if echo_data has been initialized

            In pdoc autogenerated docs, this docstring
            replaces the docstring from echo_toplists(),
            including the Source Code
            """

            def _wrapper(self, *args, **kwargs):
                # init echo data
                if self.echo_data is None:
                    # do something first
                return func(self, *args, **kwargs)
            return _wrapper
    
    @_PrivateDecorators._init_data_check
    def echo_toplists(self):
        """Print toplists for items to output


        This is the main public function. This text is not displayed
        in pdoc generated documentation, neither is the code below.
        """
        print("Toplist")
```
2. Create documentation `pdoc --http : echo_package`
3. Observe the following:

![dec_pdoc](https://user-images.githubusercontent.com/13646666/63632774-50a7f500-c63d-11e9-95fe-e18d89263522.png)

(screenshot is taken from my personal package doc, not the example above)

### Additional info

- this happens even if the Decorator class or Decorator names are private (begin with an underscore)
- pdoc version: 0.63 (latest)

**Comment by Sieboldianus** [comment]
It appears that this difficult to solve. There's an issue in the original repo [here](https://github.com/mitmproxy/pdoc/issues/58) which points out some aspects.

I've looked up some solutions, perhaps [this](https://stackoverflow.com/a/43506509/4556479) answer on stack points in the right direction:
It requires adding an attribute to Decorators which stores the original function, e.g.:

```python
wrapper.__wrapped__ = wrapped
```

pdoc3 could then look for this attribute and unwrap it:

```python
def unwrap(func):
    while hasattr(func, '__wrapped__'):
        func = func.__wrapped__
    return func
```

**Comment by kernc** [comment]
pdoc3 does already unwrap. :+1: 

https://github.com/pdoc3/pdoc/blob/9d71e3269f32c00828d7698d07ca2df0ef8007cc/pdoc/__init__.py#L558

The idiomatic solution is to use [`functools.wraps()`](https://docs.python.org/3/library/functools.html#functools.wraps) in your decorator definition.

An example of this working as expected: https://pdoc3.github.io/pdoc/doc/pdoc/#pdoc.Doc.url
